var bullshits = {
    culture: {
        theme: '一天掉多少根头发',
        themeKey: '主题',
        argument: [
            "现在，解决主题的问题，是非常非常重要的。 所以， ",
            "我们不得不面对一个非常尴尬的事实，那就是， ",
            "主题的发生，到底需要如何做到，不主题的发生，又会如何产生。 ",
            "而这些并不是完全重要，更加重要的问题是， ",
            "主题，到底应该如何实现。 ",
            "带着这些问题，我们来审视一下主题。 ",
            "所谓主题，关键是主题需要如何写。 ",
            "我们一般认为，抓住了问题的关键，其他一切则会迎刃而解。 ",
            "问题的关键究竟为何? ",
            "主题因何而发生?",
            "每个人都不得不面对这些问题。 在面对这种问题时， ",
            "一般来讲，我们都必须务必慎重的考虑考虑。 ",
            "要想清楚，主题，到底是一种怎么样的存在。 ",
            "了解清楚主题到底是一种怎么样的存在，是解决一切问题的关键。 ",
            "就我个人来说，主题对我的意义，不能不说非常重大。 ",
            "本人也是经过了深思熟虑，在每个日日夜夜思考这个问题。 ",
            "主题，发生了会如何，不发生又会如何。 ",
            "在这种困难的抉择下，本人思来想去，寝食难安。 ",
            "生活中，若主题出现了，我们就不得不考虑它出现了的事实。 ",
            "这种事实对本人来说意义重大，相信对这个世界也是有一定意义的。 ",
            "我们都知道，只要有意义，那么就必须慎重考虑。 ",
            "既然如此， ",
            "那么， ",
            "我认为， ",
            "一般来说， ",
            "总结的来说， ",
            "既然如何， ",
            "经过上述讨论"
        ],
        quotes: [
            "伏尔泰曾经说过，不经巨大的困难，不会有伟大的事业。这不禁令我深思",
            "富勒曾经说过，苦难磨炼一些人，也毁灭另一些人。这不禁令我深思",
            "文森特·皮尔曾经说过，改变你的想法，你就改变了自己的世界。这不禁令我深思",
            "拿破仑·希尔曾经说过，不要等待，时机永远不会恰到好处。这不禁令我深思",
            "塞涅卡曾经说过，生命如同寓言，其价值不在与长短，而在与内容。这不禁令我深思",
            "奥普拉·温弗瑞曾经说过，你相信什么，你就成为什么样的人。这不禁令我深思",
            "吕凯特曾经说过，生命不可能有两次，但许多人连一次也不善于度过。这不禁令我深思",
            "莎士比亚曾经说过，人的一生是短的，但如果卑劣地过这一生，就太长了。这不禁令我深思",
            "笛卡儿曾经说过，我的努力求学没有得到别的好处，只不过是愈来愈发觉自己的无知。这不禁令我深思",
            "左拉曾经说过，生活的道路一旦选定，就要勇敢地走到底，决不回头。这不禁令我深思",
            "米歇潘曾经说过，生命是一条艰险的峡谷，只有勇敢的人才能通过。这不禁令我深思",
            "吉姆·罗恩曾经说过，要么你主宰生活，要么你被生活主宰。这不禁令我深思",
            "日本谚语曾经说过，不幸可能成为通向幸福的桥梁。这不禁令我深思",
            "海贝尔曾经说过，人生就是学校。在那里，与其说好的教师是幸福，不如说好的教师是不幸。这不禁令我深思",
            "杰纳勒尔·乔治·S·巴顿曾经说过，接受挑战，就可以享受胜利的喜悦。这不禁令我深思",
            "德谟克利特曾经说过，节制使快乐增加并使享受加强。这不禁令我深思",
            "裴斯泰洛齐曾经说过，今天应做的事没有做，明天再早也是耽误了。这不禁令我深思",
            "歌德曾经说过，决定一个人的一生，以及整个命运的，只是一瞬之间。这不禁令我深思",
            "卡耐基曾经说过，一个不注意小事情的人，永远不会成就大事业。这不禁令我深思",
            "卢梭曾经说过，浪费时间是一桩大罪过。这不禁令我深思",
            "康德曾经说过，既然我已经踏上这条道路，那么，任何东西都不应妨碍我沿着这条路走下去。这不禁令我深思",
            "克劳斯·莫瑟爵士曾经说过，教育需要花费钱，而无知也是一样。这不禁令我深思",
            "伏尔泰曾经说过，坚持意志伟大的事业需要始终不渝的精神。这不禁令我深思",
            "亚伯拉罕·林肯曾经说过，你活了多少岁不算什么，重要的是你是如何度过这些岁月的。这不禁令我深思",
            "韩非曾经说过，内外相应，言行相称。这不禁令我深思",
            "富兰克林曾经说过，你热爱生命吗？那么别浪费时间，因为时间是组成生命的材料。这不禁令我深思",
            "马尔顿曾经说过，坚强的信心，能使平凡的人做出惊人的事业。这不禁令我深思",
            "笛卡儿曾经说过，读一切好书，就是和许多高尚的人谈话。这不禁令我深思",
            "塞涅卡曾经说过，真正的人生，只有在经过艰难卓绝的斗争之后才能实现。这不禁令我深思",
            "易卜生曾经说过，伟大的事业，需要决心，能力，组织和责任感。这不禁令我深思",
            "歌德曾经说过，没有人事先了解自己到底有多大的力量，直到他试过以后才知道。这不禁令我深思",
            "达尔文曾经说过，敢于浪费哪怕一个钟头时间的人，说明他还不懂得珍惜生命的全部价值。这不禁令我深思",
            "佚名曾经说过，感激每一个新的挑战，因为它会锻造你的意志和品格。这不禁令我深思",
            "奥斯特洛夫斯基曾经说过，共同的事业，共同的斗争，可以使人们产生忍受一切的力量。　这不禁令我深思",
            "苏轼曾经说过，古之立大事者，不惟有超世之才，亦必有坚忍不拔之志。这不禁令我深思",
            "王阳明曾经说过，故立志者，为学之心也；为学者，立志之事也。这不禁令我深思",
            "歌德曾经说过，读一本好书，就如同和一个高尚的人在交谈。这不禁令我深思",
            "乌申斯基曾经说过，学习是劳动，是充满思想的劳动。这不禁令我深思",
            "别林斯基曾经说过，好的书籍是最贵重的珍宝。这不禁令我深思",
            "富兰克林曾经说过，读书是易事，思索是难事，但两者缺一，便全无用处。这不禁令我深思",
            "鲁巴金曾经说过，读书是在别人思想的帮助下，建立起自己的思想。这不禁令我深思",
            "培根曾经说过，合理安排时间，就等于节约时间。这不禁令我深思",
            "屠格涅夫曾经说过，你想成为幸福的人吗？但愿你首先学会吃得起苦。这不禁令我深思",
            "莎士比亚曾经说过，抛弃时间的人，时间也抛弃他。这不禁令我深思",
            "叔本华曾经说过，普通人只想到如何度过时间，有才能的人设法利用时间。这不禁令我深思",
            "博曾经说过，一次失败，只是证明我们成功的决心还够坚强。 维这不禁令我深思",
            "拉罗什夫科曾经说过，取得成就时坚持不懈，要比遭到失败时顽强不屈更重要。这不禁令我深思",
            "莎士比亚曾经说过，人的一生是短的，但如果卑劣地过这一生，就太长了。这不禁令我深思",
            "俾斯麦曾经说过，失败是坚忍的最后考验。这不禁令我深思",
            "池田大作曾经说过，不要回避苦恼和困难，挺起身来向它挑战，进而克服它。这不禁令我深思",
            "莎士比亚曾经说过，那脑袋里的智慧，就像打火石里的火花一样，不去打它是不肯出来的。这不禁令我深思",
            "希腊曾经说过，最困难的事情就是认识自己。这不禁令我深思",
            "黑塞曾经说过，有勇气承担命运这才是英雄好汉。这不禁令我深思",
            "非洲曾经说过，最灵繁的人也看不见自己的背脊。这不禁令我深思",
            "培根曾经说过，阅读使人充实，会谈使人敏捷，写作使人精确。这不禁令我深思",
            "斯宾诺莎曾经说过，最大的骄傲于最大的自卑都表示心灵的最软弱无力。这不禁令我深思",
            "西班牙曾经说过，自知之明是最难得的知识。这不禁令我深思",
            "塞内加曾经说过，勇气通往天堂，怯懦通往地狱。这不禁令我深思",
            "赫尔普斯曾经说过，有时候读书是一种巧妙地避开思考的方法。这不禁令我深思",
            "笛卡儿曾经说过，阅读一切好书如同和过去最杰出的人谈话。这不禁令我深思",
            "邓拓曾经说过，越是没有本领的就越加自命不凡。这不禁令我深思",
            "爱尔兰曾经说过，越是无能的人，越喜欢挑剔别人的错儿。这不禁令我深思",
            "老子曾经说过，知人者智，自知者明。胜人者有力，自胜者强。这不禁令我深思",
            "歌德曾经说过，意志坚强的人能把世界放在手中像泥块一样任意揉捏。这不禁令我深思",
            "迈克尔·F·斯特利曾经说过，最具挑战性的挑战莫过于提升自我。这不禁令我深思",
            "爱迪生曾经说过，失败也是我需要的，它和成功对我一样有价值。这不禁令我深思",
            "罗素·贝克曾经说过，一个人即使已登上顶峰，也仍要自强不息。这不禁令我深思",
            "马云曾经说过，最大的挑战和突破在于用人，而用人最大的突破在于信任人。这不禁令我深思",
            "雷锋曾经说过，自己活着，就是为了使别人过得更美好。这不禁令我深思",
            "布尔沃曾经说过，要掌握书，莫被书掌握；要为生而读，莫为读而生。这不禁令我深思",
            "培根曾经说过，要知道对好事的称颂过于夸大，也会招来人们的反感轻蔑和嫉妒。这不禁令我深思",
            "莫扎特曾经说过，谁和我一样用功，谁就会和我一样成功。这不禁令我深思",
            "马克思曾经说过，一切节省，归根到底都归结为时间的节省。这不禁令我深思",
            "莎士比亚曾经说过，意志命运往往背道而驰，决心到最后会全部推倒。这不禁令我深思",
            "卡莱尔曾经说过，过去一切时代的精华尽在书中。这不禁令我深思",
            "培根曾经说过，深窥自己的心，而后发觉一切的奇迹在你自己。这不禁令我深思",
            "罗曼·罗兰曾经说过，只有把抱怨环境的心情，化为上进的力量，才是成功的保证。这不禁令我深思",
            "孔子曾经说过，知之者不如好之者，好之者不如乐之者。这不禁令我深思",
            "达·芬奇曾经说过，大胆和坚定的决心能够抵得上武器的精良。这不禁令我深思",
            "叔本华曾经说过，意志是一个强壮的盲人，倚靠在明眼的跛子肩上。这不禁令我深思",
            "黑格尔曾经说过，只有永远躺在泥坑里的人，才不会再掉进坑里。这不禁令我深思",
            "普列姆昌德曾经说过，希望的灯一旦熄灭，生活刹那间变成了一片黑暗。这不禁令我深思",
            "维龙曾经说过，要成功不需要什么特别的才能，只要把你能做的小事做得好就行了。这不禁令我深思",
            "郭沫若曾经说过，形成天才的决定因素应该是勤奋。这不禁令我深思",
            "洛克曾经说过，学到很多东西的诀窍，就是一下子不要学很多。这不禁令我深思",
            "西班牙曾经说过，自己的鞋子，自己知道紧在哪里。这不禁令我深思",
            "拉罗什福科曾经说过，我们唯一不会改正的缺点是软弱。这不禁令我深思",
            "亚伯拉罕·林肯曾经说过，我这个人走得很慢，但是我从不后退。这不禁令我深思",
            "美华纳曾经说过，勿问成功的秘诀为何，且尽全力做你应该做的事吧。这不禁令我深思",
            "俾斯麦曾经说过，对于不屈不挠的人来说，没有失败这回事。这不禁令我深思",
            "阿卜·日·法拉兹曾经说过，学问是异常珍贵的东西，从任何源泉吸收都不可耻。这不禁令我深思",
            "白哲特曾经说过，坚强的信念能赢得强者的心，并使他们变得更坚强。 这不禁令我深思",
            "查尔斯·史考伯曾经说过，一个人几乎可以在任何他怀有无限热忱的事情上成功。 这不禁令我深思",
            "贝多芬曾经说过，卓越的人一大优点是：在不利与艰难的遭遇里百折不饶。这不禁令我深思",
            "莎士比亚曾经说过，本来无望的事，大胆尝试，往往能成功。这不禁令我深思",
            "卡耐基曾经说过，我们若已接受最坏的，就再没有什么损失。这不禁令我深思",
            "德国曾经说过，只有在人群中间，才能认识自己。这不禁令我深思",
            "史美尔斯曾经说过，书籍把我们引入最美好的社会，使我们认识各个时代的伟大智者。这不禁令我深思",
            "冯学峰曾经说过，当一个人用工作去迎接光明，光明很快就会来照耀着他。这不禁令我深思",
            "吉格·金克拉曾经说过，如果你能做梦，你就能实现它。这不禁令我深思"
        ],
        after: [
            "这不禁令我深思。 ",
            "带着这句话，我们还要更加慎重的审视这个问题： ",
            "这启发了我， ",
            "我希望诸位也能好好地体会这句话。 ",
            "这句话语虽然很短，但令我浮想联翩。 "
        ],
        before: [
            "曾经说过",
            "在不经意间这样说过"
        ]
    },
    quality: {
        theme: 'nmsl',
        themeKey: '主题',
        argument: [
            '现在，解决主题的问题，是非常非常重要的。 所以， ',
            '本来看你奸诈狡猾的嘴脸，我就想一巴掌拍死你；但是走进看见你满脸油光，实在是下不去手！',
            '我们不得不面对一个足以干掉你亲吗的事实，那就是， ',
            '主题的发生，到底需要如何做到，不主题的发生，又会如何产生。 ',
            '而这些并不是完全重要，更加重要的问题是， ',
            '主题，到底应该如何实现。 ',
            '带着这些问题，恁野爹我来审视一下主题。 ',
            '所谓主题，关键是主题需要如何写。 ',
            '你野爹跟你讲，抓住了问题的关键，其他一切则会迎刃而解。 ',
            '问题的关键究竟为何？ ',
            '主题因何而发生？ ',
            '每个人都不得不面对这些问题。 在面对这种问题时， ',
            '一般来讲，我们都必须务必慎重的考虑考虑。 ',
            '要想清楚，主题，到底是一种怎么样的存在。 ',
            '了解清楚主题到底是一种怎么样的存在，是解决一切问题的关键。 ',
            '就我个人来说，主题对我的意义，不能不说非常重大。 ',
            '本人也是经过了深思熟虑，在每个日日夜夜思考这个问题。 ',
            '主题，发生了会如何，不发生又会如何。 ',
            '在这种困难的抉择下，本人思来想去，寝食难安。 ',
            '生活中，若主题出现了，我们就不得不考虑它出现了的事实。 ',
            '这种事实对本人来说意义重大，相信对这个世界也是有一定意义的。 ',
            '我们都知道，只要有意义，那么就必须慎重考虑。 ',
            '你个穷狗估计也就只能意淫着你婊子🐴疯狂卖逼来为你赚钱估计你瞎🐴一辈子赚得的都不如你野爹我胯下的内裤',
            '既然如此， ',
            '那么， ',
            '你野爹认为， ',
            '一般来说， ',
            '总结的来说， ',
            '既然如何， ',
            '经过上述讨论， ',
            '这样看来， ',
            '从这个角度来看， ',
            '可是，即使是这样，主题的出现仍然代表了一定的意义。 ',
            '对你野爹而言，主题不仅仅是一个重大的事件，还可能会改变你妈的人生。 '
        ],
        quotes: [
            '我没认识你之前，我真没发现原来我有以貌取人这毛病。这不禁令我深思',
            '这么不要脸，这么没心没肺，你的体重应该会很轻吧？这不禁令我深思',
            '你是个可爱的，迷人的辛勤的，白色的小小的总在为人民服务的新型杂交鱼种 长的很科幻，长的很抽象!这不禁令我深思',
            '你的牙如同天上的繁星，色泽鲜艳，相距甚远。这不禁令我深思',
            '这两片嘴唇，切切倒有一大碟子。这不禁令我深思',
            '听说你傍大款了，认二郎神当主人了。这不禁令我深思',
            '一脸兴冲冲的，跟喝了尿糖似的。这不禁令我深思',
            '你爸是化学部队的吧，研究病毒没研究明白，把你研究出来了。这不禁令我深思',
            '你的长相和智商都挺哈韩的。这不禁令我深思',
            '别以为你长的稀有样我们就应该物以稀为贵。这不禁令我深思',
            '你说你能干点啥，去打仗的话子弹飞弹会忍不住向你飞。这不禁令我深思',
            '你以为四海之内皆你妈啊，处处都得让着你。这不禁令我深思',
            '听你说话，一种智商上的优越感油然而生。 这不禁令我深思',
            '天下之大，大不过你缺的那块心眼。这不禁令我深思',
            '少在我面前拽的跟二五八万似的，摆好POSE，在装b。这不禁令我深思',
            '和你接触的时间越长，我就越喜欢狗，狗永远是狗，人有时候不是人。这不禁令我深思',
            '国家怎么就没拿你的脸皮研究防弹衣？这不禁令我深思',
            '请问我能向你要几张脸皮吗，我看你的脸皮里三层外三层的，少几张应该没关系吧。这不禁令我深思',

            '给你剑仙你不当，赐你剑神你不做，非死皮赖脸哭着喊着要做剑人！真是的，何必呢？！这不禁令我深思',
            '劳资眼光没那么差，就你这贱样还想让劳资上，劳资感觉恶心。',
            '日照香炉声紫烟，恁的老吗我强奸；十个男人一起来，你吗还要自已舔！',
            '作为人类最失败的典型，恁实在是太成功了！这不禁令我深思',
            '哎呀呀，哎呀呀，恁娘比里有蚂蚁爬，恁娘痒，恁娘痒，恁娘的yd往外长。',
            '你由外表到骨髓细胞还有基因都散发这一个字，"贱"！',
            '天生就是属黄瓜的，欠拍！后天属核桃的，欠捶！终生属破摩托的，欠踹！找个媳妇属螺丝钉的，欠拧！这不禁令我深思',
            '世上有三种人：一是良心被狗吃了的人，二是良心没被狗吃的人，三是良心连狗都不吃的人。这不禁令我深思'
        ],
        after: [
            'nmsl。 ',
            '带着这个理由，爷爷谅你也不敢。 ',
            '给老子爬。 ',
            '我希望恁mmp也能好好地体会这句话。 ',
            '这句话语虽然很短，但足以把恁吗屁眼捅烂。 ',
            '所以说恁个杂种cnm。 ',
            '后悔当初没把你射墙上。'
        ],
        before: [
            '恁傻逼东西',
            '劳资给恁讲',
            '曾经提到过',
            '说过一句儒雅随和的话'
        ]
    },
    english: {
        theme: 'should everyone vote for grade non-disclosure',
        themeKey: 'topic',
        argument: [
            'It is pressing to consider topic. ',
            'How should we achieve topic. ',
            'With some questions, let us reconsider topic. ',
            'Why does topic happen? ',
            'What are the consequences of topic happening? ',
            'It is important to understand topic before we proceed. ',
            'We all heard about topic. ',
            'It is important to solve topic. ',
            'The key to topic is that. ',
            'Personally, topic is very important to me. ',
            'As we all know, topic raises an important question to us. ',
            'Above all, we need to solve the most important issue first. ',
            'After seeing this evidence. ',
            'Alternatively, what is the other argument about topic? ',
            'Another possibility to topic is presented by the following example. ',
            'Another way of viewing the argument about topic is that, ',
            'As far as I know, everyone has to face this issue. ',
            'As in the following example, ',
            'Besides, the above-mentioned examples, it is equally important to consider another possibility. ',
            'But these are not the most urgent issue compared to topic. ',
            'For instance, topic let us think about another argument. ',
            'Let us think about topic from a different point of view. ',
            'In that case, we need to consider topic seriously. ',
            'It is important to note that another possibility. ',
            'The evidence presented about topic has shown us a strong relationship. ',
            'Under this inevitable circumstance situation. ',
            'After thoroughly research about topic, I found an interesting fact. ',
            'This was another part we need to consider. ',
            'This fact is important to me. And I believe it is also important to the world. ',
            'As we all know, if it is important, we should seriously consider it. ',
            'It is a hard choice to make. ',
            'The more important question to consider is the following. ',
            'With these questions, let us look at it in-depth. ',
            'What is the key to this problem? '
        ],
        quotes: [
            'Benjamin Franklin concluded that, I didn’t fail the test. I just found 100 ways to do it wrong. ',
            'Bob Dylan argued that, What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do. ',
            'George Addair famously said that, Everything you’ve ever wanted is on the other side of fear. ',
            'John Lennon concluded that, Life is what happens to you while you’re busy making other plans. ',
            'Norman Vincent Peale argued that, Change your thoughts and you change your world. ',
            'Pablo Picasso famously said that, Every child is an artist. The problem is how to remain an artist once he grows up. ',
            'Anne Frank once said, How wonderful it is that nobody need wait a single moment before starting to improve the world. ',
            'Buddha once said, The mind is everything. What you think you become. ',
            'Jim Rohn once said, Either you run the day, or the day runs you. ',
            'Socrates once said, An unexamined life is not worth living. ',
            'Theodore Roosevelt once said, Believe you can and you’re halfway there. ',
            'Albert Einstein once said that, Strive not to be a success, but rather to be of value. ',
            'Alice Walker once said that, The most common way people give up their power is by thinking they don’t have any. ',
            'Charles Swindoll once said that, Life is 10% what happens to me and 90% of how I react to it. ',
            'Earl Nightingale once said that, We become what we think about. ',
            'Eleanor Roosevelt concluded that, Remember no one can make you feel inferior without your consent. ',
            'Jesse Owens once said that, The battles that count aren’t the ones for gold medals. The struggles within yourself–the invisible battles inside all of us–that’s where it’s at. ',
            'Mae Jemison once said that, It’s your place in the world; it’s your life. Go on and do all you can with it, and make it the life you want to live. ',
            'Mark Twain once said that, The two most important days in your life are the day you are born and the day you find out why. ',
            'Ralph Waldo Emerson once said that, The only person you are destined to become is the person you decide to be. ',
            'Sheryl Sandberg once said that, If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on. ',
            'Vince Lombardi once said that, Winning isn’t everything, but wanting to win is. ',
            'W. Clement Stone once said that, Definiteness of purpose is the starting point of all achievement. ',
            'Anais Nin said, Life shrinks or expands in proportion to one’s courage. ',
            'Babe Ruth said, Every strike brings me closer to the next home run. ',
            'Benjamin Franklin mentioned that, Either write something worth reading or do something worth writing. ',
            'George Eliot said, It is never too late to be what you might have been. ',
            'Henry Ford said, Whether you think you can or you think you can’t, you’re right. ',
            'Joshua J. Marine said, Challenges are what make life interesting and overcoming them is what makes life meaningful. ',
            'Kevin Kruse concluded that, We must balance conspicuous consumption with conscious capitalism. ',
            'Maya Angelou said, Life is not measured by the number of breaths we take, but by the moments that take our breath away. ',
            'Roger Staubach said, There are no traffic jams along the extra mile. ',
            'Sir Claus Moser said, Education costs money. But then so does ignorance. ',
            'Tony Robbins said, If you do what you’ve always done, you’ll get what you’ve always gotten. ',
            'Zig Ziglar said, If you can dream it, you can achieve it. ',
            'Zig Ziglar said, People often say that motivation doesn’t last. Well, neither does bathing. That’s why we recommend it daily. ',
            'Bill Cosby said in a speech, In order to succeed, your desire for success should be greater than your fear of failure. ',
            'Booker T. Washington mentioned that, Few things can help an individual more than to place responsibility on him, and to let him know that you trust him. ',
            'Dalai Lama said in a speech, Happiness is not something readymade. It comes from your own actions. ',
            'Jamie Paolinetti mentioned that, Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless. ',
            'Japanese Proverb said in a speech, Fall seven times and stand up eight. ',
            'Lao Tzu said in a speech, When I let go of what I am, I become what I might be. ',
            'Les Brown argued that, Too many of us are not living our dreams because we are living our fears. ',
            'Steve Jobs said in a speech, Your time is limited, so don’t waste it living someone else’s life. ',
            'Wayne Gretzky argued that, You miss 100% of the shots you don’t take. ',
            'Amelia Earhart said in his book, The most difficult thing is the decision to act, the rest is merely tenacity. ',
            'Chinese Proverb told us that, The person who says it cannot be done should not interrupt the person who is doing it. ',
            'Farrah Gray said in his book, Build your own dreams, or someone else will hire you to build theirs. ',
            'Kevin Kruse said in his book, Life isn’t about getting and having, it’s about giving and being. ',
            'Latin Proverb argued that, If the wind will not serve, take to the oars. ',
            'Leonardo da Vinci argued that, I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do. ',
            'Steve Jobs said in his book, The only way to do great work is to love what you do. ',
            'Abraham Lincoln said that, It’s not the years in your life that count. It’s the life in your years. ',
            'Albert Einstein said that, A person who never made a mistake never tried anything new. ',
            'Ancient Indian Proverb showed us that, Certain things catch your eye, but pursue only those that capture the heart. ',
            'Arthur Ashe said that, Start where you are. Use what you have. Do what you can. ',
            'Ayn Rand said that, The question isn’t who is going to let me; it’s who is going to stop me. ',
            'Christopher Columbus said that, You can never cross the ocean until you have the courage to lose sight of the shore. ',
            'Florence Nightingale argued that, I attribute my success to this: I never gave or took any excuse. ',
            'Frank Sinatra said that, The best revenge is massive success. ',
            'Jesus said that, Ask and it will be given to you; search, and you will find; knock and the door will be opened for you. ',
            'Martin Luther King Jr. argued that, Our lives begin to end the day we become silent about things that matter. ',
            'Maya Angelou said that, You can’t use up creativity. The more you use, the more you have. ',
            'Norman Vaughan said that, Dream big and dare to fail. ',
            'Plato said that, We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light. ',
            'Stephen Covey showed us that, I am not a product of my circumstances. I am a product of my decisions. ',
            'Woody Allen said that, Eighty percent of success is showing up. ',
            'Beverly Sills told us that, You may be disappointed if you fail, but you are doomed if you don’t try. ',
            'Booker T. Washington told us that, If you want to lift yourself up, lift up someone else. ',
            'Chinese Proverb told us that, The best time to plant a tree was 20 years ago. The second best time is now. ',
            'Confucius mentioned that, Everything has beauty, but not everyone can see. ',
            'Confucius told us that, It does not matter how slowly you go as long as you do not stop. ',
            'Dalai Lama told us that, Remember that not getting what you want is sometimes a wonderful stroke of luck. ',
            'Henry David Thoreau argued that, Go confidently in the direction of your dreams. Live the life you have imagined. ',
            'Michael Jordan told us that, I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed. ',
            'Napoleon Hill showed us that, Whatever the mind of man can conceive and believe, it can achieve. ',
            'Oprah Winfrey told us that, You become what you believe. ',
            'Rosa Parks told us that, I have learned over the years that when one’s mind is made up, this diminishes fear. '
        ],
        after: [
            "This is a short but powerful argument. ",
            "This inspired me. ",
            "With the understanding developed from this, we need to look at this problem in more depth. ",
            "I totally agree with this. ",
            "This leads to my other argument. ",
            "This examplifies my following argument. ",
            'We have to consider its consequence. ',
            'This brings a new way of thinking about topic. ',
            'This enlighten me. '
        ],
        before: [
            "once said, I AM IN BEFORE ARGUMENT"
        ]
    }
};