/// 配送列表
export const mockData_peiSongList = {
	"success": true,
	"resCode": "00100000",
	"obj": {
		"hidePartMsg": "233部分订单配送已约满，请重新选择商品",
		"hideMsg": "233抱歉，配送服务已约满",
		"list": [{
			"storeCode": "200021",
			"storeType": "2040",
			"initialTime": null,
			"interval": null,
			"startTime": null,
			"endTime": null,
			"success": true,
			"dsd": false,
			"business": false,
			"msg": null,
			"peiSongTip": "233请尽快付款，以确保我们在指定时间配送（另：不可抗力因素可能导致延误敬请谅解）",
			"peiSongDesc": null,
			"nowTime": null,
			"week": null,
			"server": "48小时内发货",
			"shopBeginTime": "2022-04-18 08:00:00",
			"shopEndTime": "2022-04-18 10:00:00",
			"dsdStartTime": null,
			"dsdEndTime": null,
			"defaultSendDate": null,
			"peiSongList": [],
			"yuShouInfo": null,
			"orderLimit": null,
			"hide": "N",
			"ysSendDate": null,
			"ysFlag": 0,
			"limitFlag": 0,
			"tdFlag": 1,
			"toDay": "2022-04-18",
			"limitTimeList": null
		}, {
			"storeCode": "007780",
			"storeType": "2020",
			"initialTime": null,
			"interval": null,
			"startTime": null,
			"endTime": null,
			"success": true,
			"dsd": true,
			"business": true,
			"msg": null,
			"peiSongTip": "233请尽快付款，以确保我们在指定时间配送（另：不可抗力因素可能导致延误敬请谅解）",
			"peiSongDesc": null,
			"nowTime": null,
			"week": null,
			"server": "请选择时间",
			"shopBeginTime": "2022-04-18 08:30:00",
			"shopEndTime": "2022-04-18 23:00:00",
			"dsdStartTime": null,
			"dsdEndTime": null,
			"defaultSendDate": 1650211200000,
			"peiSongList": [{
				"desc": "今日",
				"date": "2022-04-18",
				"week": "周一",
				"hide": "N",
				"timeList": [{
					"server": null,
					"startTime": "09:00",
					"endTime": "21:00",
					"hide": "N",
					"limit": 119988,
					"order": 2
				}]
			}, {
				"desc": "明天",
				"date": "2022-04-19",
				"week": "周二",
				"hide": "N",
				"timeList": [{
					"server": null,
					"startTime": "09:00",
					"endTime": "21:00",
					"hide": "N",
					"limit": 119988,
					"order": 0
				}]
			}],
			"yuShouInfo": null,
			"orderLimit": null,
			"hide": "N",
			"ysSendDate": null,
			"ysFlag": 0,
			"limitFlag": 1,
			"tdFlag": 0,
			"toDay": "2022-04-18",
			"limitTimeList": null
		}]
	}
}
