export const mockData = {
    "success": true,
    "resCode": "00100000",
    "obj": {
        "HDGL202201250000011277": [
            {
                "id": "007780_2020007780ENT23234@@1@@131053",
                "basePrice": "101.10",
                "categoryId": null,
                "comSid": "2000",
                "goodsId": "131053",
                "goodsImage": "https://img.st.iblimg.com/goods-14/2000/2016/11/SP_2000_20000647837001_01_1006.jpg",
                "goodsType": null,
                "inStock": null,
                "comGoodCode": "0647837001",
                "salePrice": "101.10",
                "plusPrice": null,
                "discountPrice": null,
                "endTime": null,
                "priceType": "0",
                "limitBuyPersonSum": null,
                "personLimit": null,
                "saleStockStatus": "1",
                "limitPopSum": null,
                "productName": "徐福记 糙米卷 燕麦牛奶夹心 135g/袋",
                "pointTitle": null,
                "saleStockSum": 11,
                "marketOn": "1",
                "type": null,
                "brandCnName": "lptest",
                "popinfosList": [],
                "previewList": [],
                "xgList": [],
                "from": null,
                "tdType": "0",
                "tdLable": null,
                "mainTitle": null,
                "pageCat": {
                    "15662": 1000,
                    "15675": 1,
                    "15664": 1000
                }
            }, {
                "id": "007780_2020007780ENT23234@@1@@81961",
                "basePrice": "7.80",
                "categoryId": null,
                "comSid": "2000",
                "goodsId": "81961",
                "goodsImage": "https://img.st.iblimg.com/goods-14/2000/2016/11/SP_2000_20000618424001_01_1006.jpg",
                "goodsType": null,
                "inStock": null,
                "comGoodCode": "0618424001",
                "salePrice": "7.80",
                "plusPrice": null,
                "discountPrice": null,
                "endTime": null,
                "priceType": "0",
                "limitBuyPersonSum": null,
                "personLimit": null,
                "saleStockStatus": "1",
                "limitPopSum": null,
                "productName": "Reeses花生牛奶巧克力杯 34g",
                "pointTitle": null,
                "saleStockSum": 8,
                "marketOn": "1",
                "type": null,
                "brandCnName": "lptest",
                "popinfosList": [],
                "previewList": [],
                "xgList": [],
                "from": null,
                "tdType": "0",
                "tdLable": null,
                "mainTitle": null,
                "pageCat": {
                    "15662": 1000,
                    "15666": 1000
                }
            }
        ],
        "HDGL202203140000011297": [
            {
                "id": "007780_2020007780ENT23234@@1@@81961",
                "basePrice": "7.80",
                "categoryId": null,
                "comSid": "2000",
                "goodsId": "81961",
                "goodsImage": "https://img.st.iblimg.com/goods-14/2000/2016/11/SP_2000_20000618424001_01_1006.jpg",
                "goodsType": null,
                "inStock": null,
                "comGoodCode": "0618424001",
                "salePrice": "7.80",
                "plusPrice": null,
                "discountPrice": null,
                "endTime": null,
                "priceType": "0",
                "limitBuyPersonSum": null,
                "personLimit": null,
                "saleStockStatus": "1",
                "limitPopSum": null,
                "productName": "Reeses花生牛奶巧克力杯 34g",
                "pointTitle": null,
                "saleStockSum": 8,
                "marketOn": "1",
                "type": null,
                "brandCnName": "lptest",
                "popinfosList": [],
                "previewList": [],
                "xgList": [],
                "from": null,
                "tdType": "0",
                "tdLable": null,
                "mainTitle": "促销语测试4",
                "pageCat": {
                    "15662": 1000,
                    "15666": 1000
                }
            },
            {
                "id": "007780_2020007780ENT23234@@1@@1007452",
                "basePrice": "12.90",
                "categoryId": null,
                "comSid": "2000",
                "goodsId": "1007452",
                "goodsImage": "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1107043824_200x200.jpg",
                "goodsType": null,
                "inStock": null,
                "comGoodCode": "0846101001",
                "salePrice": "12.90",
                "plusPrice": null,
                "discountPrice": "11.61",
                "endTime": null,
                "priceType": "0",
                "limitBuyPersonSum": null,
                "personLimit": null,
                "saleStockStatus": "1",
                "limitPopSum": null,
                "productName": "双汇食亨鱼肉王特级鱼肉肠 50g*5",
                "pointTitle": null,
                "saleStockSum": 11,
                "marketOn": "1",
                "type": null,
                "brandCnName": "双汇",
                "popinfosList": [
                    {
                        "rules": [
                            {
                                "desc": "每第1件9.0折",
                                "id": "8621"
                            },
                            {
                                "desc": "每第2件8.0折",
                                "id": "8622"
                            }
                        ],
                        "activityType": "1",
                        "memo": "到家的条件折扣1013",
                        "labelDesc": "到家的条件折扣",
                        "goodsDetSid": "1007452",
                        "popDes": "折扣",
                        "ruleid": "50979",
                        "ruletype": "2",
                        "ruleName": "折扣",
                        "activityDesc": "到家条件折扣_165026034",
                        "activityId": "52873",
                        "shopid": "007780",
                        "buyMember": "0",
                        "sLabel": "到家的条件折扣",
                        "mLabel": "到家的条件折扣1013"
                    }
                ],
                "previewList": [],
                "xgList": [],
                "from": null,
                "tdType": "0",
                "tdLable": null,
                "mainTitle": "促销语测试1",
                "pageCat": null
            }
        ],
        "HDGL20201211000009397": [
            {
                "id": "007780_2020007780ENT23234@@1@@162610",
                "basePrice": "59.00",
                "categoryId": null,
                "comSid": "2000",
                "goodsId": "162610",
                "goodsImage": "http://img.st.iblimg.com/goods-14/2000/2016/11/SP_2000_20000808753001_01_1006.jpg",
                "goodsType": null,
                "inStock": null,
                "comGoodCode": "0808753001",
                "salePrice": "49.00",
                "plusPrice": null,
                "discountPrice": "49.00",
                "endTime": null,
                "priceType": "0",
                "limitBuyPersonSum": null,
                "personLimit": null,
                "saleStockStatus": "1",
                "limitPopSum": "1",
                "productName": "养元六个核桃香纯型饮料",
                "pointTitle": null,
                "saleStockSum": 11,
                "marketOn": "1",
                "type": null,
                "brandCnName": null,
                "popinfosList": [{
                    "rules": [{
                        "desc": "联华新人价回归",
                        "id": "3508"
                    }],
                    "activityType": "1",
                    "activityTag": "新人活动标签",
                    "memo": "新人活动标签",
                    "labelDesc": "新人活动标签",
                    "goodsDetSid": "162610",
                    "popDes": "买立减",
                    "ruleid": "50481",
                    "ruletype": "12",
                    "ruleName": "专享",
                    "activityId": "0",
                    "shopid": "007780",
                    "discountAmount": "49.0",
                    "memberLimit": "1",
                    "orderLimit": "1",
                    "sLabel": "新人活动标签",
                    "mLabel": "新人价标签说明",
                    "lLabel": "20000856441001"
                }],
                "previewList": [],
                "xgList": [],
                "from": null,
                "tdType": "0",
                "tdLable": null,
                "mainTitle": "养元六个核桃香纯型饮料",
                "pageCat": {
                    "15654": 1000
                }
            }, {
                "id": "007780_2020007780ENT23234@@1@@162638",
                "basePrice": "30.60",
                "categoryId": null,
                "comSid": "2000",
                "goodsId": "162638",
                "goodsImage": "https://img.st.iblimg.com/goods-14/2000/2016/11/SP_2000_20000772629001_01_1006.jpg",
                "goodsType": null,
                "inStock": null,
                "comGoodCode": "0772629001",
                "salePrice": "28.40",
                "plusPrice": null,
                "discountPrice": null,
                "endTime": null,
                "priceType": "0",
                "limitBuyPersonSum": null,
                "personLimit": null,
                "saleStockStatus": "1",
                "limitPopSum": null,
                "productName": "好丽友 呀！土豆薯条 蜂蜜黄油味 500g/袋",
                "pointTitle": null,
                "saleStockSum": 11,
                "marketOn": "1",
                "type": null,
                "brandCnName": "全球购",
                "popinfosList": [],
                "previewList": [],
                "xgList": [],
                "from": null,
                "tdType": "0",
                "tdLable": null,
                "mainTitle": "好丽友",
                "pageCat": {
                    "15651": 1,
                    "15662": 1000,
                    "15655": 4,
                    "15654": 1000,
                    "15664": 1000,
                    "15653": 1000
                }
            }
        ]
    }
}
