export const mockData = {
    "success": true,
    "resCode": "00100000",
    "obj": {
        "HDGL202201250000011277": [
            {
                "id": "007780_2020007780ENT23234@@1@@81961",
                "basePrice": "7.80",
                "categoryId": null,
                "comSid": "2000",
                "goodsId": "81961",
                "goodsImage": "https://img.st.iblimg.com/goods-14/2000/2016/11/SP_2000_20000618424001_01_1006.jpg",
                "goodsType": null,
                "inStock": null,
                "comGoodCode": "0618424001",
                "salePrice": "7.80",
                "plusPrice": null,
                "discountPrice": null,
                "endTime": null,
                "priceType": "0",
                "limitBuyPersonSum": null,
                "personLimit": null,
                "saleStockStatus": "1",
                "limitPopSum": null,
                "productName": "Reeses花生牛奶巧克力杯 34g",
                "pointTitle": null,
                "saleStockSum": 8,
                "marketOn": "1",
                "type": null,
                "brandCnName": "lptest",
                "popinfosList": [],
                "previewList": [],
                "xgList": [],
                "from": null,
                "tdType": "0",
                "tdLable": null,
                "pageCat": {
                    "15662": 1000,
                    "15666": 1000
                }
            },
            {
                "id": "007780_2020007780ENT23234@@1@@131451",
                "basePrice": "39.80",
                "categoryId": null,
                "comSid": "2000",
                "goodsId": "131451",
                "goodsImage": "https://img.st.iblimg.com/goods-14/2000/2016/11/SP_2000_20000183815001_01_1006.jpg",
                "goodsType": null,
                "inStock": null,
                "comGoodCode": "0183815001",
                "salePrice": "39.80",
                "plusPrice": null,
                "discountPrice": "35.82",
                "endTime": null,
                "priceType": "0",
                "limitBuyPersonSum": null,
                "personLimit": null,
                "saleStockStatus": "1",
                "limitPopSum": null,
                "productName": "趣多多 欢享礼盒装 475g/盒",
                "pointTitle": null,
                "saleStockSum": 11,
                "marketOn": "1",
                "type": null,
                "brandCnName": "卡夫",
                "popinfosList": [
                    {
                        "rules": [
                            {
                                "desc": "每第1件9.0折",
                                "id": "8621"
                            },
                            {
                                "desc": "每第2件8.0折",
                                "id": "8622"
                            }
                        ],
                        "activityType": "1",
                        "memo": "到家的条件折扣1013",
                        "labelDesc": "到家的条件折扣",
                        "goodsDetSid": "131451",
                        "popDes": "折扣",
                        "ruleid": "50979",
                        "ruletype": "2",
                        "ruleName": "折扣",
                        "activityDesc": "到家条件折扣_165026034",
                        "activityId": "52873",
                        "shopid": "007780",
                        "buyMember": "0",
                        "sLabel": "到家的条件折扣",
                        "mLabel": "到家的条件折扣1013"
                    }
                ],
                "previewList": [],
                "xgList": [],
                "from": null,
                "tdType": "0",
                "tdLable": null,
                "pageCat": {
                    "15662": 1000,
                    "15664": 1000
                }
            }
        ],
        "HDGL20201211000009397": [
            {
                "id": "007780_2020007780ENT23234@@1@@131053",
                "basePrice": "101.10",
                "categoryId": null,
                "comSid": "2000",
                "goodsId": "131053",
                "goodsImage": "https://img.st.iblimg.com/goods-14/2000/2016/11/SP_2000_20000647837001_01_1006.jpg",
                "goodsType": null,
                "inStock": null,
                "comGoodCode": "0647837001",
                "salePrice": "101.10",
                "plusPrice": null,
                "discountPrice": null,
                "endTime": null,
                "priceType": "0",
                "limitBuyPersonSum": null,
                "personLimit": null,
                "saleStockStatus": "1",
                "limitPopSum": null,
                "productName": "徐福记 糙米卷 燕麦牛奶夹心 135g/袋",
                "pointTitle": null,
                "saleStockSum": 11,
                "marketOn": "1",
                "type": null,
                "brandCnName": "lptest",
                "popinfosList": [],
                "previewList": [],
                "xgList": [],
                "from": null,
                "tdType": "0",
                "tdLable": null,
                "pageCat": {
                    "15662": 1000,
                    "15664": 1000,
                    "15675": 1
                }
            },
            {
                "id": "007780_2020007780ENT23234@@1@@69548",
                "basePrice": "29.80",
                "categoryId": null,
                "comSid": "2000",
                "goodsId": "69548",
                "goodsImage": "https://Img.st.iblimg.com/fast2home-1/offlinegoods/goods/SP_1295855952_200x200.jpg",
                "goodsType": null,
                "inStock": null,
                "comGoodCode": "0161712001",
                "salePrice": "100.00",
                "plusPrice": null,
                "discountPrice": null,
                "endTime": null,
                "priceType": "0",
                "limitBuyPersonSum": null,
                "personLimit": null,
                "saleStockStatus": "1",
                "limitPopSum": null,
                "productName": "奥地利进口 可达怡 白胡椒粒 52g",
                "pointTitle": null,
                "saleStockSum": 11,
                "marketOn": "1",
                "type": null,
                "brandCnName": "可达怡",
                "popinfosList": [],
                "previewList": [],
                "xgList": [],
                "from": null,
                "tdType": "0",
                "tdLable": null,
                "pageCat": {
                    "15654": 1000,
                    "15662": 1000,
                    "15667": 1000
                }
            }
        ],
        "HDGL202203140000011297": [
            {
                "id": "007780_2020007780ENT23234@@1@@131053",
                "basePrice": "101.10",
                "categoryId": null,
                "comSid": "2000",
                "goodsId": "131053",
                "goodsImage": "https://img.st.iblimg.com/goods-14/2000/2016/11/SP_2000_20000647837001_01_1006.jpg",
                "goodsType": null,
                "inStock": null,
                "comGoodCode": "0647837001",
                "salePrice": "101.10",
                "plusPrice": null,
                "discountPrice": null,
                "endTime": null,
                "priceType": "0",
                "limitBuyPersonSum": null,
                "personLimit": null,
                "saleStockStatus": "1",
                "limitPopSum": null,
                "productName": "徐福记 糙米卷 燕麦牛奶夹心 135g/袋",
                "pointTitle": null,
                "saleStockSum": 11,
                "marketOn": "1",
                "type": null,
                "brandCnName": "lptest",
                "popinfosList": [],
                "previewList": [],
                "xgList": [],
                "from": null,
                "tdType": "0",
                "tdLable": null,
                "pageCat": {
                    "15662": 1000,
                    "15664": 1000,
                    "15675": 1
                }
            },
            {
                "id": "007780_2020007780ENT23234@@1@@131451",
                "basePrice": "39.80",
                "categoryId": null,
                "comSid": "2000",
                "goodsId": "131451",
                "goodsImage": "https://img.st.iblimg.com/goods-14/2000/2016/11/SP_2000_20000183815001_01_1006.jpg",
                "goodsType": null,
                "inStock": null,
                "comGoodCode": "0183815001",
                "salePrice": "39.80",
                "plusPrice": null,
                "discountPrice": "35.82",
                "endTime": null,
                "priceType": "0",
                "limitBuyPersonSum": null,
                "personLimit": null,
                "saleStockStatus": "1",
                "limitPopSum": null,
                "productName": "趣多多 欢享礼盒装 475g/盒",
                "pointTitle": null,
                "saleStockSum": 11,
                "marketOn": "1",
                "type": null,
                "brandCnName": "卡夫",
                "popinfosList": [
                    {
                        "rules": [
                            {
                                "desc": "每第1件9.0折",
                                "id": "8621"
                            },
                            {
                                "desc": "每第2件8.0折",
                                "id": "8622"
                            }
                        ],
                        "activityType": "1",
                        "memo": "到家的条件折扣1013",
                        "labelDesc": "到家的条件折扣",
                        "goodsDetSid": "131451",
                        "popDes": "折扣",
                        "ruleid": "50979",
                        "ruletype": "2",
                        "ruleName": "折扣",
                        "activityDesc": "到家条件折扣_165026034",
                        "activityId": "52873",
                        "shopid": "007780",
                        "buyMember": "0",
                        "sLabel": "到家的条件折扣",
                        "mLabel": "到家的条件折扣1013"
                    }
                ],
                "previewList": [],
                "xgList": [],
                "from": null,
                "tdType": "0",
                "tdLable": null,
                "pageCat": {
                    "15662": 1000,
                    "15664": 1000
                }
            }
        ]
    }
}
