export const mockData = {
  "success": false,
  "msg": "医疗器械诺斯清 生理性海水鼻腔护理喷雾器 50ml(儿童),已下架!",
  "resCode": "00100051",
  "obj": {
      "currentGoodsNumber": 0,
      "freightLessWeight": 0.00,
      "freightLessPrice": 0.00,
      "totalPrice": 0.00,
      "showTotalPrice": 0.00,
      "totalGoodsNumber": 0,
      "newGoodsNumber": 0,
      "allGoodsNumber": 0,
      "failGoodsList": [
          {
              "shoppingCartType": "5",
              "discountRate": 0.00,
              "isNewAdd": "0",
              "type": "25",
              "oldSalePrice": 0.00,
              "freightMoney": 0.00,
              "goodsOriginalNumber": 1,
              "medicareFlag": "0",
              "goodsGiftNumber": 0,
              "price": 0.00,
              "ggName": "生理性海水鼻腔护理喷雾器",
              "goodsPicUrl": "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1425248628_200x200.jpg",
              "medicineType": "4",
              "goodsName": "医疗器械诺斯清 生理性海水鼻腔护理喷雾器 50ml(儿童)",
              "ifOnlyPickup": "0",
              "productSid": "2267554",
              "showSalePrice": 88.33,
              "checkedOriginal": false,
              "isPopEffective": "1",
              "processingTime": 0,
              "featureList": [
                  {
                      "features": [
                          {
                              "featureName": "5646",
                              "propSid": 2149,
                              "propName": "属性",
                              "featureId": "2383"
                          }
                      ],
                      "featureSign": "3284581-2383",
                      "goodsId": "3284581",
                      "num": 1,
                      "updateTime": "2024-12-26 17:34:12 0636",
                      "checkFlag": true
                  }
              ],
              "sType": "1",
              "stor": 0,
              "limitBuySum": -1,
              "kdjShopId": "001100",
              "currPrice": 0.00,
              "if7Refund": "0",
              "medicareCateCode": "6938449800131",
              "promotionPrice": 88.33,
              "totalPrice": 0.00,
              "goodsId": "3284581",
              "capacity": 0.00,
              "referencePrice": 0.00,
              "checkLevel": "1",
              "isMergeTemplete": "0",
              "goodsLineNbr": "5080e984-5abb-4852-be80-1f7c6a9ca61e",
              "userPrice": 0,
              "handPrice": 0.00,
              "isTakenBySelf": "1",
              "tariff": 0,
              "counpDisCount": 0.00,
              "showGoodsDiscount": 0.00,
              "mpReduceMoney": 0.00,
              "salePrice": 88.33,
              "priceType": "0",
              "virtualSellFlag": "0",
              "hasActivity": "1",
              "updateTime": "2010-06-07 10:07:14 0710",
              "medicareOnlineFlag": "0",
              "isCLFlag": false,
              "depositEndTime": "2099-12-31 23:59:59",
              "promBillNo": 0,
              "goodsPopDiscount2": 0.00,
              "did": "",
              "yunType": "2",
              "basketLimitGoodsNum": -1,
              "groupId": "4018DYSD0",
              "deliveryCharge": 0.00,
              "promotionMark": "0",
              "proSellBit": 6,
              "features": [
                  {
                      "featureName": "5646",
                      "propSid": 2149,
                      "propName": "属性",
                      "featureId": "2383"
                  }
              ],
              "futuresType": "0",
              "totalCapacity": 0.00,
              "goodsNumber": 1,
              "saleSum": 0,
              "tariffRate": "0",
              "stockStatus": "0",
              "checked": false,
              "depositStartTime": "2020-09-21 16:39:59",
              "sdName": "生理性海水鼻腔护理喷雾器",
              "depositDeductMoney": 0.00,
              "brandName": "诺斯清",
              "kdjSourceShopId": "001100",
              "kdjmerchantID": "60200011001",
              "personPriceList": [],
              "depositMoney": 0.00,
              "weight": 1,
              "tax": "0.13",
              "pricechange": true,
              "globalType": "0",
              "isDelevery": "1",
              "barCode": "6938449800131",
              "goodsType": "1",
              "dggFlag": "1",
              "bl_ad": "2024011_-_49209_-_1",
              "normalSalePrice": 88.33,
              "djSendType": "3",
              "comSid": "6000",
              "goodsUrl": "https://product.st.bl.com/3284581.html",
              "finalPaymentMoney": 0.00,
              "xgOriginalPrice": 0.00,
              "goodsNumberForLimit": 0,
              "brandSid": "206128",
              "storeIndustrySid": "6020",
              "isWeight": "0",
              "limitBuyPersonSum": -1,
              "addGoodsPrice": 0.00,
              "promotionExpandMoney": 0.00,
              "supplierId": "-1",
              "stanName": "50ml(儿童)",
              "kdjSourceMerchantId": "60200011001",
              "goodsDiscount": 0.00,
              "freeFreight": false,
              "categoryBackIds": "214996",
              "preBuyFlag": "0",
              "isGift": "0",
              "kdjSourceStoreIndustrySid": "6020",
              "reduceTag": "0",
              "singleDiscountPrice": 0.00,
              "categoryid": "80395",
              "activeCode": "",
              "backChange": 0,
              "ifCanBuy": "1",
              "editable": "1",
              "measureUnit": "盒",
              "comsGoodsCode": "6999002",
              "medicareCountryCode": "6938449800131",
              "mdmGoodsSid": "60006999002",
              "totalWeight": 1.000,
              "logisticsType": "01"
          }
      ],
      "timestamp": 0,
      "totalGoodsAmount": 0
  }
}
