export default (req, res) => {
  const { type } = req.body
  let data = {}
  if (type === 'post') {
    data = post
  } else if (type === 'following') {
    data = following
  } else {
    data = post
  }
  setTimeout(() => {
    res.status(200).json({
      code: 10000,
      msg: '',
      tips: '',
      data,
    })
  }, 1000)
}
const post = {
  recommend_groups: [
    {
      guid: '31d8ad8a-e07f-4af2-8b3c-e5c403cf1815',
      title: 'queen size',
      logo: '',
      group_description: '',
      created_at: 1606095785,
      group_members: 9,
    },
  ],
  list: [
    {
      member_id: 71190,
      member_uuid: '63893f65-ce60-4cbc-853c-6038ceef34b4',
      role: 'normal',
      business_id: '',
      member_name: {
        nickname: 'tzxcy01',
        displayname: 'tzxcy01',
        icon: [],
      },
      avatar: {
        path: 'https://duly5zwcucles.cloudfront.net/__##__avatar/grey_head.png',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      post_id: 100582,
      title: '',
      content: '',
      images: [
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1609909972847_16e04ccbe1273d5b787773bea0afee1c_android.jpg',
          ratio: 1,
          tag: 1,
          imageTags: [],
        },
      ],
      video: '',
      video_cover: '',
      video_cover_ratio: 1,
      comments_num: 0,
      praise_num: 0,
      original: 0,
      publish_addr: '',
      created_at: 1609906389,
      thumb_size: {
        s: 'small/',
        m: 'middle/',
        l: 'large/',
      },
      type: 2,
      share_url:
        'https://mtest.vaffle.com/post/detail/?t=3&ctype=detail&l=en&ticket=%2F6TxjY7K0bCMspZXBnH6Qg%3D%3D',
      is_praise: 0,
      is_follow: 0,
      attention: [],
      category: 'posts',
      is_collect: 0,
      is_deals: 0,
      from: 'tzxcy01',
      offset: 0,
      recommend_state: 0,
      ticket: '50mS2iyUk4QhSow7wJU4mo1udqOyeLk1QFEkPWy3Ag0%3D',
      trans_white_state: 0,
      trans_btn: 0,
      guid: '',
      group_title: '',
      group_owner_uuid: '',
      publish_group_role: 0,
      group_topic_id: 0,
      gifCoverPath: '',
      source_content: '',
      source_title: '',
      shop_id: 0,
      shop_name: '',
      removeGroupMember: 0,
      banGroupMember: 0,
      comment_status_is: 0,
      comment_status: 1,
      is_arbitrate: 1,
      force_interest: 0,
      bigData: 0,
    },
    {
      member_id: 959,
      member_uuid: 'a5f10151-5685-4432-8c35-7198bc6511c9',
      role: 'normal',
      business_id: '',
      member_name: {
        nickname: 'lisa',
        displayname: 'heyua11',
        icon: [
          'https://duly5zwcucles.cloudfront.net/icon/1588142043_5ea91fdb95e0c.png',
        ],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/head_male1.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 1,
        pendantPath:
          'http://duly5zwcucles.cloudfront.net/posts/goods/1609838191_5ff42e6f62dd6.png',
      },
      post_id: 100579,
      title: '',
      content:
        'Interface in 2021-01-05 17:57:36 test release post is used to like and cancel likes',
      images: [
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
      ],
      video: '',
      video_cover: '',
      video_cover_ratio: 1,
      comments_num: 0,
      praise_num: 4,
      original: 0,
      publish_addr: '',
      created_at: 1609840656,
      thumb_size: {
        s: 'small/',
        m: 'middle/',
        l: 'large/',
      },
      type: 2,
      share_url:
        'https://mtest.vaffle.com/post/detail/?t=3&ctype=detail&l=en&ticket=D7uQPcvHaa7zvdFVoz7LKQ%3D%3D',
      is_praise: 0,
      is_follow: 0,
      attention: [],
      category: 'posts',
      is_collect: 0,
      is_deals: 0,
      from: 'lisa',
      offset: 0,
      recommend_state: 0,
      ticket: 'gQ%2Fj%2B%2BV71B0QqQ9l3CU9eX7s1pOcWaHNpQ9NVU7lGus%3D',
      trans_white_state: 0,
      trans_btn: 1,
      guid: '',
      group_title: '',
      group_owner_uuid: '',
      publish_group_role: 0,
      group_topic_id: 0,
      gifCoverPath: '',
      source_content:
        '\u63a5\u53e3\u57282021-01-05 17:57:36\u6d4b\u8bd5\u53d1\u5e03post\u7528\u4e8e\u70b9\u8d5e\u548c\u53d6\u6d88\u70b9\u8d5e',
      source_title: '',
      shop_id: 0,
      shop_name: '',
      removeGroupMember: 0,
      banGroupMember: 0,
      comment_status_is: 0,
      comment_status: 1,
      is_arbitrate: 0,
      force_interest: 0,
      bigData: 0,
    },
    {
      title: 'Hot hashtags you may be interested in',
      category: 'recommendChallenge',
      recommends: [
        {
          backendCover:
            'https://duly5zwcucles.cloudfront.net/icon/hashtag_1_img.jpg',
          challengeId: '1',
          challengeTitle: 'AntiSantaSide',
          joinNumbers: 10000,
          avatars: [
            'https://duly5zwcucles.cloudfront.net/small/avatar/head_male1.jpg',
            'https://duly5zwcucles.cloudfront.net/small/avatar/head_male1.jpg',
            'https://duly5zwcucles.cloudfront.net/small/avatar/1599474266761_b9d7335ae017e38987c0a049e41ba64d_android.jpg',
          ],
        },
        {
          backendCover:
            'https://duly5zwcucles.cloudfront.net/icon/hashtag_1_img.jpg',
          challengeId: '1',
          challengeTitle: 'SantaSide',
          joinNumbers: 10000,
          avatars: [
            'https://duly5zwcucles.cloudfront.net/small/avatar/159013239570856_99b0b05d7ff8541ad723318c3693034f_ios.jpg',
            'https://duly5zwcucles.cloudfront.net/small/avatar/head_male1.jpg',
            'https://duly5zwcucles.cloudfront.net/small/avatar/head_male1.jpg',
          ],
        },
        {
          backendCover:
            'https://duly5zwcucles.cloudfront.net/icon/hashtag_1_img.jpg',
          challengeId: '1',
          challengeTitle: 'queen5012',
          joinNumbers: 1,
          avatars: [
            'https://duly5zwcucles.cloudfront.net/small/avatar/159903683397785_601830fc0d161d0310e506993cbaa34a_ios.jpg',
          ],
        },
      ],
      bigData: 0,
    },
    {
      member_id: 960,
      member_uuid: 'b9f73f23-7bc6-4de6-9f9b-df2c98076221',
      role: 'normal',
      business_id: '',
      member_name: {
        nickname: 'queen',
        displayname: 'queenqq',
        icon: [
          'https://duly5zwcucles.cloudfront.net/medal/cover/m4.png',
          'https://duly5zwcucles.cloudfront.net/icon/1587723112_5ea2bb6857008.png',
        ],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/159013239570856_99b0b05d7ff8541ad723318c3693034f_ios.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      post_id: 100578,
      title: '',
      content:
        'Interface in 2021-01-05 17:55:46 test release post is used to like and cancel likes',
      images: [
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
      ],
      video: '',
      video_cover: '',
      video_cover_ratio: 1,
      comments_num: 1,
      praise_num: 2,
      original: 0,
      publish_addr: '',
      created_at: 1609840545,
      thumb_size: {
        s: 'small/',
        m: 'middle/',
        l: 'large/',
      },
      type: 2,
      share_url:
        'https://mtest.vaffle.com/post/detail/?t=3&ctype=detail&l=en&ticket=iq03QzfTaPfTTgE81tPrdw%3D%3D',
      is_praise: 0,
      is_follow: 0,
      attention: [],
      category: 'posts',
      is_collect: 0,
      is_deals: 0,
      from: 'queen',
      offset: 0,
      recommend_state: 0,
      ticket: 'XdrpnAg60L2HrpWckurcgewSZ0jo4T4j%2BZWbfL4mtKg%3D',
      trans_white_state: 0,
      trans_btn: 1,
      guid: '',
      group_title: '',
      group_owner_uuid: '',
      publish_group_role: 0,
      group_topic_id: 0,
      gifCoverPath: '',
      source_content:
        '\u63a5\u53e3\u57282021-01-05 17:55:46\u6d4b\u8bd5\u53d1\u5e03post\u7528\u4e8e\u70b9\u8d5e\u548c\u53d6\u6d88\u70b9\u8d5e',
      source_title: '',
      shop_id: 0,
      shop_name: '',
      removeGroupMember: 0,
      banGroupMember: 0,
      comment_status_is: 0,
      comment_status: 1,
      is_arbitrate: 0,
      force_interest: 0,
      bigData: 0,
    },
    {
      member_id: 960,
      member_uuid: 'b9f73f23-7bc6-4de6-9f9b-df2c98076221',
      role: 'normal',
      business_id: '',
      member_name: {
        nickname: 'queen',
        displayname: 'queenqq',
        icon: [
          'https://duly5zwcucles.cloudfront.net/medal/cover/m4.png',
          'https://duly5zwcucles.cloudfront.net/icon/1587723112_5ea2bb6857008.png',
        ],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/159013239570856_99b0b05d7ff8541ad723318c3693034f_ios.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      post_id: 100577,
      title: '',
      content:
        'The interface released nine images in the 2021-01-05 test at 17:52:19',
      images: [
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
      ],
      video: '',
      video_cover: '',
      video_cover_ratio: 1,
      comments_num: 1,
      praise_num: 1,
      original: 0,
      publish_addr: '',
      created_at: 1609840340,
      thumb_size: {
        s: 'small/',
        m: 'middle/',
        l: 'large/',
      },
      type: 2,
      share_url:
        'https://mtest.vaffle.com/post/detail/?t=3&ctype=detail&l=en&ticket=t02UOF7d7SK7kmmUVZge3Q%3D%3D',
      is_praise: 0,
      is_follow: 0,
      attention: [],
      category: 'posts',
      is_collect: 0,
      is_deals: 0,
      from: 'queen',
      offset: 0,
      recommend_state: 0,
      ticket: 'PsAP8ckAsBBKbxEXT%2B2uQinctLx0ZX6Oq5Y6u3hJJfc%3D',
      trans_white_state: 0,
      trans_btn: 1,
      guid: '',
      group_title: '',
      group_owner_uuid: '',
      publish_group_role: 0,
      group_topic_id: 0,
      gifCoverPath: '',
      source_content:
        '\u63a5\u53e3\u57282021-01-05 17:52:19\u6d4b\u8bd5\u53d1\u5e03\u4e5d\u5f20\u56fe\u7247',
      source_title: '',
      shop_id: 0,
      shop_name: '',
      removeGroupMember: 0,
      banGroupMember: 0,
      comment_status_is: 0,
      comment_status: 1,
      is_arbitrate: 0,
      force_interest: 0,
      bigData: 0,
    },
    {
      member_id: 960,
      member_uuid: 'b9f73f23-7bc6-4de6-9f9b-df2c98076221',
      role: 'normal',
      business_id: '',
      member_name: {
        nickname: 'queen',
        displayname: 'queenqq',
        icon: [
          'https://duly5zwcucles.cloudfront.net/medal/cover/m4.png',
          'https://duly5zwcucles.cloudfront.net/icon/1587723112_5ea2bb6857008.png',
        ],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/159013239570856_99b0b05d7ff8541ad723318c3693034f_ios.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      post_id: 100576,
      title: '',
      content:
        'The interface will be tested at 2021-01-05 17:46:02 and released nine pictures',
      images: [
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
      ],
      video: '',
      video_cover: '',
      video_cover_ratio: 1,
      comments_num: 0,
      praise_num: 0,
      original: 0,
      publish_addr: '',
      created_at: 1609839965,
      thumb_size: {
        s: 'small/',
        m: 'middle/',
        l: 'large/',
      },
      type: 2,
      share_url:
        'https://mtest.vaffle.com/post/detail/?t=3&ctype=detail&l=en&ticket=7jVwank9DN9SD3Vn7cInPw%3D%3D',
      is_praise: 0,
      is_follow: 0,
      attention: [],
      category: 'posts',
      is_collect: 0,
      is_deals: 0,
      from: 'queen',
      offset: 0,
      recommend_state: 0,
      ticket: 'HNPJzKMl69r%2Fd8ycjuyIpEEFWUypw2y5RmEDft1Sdak%3D',
      trans_white_state: 0,
      trans_btn: 1,
      guid: '',
      group_title: '',
      group_owner_uuid: '',
      publish_group_role: 0,
      group_topic_id: 0,
      gifCoverPath: '',
      source_content:
        '\u63a5\u53e3\u57282021-01-05 17:46:02\u6d4b\u8bd5\u53d1\u5e03\u4e5d\u5f20\u56fe\u7247',
      source_title: '',
      shop_id: 0,
      shop_name: '',
      removeGroupMember: 0,
      banGroupMember: 0,
      comment_status_is: 0,
      comment_status: 1,
      is_arbitrate: 0,
      force_interest: 0,
      bigData: 0,
    },
    {
      member_id: 960,
      member_uuid: 'b9f73f23-7bc6-4de6-9f9b-df2c98076221',
      role: 'normal',
      business_id: '',
      member_name: {
        nickname: 'queen',
        displayname: 'queenqq',
        icon: [
          'https://duly5zwcucles.cloudfront.net/medal/cover/m4.png',
          'https://duly5zwcucles.cloudfront.net/icon/1587723112_5ea2bb6857008.png',
        ],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/159013239570856_99b0b05d7ff8541ad723318c3693034f_ios.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      post_id: 100573,
      title: '',
      content:
        'The interface is tested at 2021-01-05 16:32:22 and the post is released for comment',
      images: [
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
      ],
      video: '',
      video_cover: '',
      video_cover_ratio: 1,
      comments_num: 1,
      praise_num: 0,
      original: 0,
      publish_addr: '',
      created_at: 1609835544,
      thumb_size: {
        s: 'small/',
        m: 'middle/',
        l: 'large/',
      },
      type: 2,
      share_url:
        'https://mtest.vaffle.com/post/detail/?t=3&ctype=detail&l=en&ticket=WuC4RBwLUCdEWaMUviFTRw%3D%3D',
      is_praise: 0,
      is_follow: 0,
      attention: [],
      category: 'posts',
      is_collect: 0,
      is_deals: 0,
      from: 'queen',
      offset: 0,
      recommend_state: 0,
      ticket: 'meN2B2aev%2Bg5NNvJ1YCxq%2FW7Hicl3e2dr972ziszDVc%3D',
      trans_white_state: 0,
      trans_btn: 1,
      guid: '',
      group_title: '',
      group_owner_uuid: '',
      publish_group_role: 0,
      group_topic_id: 0,
      gifCoverPath: '',
      source_content:
        '\u63a5\u53e3\u57282021-01-05 16:32:22\u6d4b\u8bd5\u53d1\u5e03post\u7528\u4e8e\u53d1\u5e03\u8bc4\u8bba',
      source_title: '',
      shop_id: 0,
      shop_name: '',
      removeGroupMember: 0,
      banGroupMember: 0,
      comment_status_is: 0,
      comment_status: 1,
      is_arbitrate: 0,
      force_interest: 0,
      bigData: 0,
    },
    {
      member_id: 70233,
      member_uuid: 'a0c77ee1-72e9-44a6-bb35-0c27291f8230',
      role: 'normal',
      business_id: '',
      member_name: {
        nickname: 'queen627',
        displayname: 'queen627',
        icon: [],
      },
      avatar: {
        path: 'https://duly5zwcucles.cloudfront.net/__##__avatar/grey_head.png',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      post_id: 100568,
      title: '',
      content:
        'The interface will be tested and released on 2020-12-28 10:33:12',
      images: [
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
      ],
      video: '',
      video_cover: '',
      video_cover_ratio: 1,
      comments_num: 7,
      praise_num: 2,
      original: 0,
      publish_addr: '',
      created_at: 1609122791,
      thumb_size: {
        s: 'small/',
        m: 'middle/',
        l: 'large/',
      },
      type: 2,
      share_url:
        'https://mtest.vaffle.com/post/detail/?t=3&ctype=detail&l=en&ticket=uZGeV6VKr381qr1POUXxYg%3D%3D',
      is_praise: 0,
      is_follow: 1,
      attention: [],
      category: 'posts',
      is_collect: 0,
      is_deals: 0,
      from: 'queen627',
      offset: 0,
      recommend_state: 0,
      ticket: 'WiK%2BNREZF5s4wejzyq2aXJ3QLvNPItDMOkkhwXIgpKY%3D',
      trans_white_state: 0,
      trans_btn: 1,
      guid: '',
      group_title: '',
      group_owner_uuid: '',
      publish_group_role: 0,
      group_topic_id: 0,
      gifCoverPath: '',
      source_content:
        '\u63a5\u53e3\u57282020-12-28 10:33:12\u6d4b\u8bd5\u53d1\u5e03post',
      source_title: '',
      shop_id: 0,
      shop_name: '',
      removeGroupMember: 0,
      banGroupMember: 0,
      comment_status_is: 0,
      comment_status: 1,
      is_arbitrate: 1,
      force_interest: 0,
      bigData: 0,
    },
    {
      member_id: 70233,
      member_uuid: 'a0c77ee1-72e9-44a6-bb35-0c27291f8230',
      role: 'normal',
      business_id: '',
      member_name: {
        nickname: 'queen627',
        displayname: 'queen627',
        icon: [],
      },
      avatar: {
        path: 'https://duly5zwcucles.cloudfront.net/__##__avatar/grey_head.png',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      post_id: 100566,
      title: '',
      content:
        'Interface in 2020-12-28 10:33:09 test release post is used for forwarding',
      images: [
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/1512710644871_767_android.jpg',
          ratio: 1.23,
          tag: 1,
          imageTags: [],
        },
      ],
      video: '',
      video_cover: '',
      video_cover_ratio: 1,
      comments_num: 0,
      praise_num: 0,
      original: 0,
      publish_addr: '',
      created_at: 1609122789,
      thumb_size: {
        s: 'small/',
        m: 'middle/',
        l: 'large/',
      },
      type: 2,
      share_url:
        'https://mtest.vaffle.com/post/detail/?t=3&ctype=detail&l=en&ticket=09OCFJpL3Ino3jLihsdQvQ%3D%3D',
      is_praise: 0,
      is_follow: 1,
      attention: [],
      category: 'posts',
      is_collect: 0,
      is_deals: 0,
      from: 'queen627',
      offset: 0,
      recommend_state: 0,
      ticket: '%2F00XXWPi0PBhWtgUCEw77CSMorfP4HbvB1eOG0Z5aOc%3D',
      trans_white_state: 0,
      trans_btn: 1,
      guid: '',
      group_title: '',
      group_owner_uuid: '',
      publish_group_role: 0,
      group_topic_id: 0,
      gifCoverPath: '',
      source_content:
        '\u63a5\u53e3\u57282020-12-28 10:33:09\u6d4b\u8bd5\u53d1\u5e03post\u7528\u4e8e\u8f6c\u53d1',
      source_title: '',
      shop_id: 0,
      shop_name: '',
      removeGroupMember: 0,
      banGroupMember: 0,
      comment_status_is: 0,
      comment_status: 1,
      is_arbitrate: 1,
      force_interest: 0,
      bigData: 0,
    },
  ],
  is_activity_button: 0,
  activity_url: '',
  url_title: '',
  is_share: 0,
  share_content: '',
  is_verify: 0,
  path: '',
  page: 1,
  total_page: 3067,
  floatIcon: 'https://duly5zwcucles.cloudfront.net/icon/chris.png',
}

const following = {
  total: 500,
  total_page: 50,
  list: [
    {
      member_uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      member_id: 1462,
      uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      role: 'normal',
      business_id: 0,
      member_name: {
        nickname: 'damon',
        displayname: 'damon111',
        icon: ['https://duly5zwcucles.cloudfront.net/medal/icon/m8.png'],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/156921741847437_654d07d8e047b503c85e9af0e35e4811_ios.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      category: 'recommendQAComment',
      created_at: 1609832059,
      question_id: 100572,
      question_title: 'Ashes promotion and active and understanding',
      question_source_title:
        '\u9aa8\u7070\u63a8\u5e7f\u53ca\u79ef\u6781\u79ef\u6781\u548c\u7406\u89e3',
      answer_id: 27231,
      answer_source_content:
        '\u9e48\u9e55\u4f30\u8ba1\u4f1a\u4e8f\u7684\u65f6\u5019\u624d\u4f1a\u89c9\u5f97\u4f60\u6709\u591a\u91cd\u8981\uff01\u4f60\u7684\u5b69\u5b50\u600e\u4e48\u4e0d\u4e0a\u4f60\u6211\u90fd\u4e0d\u4f1a\u5fd8\u8bb0\u81ea\u5df1\u66fe\u7ecf\u90a3\u4e48\u7231\u4f60\ud83d\ude18\u3001\u4e0d\u8fc7\u6211\u8fd8\u662f\u89c9\u5f97\u4f60\u4e0d\u9002\u5408\u505a\u6211\u5973\u670b\u53cb\u662f\u4f60\u4e0d\u77e5\u9053\u6211\u4e3a\u4ec0\u4e48\u8fd9\u4e48\u4e0d\u9ad8\u5174\u6211\u4e5f\u4e0d\u4f1a\u53bb\u7684\u5730\u65b9\u90fd\u6ca1\u6709\u90a3\u4e48\u7b80\u5355\u3001',
      answer_content:
        "How important you are when you're expected to lose! Why don't your children go to you I won't forget how much I loved you\ud83d\ude18But I still think you're not fit to be my girlfriend you don't know why I'm so unhappy I won't go either place is that simple,",
      answertrans_btn: 0,
      trans_btn: 0,
      is_follow: 0,
      praise_num: 0,
      answer_comment_num: 20,
      is_praise: 0,
    },
    {
      member_id: 1462,
      member_uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      role: 'normal',
      business_id: '',
      member_name: {
        nickname: 'damon',
        displayname: 'damon111',
        icon: ['https://duly5zwcucles.cloudfront.net/medal/icon/m8.png'],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/156921741847437_654d07d8e047b503c85e9af0e35e4811_ios.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      post_id: 100243,
      title: '\u3002\u4e86\uff0cjij',
      content: '',
      images: [],
      video: '',
      video_cover: '',
      video_cover_ratio: 1,
      comments_num: 20,
      praise_num: 1,
      original: 0,
      publish_addr: '',
      created_at: 1607476157,
      thumb_size: {
        s: 'small/',
        m: 'middle/',
        l: 'large/',
      },
      type: 1,
      share_url:
        'https://mtest.vaffle.com/post/detail/?t=3&ctype=detail&l=en&ticket=UMvmPynyTA3iX%2FHP1yImHA%3D%3D',
      is_praise: 0,
      is_follow: 0,
      attention: [],
      category: 'review',
      is_collect: 0,
      is_deals: 0,
      from: 'damon',
      offset: 0,
      recommend_state: 0,
      ticket: 'TmJFlcadEICS58ZKUTzTBKxKb38vxCdrSJvGK5msuBg%3D',
      trans_white_state: 0,
      trans_btn: 0,
      guid: '',
      group_title: '',
      group_owner_uuid: '',
      publish_group_role: 0,
      group_topic_id: 0,
      gifCoverPath: '',
      source_content: 'yutyxquqqu',
      source_title: '\u3002\u4e86\uff0cjij',
      review_product: 'gongminguih',
      review_type: 'tyuywjyuysys',
      shop_id: 0,
      shop_name: '',
      removeGroupMember: 0,
      banGroupMember: 0,
      comment_status_is: 1,
      comment_status: 1,
      is_arbitrate: 0,
    },
    {
      member_id: 1462,
      member_uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      role: 'normal',
      business_id: '',
      member_name: {
        nickname: 'damon',
        displayname: 'damon111',
        icon: ['https://duly5zwcucles.cloudfront.net/medal/icon/m8.png'],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/156921741847437_654d07d8e047b503c85e9af0e35e4811_ios.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      post_id: 100234,
      title: 'gjjigjli',
      content: '',
      images: [],
      video: '',
      video_cover: '',
      video_cover_ratio: 1,
      comments_num: 0,
      praise_num: 0,
      original: 0,
      publish_addr: '',
      created_at: 1607392412,
      thumb_size: {
        s: 'small/',
        m: 'middle/',
        l: 'large/',
      },
      type: 1,
      share_url:
        'https://mtest.vaffle.com/post/detail/?t=3&ctype=detail&l=en&ticket=QpV2a5xtKDrK6L6Pikp56g%3D%3D',
      is_praise: 0,
      is_follow: 0,
      attention: [],
      category: 'review',
      is_collect: 0,
      is_deals: 0,
      from: 'damon',
      offset: 0,
      recommend_state: 0,
      ticket: 'V%2BNfLYfEuPwexhgg%2FZE7qWtkB9A%2BIDPobUdKe6Yf6l0%3D',
      trans_white_state: 0,
      trans_btn: 0,
      guid: '',
      group_title: '',
      group_owner_uuid: '',
      publish_group_role: 0,
      group_topic_id: 0,
      gifCoverPath: '',
      source_content:
        '\u817e\u8baf\u53bb\u53bb\u601d\u8003\ud83e\udd14\uff0casxwq',
      source_title: 'gjjigjli',
      review_product: ' truqilli',
      review_type: 'tqququksji',
      shop_id: 0,
      shop_name: '',
      removeGroupMember: 0,
      banGroupMember: 0,
      comment_status_is: 1,
      comment_status: 2,
      is_arbitrate: 0,
    },
    {
      member_id: 1462,
      member_uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      role: 'normal',
      business_id: '',
      member_name: {
        nickname: 'damon',
        displayname: 'damon111',
        icon: ['https://duly5zwcucles.cloudfront.net/medal/icon/m8.png'],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/156921741847437_654d07d8e047b503c85e9af0e35e4811_ios.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      post_id: 100185,
      title: '',
      content: 'Stsgsgsgsg',
      images: [
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/160730992406103_654d07d8e047b503c85e9af0e35e4811_ios.jpg',
          ratio: 1,
          tag: 1,
          imageTags: [],
        },
      ],
      video: '',
      video_cover: '',
      video_cover_ratio: 1,
      comments_num: 36,
      praise_num: 1,
      original: 0,
      publish_addr: '',
      created_at: 1607309929,
      thumb_size: {
        s: 'small/',
        m: 'middle/',
        l: 'large/',
      },
      type: 2,
      share_url:
        'https://mtest.vaffle.com/post/detail/?t=3&ctype=detail&l=en&ticket=CFjpjCGUkV2r02niDmgnfg%3D%3D',
      is_praise: 1,
      is_follow: 0,
      attention: [],
      category: 'posts',
      is_collect: 0,
      is_deals: 0,
      from: 'damon',
      offset: 0,
      recommend_state: 0,
      ticket: 'yzDliCDs0hSXuehxgmcOMlFuvnl3jkYeaRw3eCm8aUM%3D',
      trans_white_state: 0,
      trans_btn: 0,
      guid: '',
      group_title: '',
      group_owner_uuid: '',
      publish_group_role: 0,
      group_topic_id: 0,
      gifCoverPath: '',
      source_content: 'Stsgsgsgsg',
      source_title: '',
      shop_id: 0,
      shop_name: '',
      removeGroupMember: 0,
      banGroupMember: 0,
      comment_status_is: 1,
      comment_status: 1,
      is_arbitrate: 1,
    },
    {
      member_uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      member_id: 1462,
      uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      role: 'normal',
      business_id: 0,
      member_name: {
        nickname: 'damon',
        displayname: 'damon111',
        icon: ['https://duly5zwcucles.cloudfront.net/medal/icon/m8.png'],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/156921741847437_654d07d8e047b503c85e9af0e35e4811_ios.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      category: 'recommendQAComment',
      created_at: 1606184854,
      question_id: 100136,
      question_title:
        'Queenin, be sure to trust each other, a good opportunity',
      question_source_title:
        'Queenin \u4f60\u5b9a\u54e6\u5427\u4e92\u4fe1\u54e6\u597d\u673a\u4f1a',
      answer_id: 26761,
      answer_source_content: 'Scvxbddggddggd',
      answer_content: 'Scvxbddggddggd',
      answertrans_btn: 0,
      trans_btn: 1,
      is_follow: 0,
      praise_num: 1,
      answer_comment_num: 3,
      is_praise: 0,
    },
    {
      member_id: 1462,
      member_uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      role: 'normal',
      business_id: '',
      member_name: {
        nickname: 'damon',
        displayname: 'damon111',
        icon: ['https://duly5zwcucles.cloudfront.net/medal/icon/m8.png'],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/156921741847437_654d07d8e047b503c85e9af0e35e4811_ios.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      post_id: 99918,
      title: '',
      content: 'HTTP://172.100.13.184:3033/bridge',
      images: [
        {
          path:
            'https://duly5zwcucles.cloudfront.net/__##__posts/160378208879979_654d07d8e047b503c85e9af0e35e4811_ios.jpg',
          ratio: 1,
          tag: 1,
          imageTags: [],
        },
      ],
      video: '',
      video_cover: '',
      video_cover_ratio: 1,
      comments_num: 1,
      praise_num: 1,
      original: 0,
      publish_addr: '',
      created_at: 1603782096,
      thumb_size: {
        s: 'small/',
        m: 'middle/',
        l: 'large/',
      },
      type: 2,
      share_url:
        'https://mtest.vaffle.com/post/detail/?t=3&ctype=detail&l=en&ticket=5Yc8IDiri6869z9PwSrtfA%3D%3D',
      is_praise: 0,
      is_follow: 0,
      attention: [],
      category: 'posts',
      is_collect: 0,
      is_deals: 0,
      from: 'damon',
      offset: 0,
      recommend_state: 0,
      ticket: 'OqgqO5WKZztnsZ6j6xvCD15e387UiC%2FFoC3VFCgEEJY%3D',
      trans_white_state: 0,
      trans_btn: 0,
      guid: '',
      group_title: '',
      group_owner_uuid: '',
      publish_group_role: 0,
      group_topic_id: 0,
      gifCoverPath: '',
      source_content: 'http://172.100.13.184:3033/bridge',
      source_title: '',
      shop_id: 0,
      shop_name: '',
      removeGroupMember: 0,
      banGroupMember: 0,
      comment_status_is: 1,
      comment_status: 1,
      is_arbitrate: 1,
    },
    {
      member_uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      member_id: 1462,
      uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      role: 'normal',
      business_id: 0,
      member_name: {
        nickname: 'damon',
        displayname: 'damon111',
        icon: ['https://duly5zwcucles.cloudfront.net/medal/icon/m8.png'],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/156921741847437_654d07d8e047b503c85e9af0e35e4811_ios.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      category: 'recommendQAComment',
      created_at: 1601024844,
      question_id: 99072,
      question_title: 'Hello 111 222 333',
      question_source_title: '\u4f60\u597d111 222 333',
      answer_id: 26505,
      answer_source_content: 'qqqqqq',
      answer_content: 'qqqqqq',
      answertrans_btn: 0,
      trans_btn: 1,
      is_follow: 0,
      praise_num: 0,
      answer_comment_num: 0,
      is_praise: 0,
    },
    {
      member_uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      member_id: 1462,
      uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      role: 'normal',
      business_id: 0,
      member_name: {
        nickname: 'damon',
        displayname: 'damon111',
        icon: ['https://duly5zwcucles.cloudfront.net/medal/icon/m8.png'],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/156921741847437_654d07d8e047b503c85e9af0e35e4811_ios.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      category: 'recommendQAComment',
      created_at: 1598249075,
      question_id: 98710,
      question_title: 'queen032',
      question_source_title: 'queen032',
      answer_id: 26197,
      answer_source_content: '\u5168\u7403\u73a9\u513f\u8ba9\u4eba\u542c',
      answer_content: 'Global play makes people listen',
      answertrans_btn: 0,
      trans_btn: 1,
      is_follow: 0,
      praise_num: 0,
      answer_comment_num: 0,
      is_praise: 0,
    },
    {
      member_uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      member_id: 1462,
      uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      role: 'normal',
      business_id: 0,
      member_name: {
        nickname: 'damon',
        displayname: 'damon111',
        icon: ['https://duly5zwcucles.cloudfront.net/medal/icon/m8.png'],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/156921741847437_654d07d8e047b503c85e9af0e35e4811_ios.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      category: 'recommendQAComment',
      created_at: 1598248887,
      question_id: 98787,
      question_title: 'Sa Sa Sa',
      question_source_title: '\u6492\u6492\u6492',
      answer_id: 26196,
      answer_source_content:
        '\u6211\u545c\u545c\u545c\u545c\u545c\u545c\u545c\u545c',
      answer_content: 'I oooooooooooo',
      answertrans_btn: 0,
      trans_btn: 1,
      is_follow: 0,
      praise_num: 0,
      answer_comment_num: 0,
      is_praise: 0,
    },
    {
      member_uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      member_id: 1462,
      uuid: 'bdf8adc6-28c9-425a-b052-fda998a0597d',
      role: 'normal',
      business_id: 0,
      member_name: {
        nickname: 'damon',
        displayname: 'damon111',
        icon: ['https://duly5zwcucles.cloudfront.net/medal/icon/m8.png'],
      },
      avatar: {
        path:
          'https://duly5zwcucles.cloudfront.net/__##__avatar/156921741847437_654d07d8e047b503c85e9af0e35e4811_ios.jpg',
        thumb_size: {
          s: 'small/',
          m: 'middle/',
          l: 'large/',
        },
        ranking: 0,
        pendantPath: '',
      },
      category: 'recommendQAComment',
      created_at: 1598241498,
      question_id: 98798,
      question_title: "Derrick's problem",
      question_source_title: 'Derrick \u7684\u95ee\u9898',
      answer_id: 26193,
      answer_source_content:
        '\u5bcc\u542b\u4e30\u5bcc\u808c\u80a4\u4fa0\u809d\u4e49\u80c6\u7684\u8863\u670d',
      answer_content: 'Clothes rich in rich skin',
      answertrans_btn: 0,
      trans_btn: 1,
      is_follow: 0,
      praise_num: 0,
      answer_comment_num: 0,
      is_praise: 0,
    },
  ],
  page: 1,
}
