export const mockData = {
  "success": true,
  "resCode": "00100000",
  "obj": {
    "fullPath": "102660>103182>102821>102667",
    "cateAllList": [{
      "categorySid": "101742",
      "categoryName": "手机数码/电脑办公2",
      "parentCategorySid": null,
      "recursiveCategorySids": "101742",
      "recursiveCategoryNames": "手机数码/电脑办公2",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "214956",
      "categoryName": "测试408",
      "parentCategorySid": null,
      "recursiveCategorySids": "214956",
      "recursiveCategoryNames": "测试408",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "102103",
      "categoryName": "运动户外",
      "parentCategorySid": null,
      "recursiveCategorySids": "102103",
      "recursiveCategoryNames": "运动户外",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "102228",
      "categoryName": "家用电器2",
      "parentCategorySid": null,
      "recursiveCategorySids": "102228",
      "recursiveCategoryNames": "家用电器2",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "102261",
      "categoryName": "珠宝饰品/手表眼镜",
      "parentCategorySid": null,
      "recursiveCategorySids": "102261",
      "recursiveCategoryNames": "珠宝饰品/手表眼镜",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "102435",
      "categoryName": "母婴/玩具/童装",
      "parentCategorySid": null,
      "recursiveCategorySids": "102435",
      "recursiveCategoryNames": "母婴/玩具/童装",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "102516",
      "categoryName": "家庭清洁/一次性用品/衣物清洁",
      "parentCategorySid": null,
      "recursiveCategorySids": "102516",
      "recursiveCategoryNames": "家庭清洁/一次性用品/衣物清洁",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "102537",
      "categoryName": "家居家纺/餐厨/家具/家装/宠物园艺",
      "parentCategorySid": null,
      "recursiveCategorySids": "102537",
      "recursiveCategoryNames": "家居家纺/餐厨/家具/家装/宠物园艺",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "102561",
      "categoryName": "服装",
      "parentCategorySid": null,
      "recursiveCategorySids": "102561",
      "recursiveCategoryNames": "服装",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "102653",
      "categoryName": "鞋靴/箱包/皮具",
      "parentCategorySid": null,
      "recursiveCategorySids": "102653",
      "recursiveCategoryNames": "鞋靴/箱包/皮具",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "102660",
      "categoryName": "食品",
      "parentCategorySid": null,
      "recursiveCategorySids": "102660",
      "recursiveCategoryNames": "食品",
      "leaf": 0,
      "children": [{
        "categorySid": "102693",
        "categoryName": "咖啡",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>102693",
        "recursiveCategoryNames": "食品>咖啡",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "221136",
        "categoryName": "测试目录-Q",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>221136",
        "recursiveCategoryNames": "食品>测试目录-Q",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "102703",
        "categoryName": "饮料",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>102703",
        "recursiveCategoryNames": "食品>饮料",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "102706",
        "categoryName": "常温乳制品",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>102706",
        "recursiveCategoryNames": "食品>常温乳制品",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "102711",
        "categoryName": "食用油",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>102711",
        "recursiveCategoryNames": "食品>食用油",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "102727",
        "categoryName": "厨房调料/果酱/沙拉",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>102727",
        "recursiveCategoryNames": "食品>厨房调料/果酱/沙拉",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "102855",
        "categoryName": "茶叶",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>102855",
        "recursiveCategoryNames": "食品>茶叶",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "102884",
        "categoryName": "方便速食",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>102884",
        "recursiveCategoryNames": "食品>方便速食",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "102901",
        "categoryName": "南北干货",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>102901",
        "recursiveCategoryNames": "食品>南北干货",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "103136",
        "categoryName": "饼干/糕点",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>103136",
        "recursiveCategoryNames": "食品>饼干/糕点",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "103182",
        "categoryName": "零食/坚果/蜜饯/果干",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>103182",
        "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干",
        "leaf": 0,
        "children": [{
          "categorySid": "102669",
          "categoryName": "蜜饯/枣类/梅/果干",
          "parentCategorySid": "103182",
          "recursiveCategorySids": "102660>103182>102669",
          "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>蜜饯/枣类/梅/果干",
          "leaf": 0,
          "children": null
        }, {
          "categorySid": "102821",
          "categoryName": "坚果/炒货",
          "parentCategorySid": "103182",
          "recursiveCategorySids": "102660>103182>102821",
          "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货",
          "leaf": 0,
          "children": [{
            "categorySid": "102666",
            "categoryName": "长寿果/碧根果",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>102666",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>长寿果/碧根果",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "103228",
            "categoryName": "大核桃",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>103228",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>大核桃",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "102668",
            "categoryName": "花生",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>102668",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>花生",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "102822",
            "categoryName": "杏仁/巴旦木",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>102822",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>杏仁/巴旦木",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "102823",
            "categoryName": "开心果",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>102823",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>开心果",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "102824",
            "categoryName": "腰果",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>102824",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>腰果",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "102825",
            "categoryName": "瓜子",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>102825",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>瓜子",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "102826",
            "categoryName": "豆类（炒货）",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>102826",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>豆类（炒货）",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "103209",
            "categoryName": "小核桃/山核桃",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>103209",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>小核桃/山核桃",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "103212",
            "categoryName": "栗类制品",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>103212",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>栗类制品",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "103213",
            "categoryName": "松子",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>103213",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>松子",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "103214",
            "categoryName": "夏威夷果",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>103214",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>夏威夷果",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "103215",
            "categoryName": "榛子",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>103215",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>榛子",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "103216",
            "categoryName": "香榧",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>103216",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>香榧",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "103217",
            "categoryName": "鲍鱼果",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>103217",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>鲍鱼果",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "103218",
            "categoryName": "白果/银杏果",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>103218",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>白果/银杏果",
            "leaf": 1,
            "children": null
          }, {
            "categorySid": "102667",
            "categoryName": "其它坚果",
            "parentCategorySid": "102821",
            "recursiveCategorySids": "102660>103182>102821>102667",
            "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>坚果/炒货>其它坚果",
            "leaf": 1,
            "children": null
          }]
        }, {
          "categorySid": "103261",
          "categoryName": "鱿鱼丝/鱼干/海味即食",
          "parentCategorySid": "103182",
          "recursiveCategorySids": "102660>103182>103261",
          "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>鱿鱼丝/鱼干/海味即食",
          "leaf": 0,
          "children": null
        }, {
          "categorySid": "103260",
          "categoryName": "常温奶酪",
          "parentCategorySid": "103182",
          "recursiveCategorySids": "102660>103182>103260",
          "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>常温奶酪",
          "leaf": 1,
          "children": null
        }, {
          "categorySid": "103248",
          "categoryName": "肉干肉脯/豆制品/熟食",
          "parentCategorySid": "103182",
          "recursiveCategorySids": "102660>103182>103248",
          "recursiveCategoryNames": "食品>零食/坚果/蜜饯/果干>肉干肉脯/豆制品/熟食",
          "leaf": 0,
          "children": null
        }]
      }, {
        "categorySid": "103205",
        "categoryName": "糖果/巧克力/果冻/布丁",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>103205",
        "recursiveCategoryNames": "食品>糖果/巧克力/果冻/布丁",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "103289",
        "categoryName": "粮食制品",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>103289",
        "recursiveCategoryNames": "食品>粮食制品",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "103404",
        "categoryName": "无糖食品",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>103404",
        "recursiveCategoryNames": "食品>无糖食品",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "105162",
        "categoryName": "茶具",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>105162",
        "recursiveCategoryNames": "食品>茶具",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "211978",
        "categoryName": "迁移到的目录",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>211978",
        "recursiveCategoryNames": "食品>迁移到的目录",
        "leaf": 0,
        "children": null
      }, {
        "categorySid": "212417",
        "categoryName": "ml112",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>212417",
        "recursiveCategoryNames": "食品>ml112",
        "leaf": 1,
        "children": null
      }, {
        "categorySid": "102700",
        "categoryName": "酒全球购测试",
        "parentCategorySid": "102660",
        "recursiveCategorySids": "102660>102700",
        "recursiveCategoryNames": "食品>酒全球购测试",
        "leaf": 0,
        "children": null
      }]
    }, {
      "categorySid": "102768",
      "categoryName": "生鲜食品",
      "parentCategorySid": null,
      "recursiveCategorySids": "102768",
      "recursiveCategoryNames": "生鲜食品",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "103443",
      "categoryName": "美容护理/个人清洁/纸制品",
      "parentCategorySid": null,
      "recursiveCategorySids": "103443",
      "recursiveCategoryNames": "美容护理/个人清洁/纸制品",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "103771",
      "categoryName": "汽车",
      "parentCategorySid": null,
      "recursiveCategorySids": "103771",
      "recursiveCategoryNames": "汽车",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "104715",
      "categoryName": "生活服务",
      "parentCategorySid": null,
      "recursiveCategorySids": "104715",
      "recursiveCategoryNames": "生活服务",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "105098",
      "categoryName": "图书/音像",
      "parentCategorySid": null,
      "recursiveCategorySids": "105098",
      "recursiveCategoryNames": "图书/音像",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211407",
      "categoryName": "xcmtest",
      "parentCategorySid": null,
      "recursiveCategorySids": "211407",
      "recursiveCategoryNames": "xcmtest",
      "leaf": 1,
      "children": null
    }, {
      "categorySid": "211413",
      "categoryName": "iPhone",
      "parentCategorySid": null,
      "recursiveCategorySids": "211413",
      "recursiveCategoryNames": "iPhone",
      "leaf": 1,
      "children": null
    }, {
      "categorySid": "211453",
      "categoryName": "生活用品",
      "parentCategorySid": null,
      "recursiveCategorySids": "211453",
      "recursiveCategoryNames": "生活用品",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211495",
      "categoryName": "礼品卡",
      "parentCategorySid": null,
      "recursiveCategorySids": "211495",
      "recursiveCategoryNames": "礼品卡",
      "leaf": 1,
      "children": null
    }, {
      "categorySid": "211575",
      "categoryName": "211530小米",
      "parentCategorySid": null,
      "recursiveCategorySids": "211575",
      "recursiveCategoryNames": "211530小米",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211599",
      "categoryName": "oppo R72-测试2",
      "parentCategorySid": null,
      "recursiveCategorySids": "211599",
      "recursiveCategoryNames": "oppo R72-测试2",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211623",
      "categoryName": "test2016051401",
      "parentCategorySid": null,
      "recursiveCategorySids": "211623",
      "recursiveCategoryNames": "test2016051401",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211627",
      "categoryName": "test11",
      "parentCategorySid": null,
      "recursiveCategorySids": "211627",
      "recursiveCategoryNames": "test11",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211655",
      "categoryName": "迁移目录一二",
      "parentCategorySid": null,
      "recursiveCategorySids": "211655",
      "recursiveCategoryNames": "迁移目录一二",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211677",
      "categoryName": "组合商品",
      "parentCategorySid": null,
      "recursiveCategorySids": "211677",
      "recursiveCategoryNames": "组合商品",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211755",
      "categoryName": "目录优化",
      "parentCategorySid": null,
      "recursiveCategorySids": "211755",
      "recursiveCategoryNames": "目录优化",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211757",
      "categoryName": "目录优化1",
      "parentCategorySid": null,
      "recursiveCategorySids": "211757",
      "recursiveCategoryNames": "目录优化1",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211775",
      "categoryName": "test二零二零",
      "parentCategorySid": null,
      "recursiveCategorySids": "211775",
      "recursiveCategoryNames": "test二零二零",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211816",
      "categoryName": "monogata",
      "parentCategorySid": null,
      "recursiveCategorySids": "211816",
      "recursiveCategoryNames": "monogata",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211861",
      "categoryName": "MP商品测试",
      "parentCategorySid": null,
      "recursiveCategorySids": "211861",
      "recursiveCategoryNames": "MP商品测试",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211878",
      "categoryName": "同步111",
      "parentCategorySid": null,
      "recursiveCategorySids": "211878",
      "recursiveCategoryNames": "同步111",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211885",
      "categoryName": "test0819",
      "parentCategorySid": null,
      "recursiveCategorySids": "211885",
      "recursiveCategoryNames": "test0819",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211888",
      "categoryName": "食品1",
      "parentCategorySid": null,
      "recursiveCategorySids": "211888",
      "recursiveCategoryNames": "食品1",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211893",
      "categoryName": "图书",
      "parentCategorySid": null,
      "recursiveCategorySids": "211893",
      "recursiveCategoryNames": "图书",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211899",
      "categoryName": "奶制品",
      "parentCategorySid": null,
      "recursiveCategorySids": "211899",
      "recursiveCategoryNames": "奶制品",
      "leaf": 1,
      "children": null
    }, {
      "categorySid": "211901",
      "categoryName": "餐具",
      "parentCategorySid": null,
      "recursiveCategorySids": "211901",
      "recursiveCategoryNames": "餐具",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211916",
      "categoryName": "三端合并验证",
      "parentCategorySid": null,
      "recursiveCategorySids": "211916",
      "recursiveCategoryNames": "三端合并验证",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "211976",
      "categoryName": "20160907测试",
      "parentCategorySid": null,
      "recursiveCategorySids": "211976",
      "recursiveCategoryNames": "20160907测试",
      "leaf": 1,
      "children": null
    }, {
      "categorySid": "212036",
      "categoryName": "到家类目",
      "parentCategorySid": null,
      "recursiveCategorySids": "212036",
      "recursiveCategoryNames": "到家类目",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "212117",
      "categoryName": "新类目产品导入",
      "parentCategorySid": null,
      "recursiveCategorySids": "212117",
      "recursiveCategoryNames": "新类目产品导入",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "212256",
      "categoryName": "我新增",
      "parentCategorySid": null,
      "recursiveCategorySids": "212256",
      "recursiveCategoryNames": "我新增",
      "leaf": 1,
      "children": null
    }, {
      "categorySid": "212276",
      "categoryName": "新增目录迁移",
      "parentCategorySid": null,
      "recursiveCategorySids": "212276",
      "recursiveCategoryNames": "新增目录迁移",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "212278",
      "categoryName": "新增2233",
      "parentCategorySid": null,
      "recursiveCategorySids": "212278",
      "recursiveCategoryNames": "新增2233",
      "leaf": 1,
      "children": null
    }, {
      "categorySid": "212296",
      "categoryName": "新增同步",
      "parentCategorySid": null,
      "recursiveCategorySids": "212296",
      "recursiveCategoryNames": "新增同步",
      "leaf": 1,
      "children": null
    }, {
      "categorySid": "212316",
      "categoryName": "我新增的",
      "parentCategorySid": null,
      "recursiveCategorySids": "212316",
      "recursiveCategoryNames": "我新增的",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "212416",
      "categoryName": "455",
      "parentCategorySid": null,
      "recursiveCategorySids": "212416",
      "recursiveCategoryNames": "455",
      "leaf": 1,
      "children": null
    }, {
      "categorySid": "212437",
      "categoryName": "新增789",
      "parentCategorySid": null,
      "recursiveCategorySids": "212437",
      "recursiveCategoryNames": "新增789",
      "leaf": 1,
      "children": null
    }, {
      "categorySid": "212497",
      "categoryName": "cps通知测试",
      "parentCategorySid": null,
      "recursiveCategorySids": "212497",
      "recursiveCategoryNames": "cps通知测试",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "212536",
      "categoryName": "11111",
      "parentCategorySid": null,
      "recursiveCategorySids": "212536",
      "recursiveCategoryNames": "11111",
      "leaf": 1,
      "children": null
    }, {
      "categorySid": "212556",
      "categoryName": "云商",
      "parentCategorySid": null,
      "recursiveCategorySids": "212556",
      "recursiveCategoryNames": "云商",
      "leaf": 1,
      "children": null
    }, {
      "categorySid": "212557",
      "categoryName": "云店商品",
      "parentCategorySid": null,
      "recursiveCategorySids": "212557",
      "recursiveCategoryNames": "云店商品",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "212576",
      "categoryName": "test001",
      "parentCategorySid": null,
      "recursiveCategorySids": "212576",
      "recursiveCategoryNames": "test001",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "212596",
      "categoryName": "Riso商品",
      "parentCategorySid": null,
      "recursiveCategorySids": "212596",
      "recursiveCategoryNames": "Riso商品",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "214188",
      "categoryName": "逸刻类目",
      "parentCategorySid": null,
      "recursiveCategorySids": "214188",
      "recursiveCategoryNames": "逸刻类目",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "214896",
      "categoryName": "目录推搜索",
      "parentCategorySid": null,
      "recursiveCategorySids": "214896",
      "recursiveCategoryNames": "目录推搜索",
      "leaf": 0,
      "children": null
    }, {
      "categorySid": "101989",
      "categoryName": "保健品/器械/药品/成人计生",
      "parentCategorySid": null,
      "recursiveCategorySids": "101989",
      "recursiveCategoryNames": "保健品/器械/药品/成人计生",
      "leaf": 0,
      "children": null
    }]
  },
  "msg": null
}
