import React, { useEffect } from "react"
// import PropTypes from 'prop-types'

// export const config = { amp: true };

const PalWorldTest = (props) => {
  useEffect(() => {
    window.info = {
      zh,
      translate,
    }
    window.testM = testM
  }, [])
  const testM = () => {
    // const palsMap = translate.palsList.reduce((prev, cur) => {
    //   prev[cur.CodeName] = cur
    //   return prev
    // }, {})
    translate.skillsInfo.forEach((item) => {
      const codeName = item.CodeName
      const zh_skills = zh.skills[codeName]
      const zh_desc = zh.skills_desc[zh_skills]
      if (zh_skills) {
        item.Name = zh_skills
      }
      if (zh_desc) {
        item.Description = zh_desc
      }
    })
    translate.palsList.forEach((item) => {
      const codeName = item.CodeName
      const zh_Name = zh.palList[codeName]
      if (zh_Name) {
        item.Name = zh_Name
      }
      var zh_moveset = {}
      const tmp = Object.keys(zh.moveset)
      Object.keys(item.Moveset).forEach((item2) => {
        if (!tmp.includes(item2)) {
          console.log("-->Moveset: ", item2)
        }
        const key = zh.moveset[item2] ?? item2
        zh_moveset[key] = item.Moveset[item2]
      })
      item.Moveset = zh_moveset

      item.Type = item.Type.map((t) => {
        let tmp = zh.types[t]
        if (!tmp) {
          console.log("-->Type: ", tmp)
          tmp = t
        }
        return tmp
      })
    })
    return {
      skillsInfo: translate.skillsInfo,
      palsList: translate.palsList,
    }
    // return palsMap
  }
  return (
    <>
      <span>test</span>
      {/* <style jsx>{``}</style> */}
    </>
  )
}

// PalWorldTest.propTypes = {}
// export const getStaticPaths = async () => { return { paths, fallback: true }; }
// export const getStaticProps = async ({ params, preview, previewData }) => { return { props: { } }; }
// export const getServerSideProps = async ({ params, req, res, query, preview, previewData }) => {}
// PalWorldTest.getInitialProps = async ({ req }) => {}
PalWorldTest.displayName = "🔗 PalWorldTest - COMPONENT"

export default PalWorldTest

const zh = {
  // 特性
  skills: {
    ElementResist_Normal_1_PAL: "一反常态",
    ElementResist_Dark_1_PAL: "阳光开朗",
    ElementResist_Dragon_1_PAL: "屠龙之人",
    ElementResist_Ice_1_PAL: "高温体质",
    ElementResist_Fire_1_PAL: "拥抱烈日",
    ElementResist_Leaf_1_PAL: "除草效果",
    ElementResist_Earth_1_PAL: "抗震结构",
    ElementResist_Thunder_1_PAL: "绝缘体",
    ElementResist_Aqua_1_PAL: "防水性能",

    ElementBoost_Normal_1_PAL: "禅境",
    ElementBoost_Dark_1_PAL: "夜幕",
    ElementBoost_Dragon_1_PAL: "龙之血脉",
    ElementBoost_Ice_1_PAL: "冷血",
    ElementBoost_Fire_1_PAL: "喜欢玩火",
    ElementBoost_Leaf_1_PAL: "草木馨香",
    ElementBoost_Earth_1_PAL: "大地之力",
    ElementBoost_Thunder_1_PAL: "电容",
    ElementBoost_Aqua_1_PAL: "喜欢戏水",

    ElementBoost_Normal_2_PAL: "圣天",
    ElementBoost_Dark_2_PAL: "冥王",
    ElementBoost_Dragon_2_PAL: "神龙",
    ElementBoost_Ice_2_PAL: "冰帝",
    ElementBoost_Fire_2_PAL: "炎帝",
    ElementBoost_Leaf_2_PAL: "精灵王",
    ElementBoost_Earth_2_PAL: "岩帝",
    ElementBoost_Thunder_2_PAL: "雷帝",
    ElementBoost_Aqua_2_PAL: "海皇",

    PAL_ALLAttack_up1: "勇敢",
    PAL_ALLAttack_up2: "凶猛",
    PAL_ALLAttack_down1: "胆小",
    PAL_ALLAttack_down2: "消极主义",

    Deffence_up1: "坚硬皮肤",
    Deffence_up2: "顽强肉体",
    Deffence_down1: "弱不禁风",
    Deffence_down2: "骨质疏松",

    TrainerMining_up1: "矿山首领",
    TrainerLogging_up1: "采伐领袖",
    TrainerATK_UP_1: "突袭指挥官",
    TrainerWorkSpeed_UP_1: "啦啦队",
    TrainerDEF_UP_1: "铁壁军师",

    PAL_Sanity_Down_1: "积极思维",
    PAL_Sanity_Down_2: "工作狂",
    PAL_Sanity_Up_1: "情绪不稳",
    PAL_Sanity_Up_2: "毁灭欲望",

    PAL_FullStomach_Down_1: "小胃",
    PAL_FullStomach_Down_2: "节食大师",
    PAL_FullStomach_Up_1: "贪吃",
    PAL_FullStomach_Up_2: "无底之胃",

    CraftSpeed_up1: "认真",
    CraftSpeed_up2: "工匠精神",
    CraftSpeed_down1: "笨手笨脚",
    CraftSpeed_down2: "偷懒成瘾",

    MoveSpeed_up_1: "灵活",
    MoveSpeed_up_2: "运动健将",
    MoveSpeed_up_3: "神速",

    PAL_CorporateSlave: "社畜",

    PAL_rude: "粗暴",
    Noukin: "脑筋",

    PAL_oraora: "强势",

    PAL_conceited: "自恋狂",

    PAL_masochist: "受虐狂",
    PAL_sadist: "虐待狂",

    Rare: "稀有",
    Legend: "传说",
  },
  // 特性描述
  skills_desc: {
    未知: " 不存在或不在我们的数据库中",
    空: "此帕鲁在该槽位没有技能",

    一反常态: "-10%受到的无属性攻击伤害",
    阳光开朗: "-10%受到的暗属性攻击伤害",
    屠龙之人: "-10%受到的龙属性攻击伤害",
    高温体质: "-10%受到的冰属性攻击伤害",
    拥抱烈日: "-10%受到的火属性攻击伤害",
    除草效果: "-10%受到的草属性攻击伤害",
    抗震结构: "-10%受到的地属性攻击伤害",
    绝缘体: "-10%受到的电属性攻击伤害",
    防水性能: "-10%受到的水属性攻击伤害",

    禅境: "+10%造成的无属性攻击伤害",
    夜幕: "+10%造成的暗属性攻击伤害",
    龙之血脉: "+10%造成的龙属性攻击伤害",
    冷血: "+10%造成的冰属性攻击伤害",
    喜欢玩火: "+10%造成的火属性攻击伤害",
    草木馨香: "+10%造成的草属性攻击伤害",
    大地之力: "+10%造成的地属性攻击伤害",
    电容: "+10%造成的电属性攻击伤害",
    喜欢戏水: "+10%造成的水属性攻击伤害",

    圣天: "+20%造成的无属性攻击伤害; 圣光骑士的专属能力",
    冥王: "+20%造成的暗属性攻击伤害; 混沌骑士的专属能力",
    神龙: "+20%造成的龙属性攻击伤害; 空涡龙的专属能力",
    冰帝: "+20%造成的冰属性攻击伤害; 唤冬兽的专属能力",
    炎帝: "+20%造成的火属性攻击伤害; 焰煌的专属能力",
    精灵王: "+20%造成的草属性攻击伤害; 百合女王的专属能力",
    岩帝: "+20%造成的地属性攻击伤害; 阿努比斯的专属能力",
    雷帝: "+20%造成的电属性攻击伤害; 波鲁杰克斯的专属能力",
    海皇: "+20%造成的水属性攻击伤害; 覆海龙的专属能力",

    勇敢: "+10%攻击力",
    凶猛: "+20%攻击力",
    胆小: "-10%攻击力",
    消极主义: "-20%攻击力",

    坚硬皮肤: "+10%防御力",
    顽强肉体: "+20%防御力",
    弱不禁风: "-10%防御力",
    骨质疏松: "-20%防御力",

    采伐领袖: "+25%玩家伐木效率",
    矿山首领: "+25%玩家采矿效率",
    突袭指挥官: "+10%玩家攻击力",
    啦啦队: "+25%玩家工作速度",
    铁壁军师: "+10%玩家防御力",

    积极思维: "理智下降速度减缓10%",
    工作狂: "理智下降速度减缓15%",
    情绪不稳: "理智下降速度加快10%",
    毁灭欲望: "理智下降速度加快15%",

    小胃: "饱食下降速度减缓10%",
    节食大师: "饱食下降速度减缓15%",
    贪吃: "饱食下降速度加快10%",
    无底之胃: "饱食下降速度加快15%",

    认真: "+20%工作速度",
    工匠精神: "+50%工作速度",
    笨手笨脚: "-10%工作速度",
    偷懒成瘾: "-30%工作速度",

    灵活: "+10%移动速度",
    运动健将: "+20%移动速度",
    神速: "+30%移动速度",

    社畜: "+30%工作速度, -30%攻击力",

    粗暴: "+15%攻击力, -10%工作速度",
    脑筋: "+30%攻击力, -50%工作速度",

    强势: "+10%攻击力, -10%防御力",

    自恋狂: "+10%工作速度, -10%防御力",

    受虐狂: "+15%防御力, -15%攻击力",
    虐待狂: "+15%攻击力, -15%防御力",

    稀有: "+15%攻击力, +15%工作速度",
    传说: "+20%攻击力, +20%防御力, +15%移动速度",

    "": "",
  },
  // 帕鲁列表
  palList: {
    // # 普通帕鲁列表
    Alpaca: "美露帕",
    AmaterasuWolf: "苍焰狼",
    Anubis: "阿努比斯",
    Baphomet: "炎魔羊",
    Baphomet_Dark: "暗魔羊",
    Bastet: "喵丝特",
    Bastet_Ice: "冰丝特",
    BerryGoat: "灌木羊",
    BirdDragon: "烽歌龙",
    BirdDragon_Ice: "霜歌龙",
    BlackCentaur: "混沌骑士",
    BlackGriffon: "异构格里芬",
    BlackMetalDragon: "魔渊龙",
    BlueDragon: "碧海龙",
    BluePlatypus: "冲浪鸭",
    Boar: "草莽猪",
    CaptainPenguin: "企丸王",
    Carbunclo: "翠叶鼠",
    CatBat: "猫蝠怪",
    CatMage: "暗巫猫",
    CatVampire: "夜幕魔蝠",
    ChickenPal: "皮皮鸡",
    ColorfulBird: "炸弹鸟",
    CowPal: "波霸牛",
    CuteButterfly: "幻悦蝶",
    CuteFox: "玉藻狐",
    CuteMole: "遁地鼠",
    DarkCrow: "黑鸦隐士",
    DarkScorpion: "冥铠蝎",
    Deer: "紫霞鹿",
    Deer_Ground: "祇岳鹿",
    DreamDemon: "寐魔",
    DrillGame: "碎岩龟",
    Eagle: "天擒鸟",
    ElecCat: "伏特喵",
    ElecPanda: "暴电熊",
    FairyDragon: "精灵龙",
    FairyDragon_Water: "水灵龙",
    FengyunDeeper: "云海鹿",
    FireKirin: "火麒麟",
    FireKirin_Dark: "邪麒麟",
    FlameBambi: "燎火鹿",
    FlameBuffalo: "炽焰牛",
    FlowerDinosaur: "花冠龙",
    FlowerDinosaur_Electric: "雷冠龙",
    FlowerDoll: "花丽娜",
    FlowerRabbit: "波娜兔",
    FlyingManta: "鲁米儿",
    FoxMage: "焰巫狐",
    Ganesha: "壶小象",
    Garm: "猎狼",
    GhostBeast: "噬魂兽",
    Gorilla: "铁拳猿",
    GrassMammoth: "森猛犸",
    GrassMammoth_Ice: "雪猛犸",
    GrassPanda: "叶胖达",
    GrassPanda_Electric: "雷胖达",
    GrassRabbitMan: "踏春兔",
    HadesBird: "雷冥鸟",
    HawkBird: "疾风隼",
    Hedgehog: "电棘鼠",
    Hedgehog_Ice: "冰刺鼠",
    HerculesBeetle: "铠格力斯",
    Horus: "荷鲁斯",
    IceDeer: "严冬鹿",
    IceFox: "吹雪狐",
    IceHorse: "唤冬兽",
    IceHorse_Dark: "唤夜兽",
    JetDragon: "空涡龙",
    Kelpie: "水灵儿",
    Kelpie_Fire: "火灵儿",
    KingAlpaca: "君王美露帕",
    KingAlpaca_Ice: "冰帝美露帕",
    KingBahamut: "焰煌",
    Kirin: "雷角马",
    Kitsunebi: "火绒狐",
    LavaGirl: "融焰娘",
    LazyCatfish: "趴趴鲶",
    LazyDragon: "佩克龙",
    LazyDragon_Electric: "派克龙",
    LilyQueen: "百合女王",
    LilyQueen_Dark: "黑月女王",
    LittleBriarRose: "荆棘魔仙",
    LizardMan: "朋克蜥",
    LizardMan_Fire: "热血蜥",
    Manticore: "狱焰王",
    Manticore_Dark: "狱阎王",
    Monkey: "新叶猿",
    MopBaby: "毛掸儿",
    MopKing: "毛老爹",
    Mutant: "秘斯媞雅",
    NaughtyCat: "笑魇猫",
    NegativeKoala: "瞅什魔",
    NegativeOctopus: "勾魂鱿",
    NightFox: "露娜蒂",
    Penguin: "企丸丸",
    PinkCat: "捣蛋猫",
    PinkLizard: "博爱蜥",
    PinkRabbit: "姬小兔",
    PlantSlime: "叶泥泥",
    QueenBee: "女皇蜂",
    RaijinDaughter: "雷鸣童子",
    RedArmorBird: "燧火鸟",
    RobinHood: "羽箭射手",
    RobinHood_Ground: "山岳射手",
    Ronin: "浪刃武士",
    SaintCentaur: "圣光骑士",
    SakuraSaurus: "连理龙",
    SakuraSaurus_Water: "海誓龙",
    Serpent: "滑水蛇",
    Serpent_Ground: "流沙蛇",
    SharkKid: "鲨小子",
    SharkKid_Fire: "红小鲨",
    Sheepball: "棉悠悠",
    SkyDragon: "天羽龙",
    SoldierBee: "骑士蜂",
    Suzaku: "朱雀",
    Suzaku_Water: "清雀",
    SweetsSheep: "棉花糖",
    ThunderBird: "迅雷鸟",
    ThunderDog: "霹雳犬",
    ThunderDragonMan: "波鲁杰克斯",
    Umihebi: "覆海龙",
    Umihebi_Fire: "腾炎龙",
    VioletFairy: "薇莉塔",
    VolcanicMonster: "熔岩兽",
    VolcanicMonster_Ice: "寒霜兽",
    WeaselDragon: "疾旋鼬",
    Werewolf: "月镰魔",
    WhiteMoth: "绸笠蛾",
    WhiteTiger: "冰棘兽",
    WindChimes: "吊缚灵",
    WindChimes_Ice: "冰缚灵",
    WizardOwl: "啼卡尔",
    WoolFox: "米露菲",
    Yeti: "白绒雪怪",
    Yeti_Grass: "绿苔绒怪",

    // # 高塔BOSS
    GYM_ThunderDragonMan: "BOSS-波鲁杰克斯",
    GYM_LilyQueen: "BOSS-百合女王",
    GYM_Horus: "BOSS-荷鲁斯",
    GYM_BlackGriffon: "BOSS-异构格里芬",
    GYM_ElecPanda: "BOSS-暴电熊",

    // # 人类实体 (尚未完成)
    Male_DarkTrader01: "人类-黑市商人",
    FireCult_FlameThrower: "人类-Brothers of the Eternal Pyre Martyr",
    Male_Soldier01: "人类-Burly Merc",
    Female_Soldier01: "人类-Expedition Survivor",
    Believer_CrossBow: "人类-Free Pal Alliance Devout",
    Male_Scientist01_LaserRifle: "人类-PAL Genetic Research Unit Executioner",
    PalDealer: "人类-Pal Merchant",
    Police_Handgun: "人类-PIDF Guard",
    Hunter_Bat: "人类-Syndicate Thug (Bat)",
    Hunter_FlameThrower: "人类-Syndicate Cleaner",
    Hunter_Fat_GatlingGun: "人类-Syndicate Crusher",
    Hunter_RocketLauncher: "人类-Syndicate Elite",
    Hunter_Grenade: "人类-Syndicate Grenadier",
    Hunter_Rifle: "人类-Syndicate Gunner",
    Hunter_Shotgun: "人类-Syndicate Hunter",
    Hunter_Handgun: "人类-Syndicate Thug (Handgun)",
    SalesPerson: "人类-流浪商人",
  },
  types: {
    Neutral: "中立",
    Fire: "火",
    Ground: "地",
    Dark: "暗",
    Ice: "冰",
    Grass: "草",
    Dragon: "龙",
    Water: "水",
    Electric: "电",
    None: "无",
  },
  moveset: {
    "Ignis Blast": "烈焰爆破",
    "Spirit Fire": "灵火",
    "Spirit Flame": "灵焰",
    "Daring Flames": "炽焰",
    "Flare Storm": "耀阳暴风",
    "Ignis Rage": "烈火之怒",
    "Fire Ball": "火球",
    "Air Cannon": "气压炮",
    "Fluffy Tackle": "毛茸茸冲撞",
    "Sand Blast": "沙暴",
    "Power Shot": "强力射击",
    Shockwave: "冲击波",
    "Power Bomb": "强力炸弹",
    "Pal Blast": "伙伴爆破",
    "Stone Blast": "石爆",
    "Sand Tornado": "沙暴",
    "Spinning Roundhouse": "回旋踢",
    "Forceful Charge": "猛冲",
    "Ground Smash": "地震轰击",
    "Emperor Slide": "滑铲冲刺",
    "Roly Poly": "翻滚攻击",
    "Reckless Charge": "冲锋",
    "Chicken Rush": "鸡突进",
    Implode: "内爆",
    "Megaton Implode": "超级内爆",
    "Seed Machine Gun": "种子机关枪",
    "Poison Blast": "毒爆",
    "Phantom Peck": "幻影啄击",
    "Antler Uppercut": "鹿角上勾拳",
    "Shell Spin": "螺旋贝壳突进",
    "Gale Claw": "风爪撕裂",
    "Spark Blast": "电光爆裂",
    "Electric Ball": "电气球",
    "Tri-Lightning": "三重闪电弹",
    "Lightning Strike": "闪电闪击",
    "Mystic Whirlwind": "神秘旋风",
    "Acid Rain": "酸雨",
    "Cloud Tempest": "云层风暴",
    "Ignis Slam": "火焰猛撞",
    "Dark Charge": "黑暗冲锋",
    "Blazing Horn": "火焰犄角冲撞",
    "Botanical Smash": "植物粉碎重击",
    "Plasma Tornado": "等离子龙卷风",
    "Fierce Fang": "勇猛撕咬",
    "Ground Pound": "地面重击",
    "2Seed Machine Gun": "双重种子机关枪",
    "Earth Impact": "大地冲击",
    "Crushing Punch": "粉碎重拳",
    "Blast Punch": "爆裂拳",
    "Tornado Attack": "龙卷风攻击",
    "Giga Horn": "超级巨角冲撞",
    "Phoenix Flare": "凤凰烈焰",
    "Freezing Charge": "冰冻冲锋",
    "Crystal Wing": "水晶之翼",
    "Beam Comet": "光束彗星",
    "Kingly Slam": "王者重击",
    "Lock-on Laser": "锁定激光",
    "Cat Press": "猫掌连打",
    "Punch Flurry": "拳击连打",
    "Spinning Lance": "螺旋长枪突刺",
    "Focus Shot": "精准射击",
    Iaigiri: "居合斩",
    "Spear Thrust": "长枪突刺",
    "Muscle Slam": "肌肉重击",
    "Bee Quiet": "安静点",
    Kerauno: "雷霆之怒",
    "Volcanic Burst": "火山爆发",
    "Frost Burst": "霜冻爆裂",
    "Jumping Claw": "跳跃爪击",
    "Rock Lance": "岩石长枪刺",
    "Flare Arrow": "火焰箭矢",
    "Shadow Burst": "暗影爆裂飞弹",
    "Dark Ball": "暗影之球",
    "Nightmare Ball": "梦魇弹",
    "Dark Laser": "暗影激光",
    "Ice Missile": "冰霜导弹",
    "Icicle Cutter": "冰棱斩",
    Iceberg: "冰山",
    "Cryst Breath": "冰晶吐息",
    "Blizzard Spike": "暴风雪刺",
    "Wind Cutter": "风之刃",
    "Grass Tornado": "草之龙卷风",
    "Spine Vine": "藤蔓鞭笞",
    "Solar Blast": "太阳耀斑",
    "Ignis Breath": "火焰吐息",
    "Twin Spears": "双枪刺击",
    "Divine Disaster": "神圣打击",
    "Dragon Cannon": "龙之轰击",
    "Dragon Burst": "龙之爆发",
    "Draconic Breath": "龙息",
    "Dragon Meteor": "龙之流星",
    "Aqua Gun": "水流利刃",
    "Bubble Blast": "泡沫爆裂",
    "Hydro Laser": "水流激光",
    "Hydro Jet": "水流喷射",
    "Aqua Burst": "水流爆裂",
    "Stone Cannon": "岩石大炮",
    "Poison Fog": "毒雾弥漫",
    "Seed Mine": "种子地雷",
    "Lightning Streak": "闪电疾闪",
    "Lightning Bolt": "闪电霹雳",
    "Lightning Claw": "闪电利爪",
    "Hellfire Claw": "烈焰爪",
  },
}

const translate = {
  skillsInfo: [
    {
      CodeName: "UNKNOWN",
      Name: "Unknown",
      Description: " does not exist or is not in our database yet",
      Rating: "Bad",
    },
    {
      CodeName: "NONE",
      Name: "None",
      Description: "The pal has no skill in this slot",
      Rating: "Okay",
    },
    {
      CodeName: "ElementResist_Normal_1_PAL",
      Name: "Abnormal",
      Description: "-10% damage received from Neutral attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementResist_Dark_1_PAL",
      Name: "Cheery",
      Description: "-10% damage received from Dark attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementResist_Dragon_1_PAL",
      Name: "Dragonkiller",
      Description: "-10% damage received from Dragon attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementResist_Ice_1_PAL",
      Name: "Heated Body",
      Description: "-10% damage received from Ice attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementResist_Fire_1_PAL",
      Name: "Suntan Lover",
      Description: "-10% damage received from Fire attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementResist_Leaf_1_PAL",
      Name: "Botanical Barrier",
      Description: "-10% damage received from Grass attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementResist_Earth_1_PAL",
      Name: "Earthquake Resistant",
      Description: "-10% damage received from Ground attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementResist_Thunder_1_PAL",
      Name: "Insulated Body",
      Description: "-10% damage received from Electric attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementResist_Aqua_1_PAL",
      Name: "Waterproof",
      Description: "-10% damage received from Water attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementBoost_Normal_1_PAL",
      Name: "Zen Mind",
      Description: "+10% damage dealt with Neutral attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementBoost_Dark_1_PAL",
      Name: "Veil of Darkness",
      Description: "+10% damage dealt with Dark attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementBoost_Dragon_1_PAL",
      Name: "Blood of the Dragon",
      Description: "+10% damage dealt with Dragon attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementBoost_Ice_1_PAL",
      Name: "Coldblooded",
      Description: "+10% damage dealt with Ice attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementBoost_Fire_1_PAL",
      Name: "Pyromaniac",
      Description: "+10% damage dealt with Fire attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementBoost_Leaf_1_PAL",
      Name: "Fragrant Foliage",
      Description: "+10% damage dealt with Grass attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementBoost_Earth_1_PAL",
      Name: "Power of Gaia",
      Description: "+10% damage dealt with Ground attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementBoost_Thunder_1_PAL",
      Name: "Capacitor",
      Description: "+10% damage dealt with Electric attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementBoost_Aqua_1_PAL",
      Name: "Hydromaniac",
      Description: "+10% damage dealt with Water attacks",
      Rating: "Okay",
    },
    {
      CodeName: "ElementBoost_Normal_2_PAL",
      Name: "Celestial Emperor",
      Description:
        "+20% damage dealt with Neutral attacks; Paladius' signature ability",
      Rating: "Good",
    },
    {
      CodeName: "ElementBoost_Dark_2_PAL",
      Name: "Lord of the Underworld",
      Description:
        "+20% damage dealt with Dark attacks; Necromus' signature ability",
      Rating: "Good",
    },
    {
      CodeName: "ElementBoost_Dragon_2_PAL",
      Name: "Divine Dragon",
      Description:
        "+20% damage dealt with Dragon attacks; Jetragon's signature ability",
      Rating: "Good",
    },
    {
      CodeName: "ElementBoost_Ice_2_PAL",
      Name: "Ice Emperor",
      Description:
        "+20% damage dealt with Ice attacks; Frostallion's signature ability",
      Rating: "Good",
    },
    {
      CodeName: "ElementBoost_Fire_2_PAL",
      Name: "Flame Emperor",
      Description:
        "+20% damage dealt with Fire attacks; Blazamut's signature ability",
      Rating: "Good",
    },
    {
      CodeName: "ElementBoost_Leaf_2_PAL",
      Name: "Spirit Emperor",
      Description:
        "+20% damage dealt with Grass attacks; Lyleen's signature ability",
      Rating: "Good",
    },
    {
      CodeName: "ElementBoost_Earth_2_PAL",
      Name: "Earth Emperor",
      Description:
        "+20% damage dealt with Ground attacks; Anubis' signature ability",
      Rating: "Good",
    },
    {
      CodeName: "ElementBoost_Thunder_2_PAL",
      Name: "Lord of Lightning",
      Description:
        "+20% damage dealt with Electric attacks; Orserk's signature ability",
      Rating: "Good",
    },
    {
      CodeName: "ElementBoost_Aqua_2_PAL",
      Name: "Lord of the Sea",
      Description:
        "+20% damage dealt with Water attacks; Jormuntide's signature ability",
      Rating: "Good",
    },
    {
      CodeName: "PAL_ALLAttack_up1",
      Name: "Brave",
      Description: "+10% to Attack stat",
      Rating: "Okay",
    },
    {
      CodeName: "PAL_ALLAttack_up2",
      Name: "Ferocious",
      Description: "+20% to Attack stat",
      Rating: "Good",
    },
    {
      CodeName: "PAL_ALLAttack_down1",
      Name: "Coward",
      Description: "-10% to Attack stat",
      Rating: "Okay",
    },
    {
      CodeName: "PAL_ALLAttack_down2",
      Name: "Pacifist",
      Description: "-20% to Attack stat",
      Rating: "Bad",
    },
    {
      CodeName: "Deffence_up1",
      Name: "Hard Skin",
      Description: "+10% to Defence stat",
      Rating: "Okay",
    },
    {
      CodeName: "Deffence_up2",
      Name: "Burly Body",
      Description: "+20% to Defence stat",
      Rating: "Good",
    },
    {
      CodeName: "Deffence_down1",
      Name: "Downtrodden",
      Description: "-10% to Defence stat",
      Rating: "Okay",
    },
    {
      CodeName: "Deffence_down2",
      Name: "Brittle",
      Description: "-20% to Defence stat",
      Rating: "Bad",
    },
    {
      CodeName: "TrainerMining_up1",
      Name: "Mine Foreman",
      Description: "+25% to Player mining efficiency",
      Rating: "Good",
    },
    {
      CodeName: "TrainerLogging_up1",
      Name: "Logging Foreman",
      Description: "+25% to Player logging efficiency",
      Rating: "Good",
    },
    {
      CodeName: "TrainerATK_UP_1",
      Name: "Vanguard",
      Description: "+10% to Player attack stat",
      Rating: "Good",
    },
    {
      CodeName: "TrainerWorkSpeed_UP_1",
      Name: "Motivational Leader",
      Description: "+25% to Player move speed",
      Rating: "Good",
    },
    {
      CodeName: "TrainerDEF_UP_1",
      Name: "Stronghold Strategist",
      Description: "+10% to Player defence stat",
      Rating: "Good",
    },
    {
      CodeName: "PAL_Sanity_Down_1",
      Name: "Positive Thinker",
      Description: "Sanity drops 10% slower",
      Rating: "Okay",
    },
    {
      CodeName: "PAL_Sanity_Down_2",
      Name: "Workaholic",
      Description: "Sanity drops 15% slower",
      Rating: "Good",
    },
    {
      CodeName: "PAL_Sanity_Up_1",
      Name: "Unstable",
      Description: "Sanity drops 10% faster",
      Rating: "Okay",
    },
    {
      CodeName: "PAL_Sanity_Up_2",
      Name: "Destructive",
      Description: "Sanity drops 15% faster",
      Rating: "Bad",
    },
    {
      CodeName: "PAL_FullStomach_Down_1",
      Name: "Dainty Eater",
      Description: "Hunger drops 10% slower",
      Rating: "Okay",
    },
    {
      CodeName: "PAL_FullStomach_Down_2",
      Name: "Diet Lover",
      Description: "Chance to lose hunger -15%",
      Rating: "Good",
    },
    {
      CodeName: "PAL_FullStomach_Up_1",
      Name: "Glutton",
      Description: "Hunger drops 10% faster",
      Rating: "Okay",
    },
    {
      CodeName: "PAL_FullStomach_Up_2",
      Name: "Bottomless Stomach",
      Description: "Hunger drops 15% faster",
      Rating: "Bad",
    },
    {
      CodeName: "CraftSpeed_up1",
      Name: "Serious",
      Description: "+20% work speed",
      Rating: "Okay",
    },
    {
      CodeName: "CraftSpeed_up2",
      Name: "Artisan",
      Description: "+50% work speed",
      Rating: "Good",
    },
    {
      CodeName: "CraftSpeed_down1",
      Name: "Clumsy",
      Description: "-10% work speed",
      Rating: "Okay",
    },
    {
      CodeName: "CraftSpeed_down2",
      Name: "Slacker",
      Description: "-30% work speed",
      Rating: "Bad",
    },
    {
      CodeName: "MoveSpeed_up_1",
      Name: "Nimble",
      Description: "+10% movement speed",
      Rating: "Okay",
    },
    {
      CodeName: "MoveSpeed_up_2",
      Name: "Runner",
      Description: "+20% movement speed",
      Rating: "Okay",
    },
    {
      CodeName: "MoveSpeed_up_3",
      Name: "Swift",
      Description: "+30% movement speed",
      Rating: "Good",
    },
    {
      CodeName: "PAL_CorporateSlave",
      Name: "Work Slave",
      Description: "+30% work speed, -30% attack",
      Rating: "Good",
    },
    {
      CodeName: "PAL_rude",
      Name: "Hooligan",
      Description: "+15% attack, -10% work speed",
      Rating: "Okay",
    },
    {
      CodeName: "Noukin",
      Name: "Musclehead",
      Description: "+30% attack, -50% work speed",
      Rating: "Good",
    },
    {
      CodeName: "PAL_oraora",
      Name: "Aggressive",
      Description: "+10% attack, -20% defence",
      Rating: "Okay",
    },
    {
      CodeName: "PAL_conceited",
      Name: "Conceited",
      Description: "+10% work speed, -20% defence",
      Rating: "Okay",
    },
    {
      CodeName: "PAL_masochist",
      Name: "Masochist",
      Description: "+15% defence, -15% attack",
      Rating: "Okay",
    },
    {
      CodeName: "PAL_sadist",
      Name: "Sadist",
      Description: "+15% attack, +15% defence",
      Rating: "Okay",
    },
    {
      CodeName: "Rare",
      Name: "Lucky",
      Description: "+15% attack, +15% work speed",
      Rating: "Good",
    },
    {
      CodeName: "Legend",
      Name: "Legend",
      Description: "+20% attack, +20% defence, +15% move speed",
      Rating: "Good",
    },
  ],
  palsList: [
    {
      CodeName: "Alpaca",
      Name: "Melpaca",
      Type: ["Neutral"],
      Moveset: {
        "Air Cannon": 1,
        "Fluffy Tackle": 7,
        "Sand Blast": 15,
        "Power Shot": 22,
        Shockwave: 30,
        "Power Bomb": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "AmaterasuWolf",
      Name: "Kitsun",
      Type: ["Fire"],
      Moveset: {
        "Ignis Blast": 1,
        "Spirit Fire": 7,
        "Spirit Flame": 15,
        "Daring Flames": 22,
        "Flare Storm": 30,
        "Ignis Rage": 40,
        "Fire Ball": 50,
      },
    },
    {
      CodeName: "Anubis",
      Name: "Anubis",
      Type: ["Ground"],
      Moveset: {
        "Stone Blast": 1,
        "Power Bomb": 7,
        "Sand Tornado": 15,
        "Spinning Roundhouse": 22,
        "Forceful Charge": 30,
        "Ground Smash": 40,
        "Rock Lance": 50,
      },
    },
    {
      CodeName: "Baphomet",
      Name: "Incineram",
      Type: ["Fire", "Dark"],
      Moveset: {
        "Ignis Blast": 1,
        "Spirit Fire": 7,
        "Flare Arrow": 15,
        "Hellfire Claw": 22,
        "Shadow Burst": 30,
        "Fire Ball": 40,
        "Ignis Rage": 50,
      },
    },
    {
      CodeName: "Baphomet_Dark",
      Name: "Incineram Noct",
      Type: ["Dark"],
      Moveset: {
        "Ignis Blast": 1,
        "Spirit Fire": 7,
        "Flare Arrow": 15,
        "Hellfire Claw": 22,
        "Shadow Burst": 30,
        "Fire Ball": 40,
        "Ignis Rage": 50,
      },
    },
    {
      CodeName: "Bastet",
      Name: "Mau",
      Type: ["Dark"],
      Moveset: {
        "Sand Blast": 1,
        "Dark Ball": 7,
        "Shadow Burst": 15,
        "Sand Tornado": 22,
        "Spirit Flame": 30,
        "Nightmare Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "Bastet_Ice",
      Name: "Mau Cryst",
      Type: ["Ice"],
      Moveset: {
        "Ice Missile": 1,
        "Air Cannon": 7,
        "Sand Blast": 15,
        "Icicle Cutter": 22,
        Iceberg: 30,
        "Cryst Breath": 40,
        "Blizzard Spike": 50,
      },
    },
    {
      CodeName: "BerryGoat",
      Name: "Caprity",
      Type: ["Grass"],
      Moveset: {
        "Wind Cutter": 1,
        "Air Cannon": 7,
        "Sand Blast": 15,
        "Power Shot": 22,
        "Grass Tornado": 30,
        "Spine Vine": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "BirdDragon",
      Name: "Vanwyrm",
      Type: ["Fire", "Dark"],
      Moveset: {
        "Air Cannon": 1,
        "Ignis Blast": 7,
        "Spirit Fire": 15,
        "Ignis Breath": 22,
        "Nightmare Ball": 30,
        "Fire Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "BirdDragon_Ice",
      Name: "Vanwyrm Cryst",
      Type: ["Ice", "Dark"],
      Moveset: {
        "Air Cannon": 1,
        "Ice Missile": 7,
        "Icicle Cutter": 15,
        "Cryst Breath": 22,
        "Nightmare Ball": 30,
        "Blizzard Spike": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "BlackCentaur",
      Name: "Necromus",
      Type: ["Dark"],
      Moveset: {
        "Shadow Burst": 1,
        "Spirit Fire": 7,
        "Spirit Flame": 15,
        "Nightmare Ball": 22,
        "Rock Lance": 30,
        "Twin Spears": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "BlackGriffon",
      Name: "Shadowbeak",
      Type: ["Dark"],
      Moveset: {
        "Air Cannon": 1,
        "Dark Ball": 7,
        "Shadow Burst": 15,
        "Spirit Flame": 22,
        "Nightmare Ball": 30,
        "Divine Disaster": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "BlackMetalDragon",
      Name: "Astegon",
      Type: ["Dragon", "Dark"],
      Moveset: {
        "Dragon Cannon": 1,
        "Spirit Flame": 7,
        "Dragon Burst": 15,
        "Nightmare Ball": 22,
        "Draconic Breath": 30,
        "Dark Laser": 40,
        "Dragon Meteor": 50,
      },
    },
    {
      CodeName: "BlueDragon",
      Name: "Azurobe",
      Type: ["Water", "Dragon"],
      Moveset: {
        "Aqua Gun": 1,
        "Dragon Cannon": 7,
        "Bubble Blast": 15,
        "Dragon Burst": 22,
        "Draconic Breath": 30,
        "Hydro Laser": 40,
        "Dragon Meteor": 50,
      },
    },
    {
      CodeName: "BluePlatypus",
      Name: "Fuack",
      Type: ["Water"],
      Moveset: {
        "Aqua Gun": 1,
        "Power Shot": 7,
        "Hydro Jet": 15,
        "Ice Missile": 22,
        "Bubble Blast": 30,
        "Aqua Burst": 40,
        "Hydro Laser": 50,
      },
    },
    {
      CodeName: "Boar",
      Name: "Rushoar",
      Type: ["Ground"],
      Moveset: {
        "Reckless Charge": 1,
        "Sand Blast": 7,
        "Power Shot": 15,
        "Stone Blast": 22,
        "Power Bomb": 30,
        "Rock Lance": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "CaptainPenguin",
      Name: "Penking",
      Type: ["Water", "Ice"],
      Moveset: {
        "Aqua Gun": 1,
        Iceberg: 7,
        "Emperor Slide": 15,
        "Cryst Breath": 22,
        "Aqua Burst": 30,
        "Blizzard Spike": 40,
        "Hydro Laser": 50,
      },
    },
    {
      CodeName: "Carbunclo",
      Name: "Lifmunk",
      Type: ["Grass"],
      Moveset: {
        "Wind Cutter": 1,
        "Air Cannon": 7,
        "Power Shot": 15,
        "Seed Machine Gun": 22,
        "Power Bomb": 30,
        "Spine Vine": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "CatBat",
      Name: "Tombat",
      Type: ["Dark"],
      Moveset: {
        "Air Cannon": 1,
        "Poison Blast": 7,
        "Dark Ball": 15,
        "Shadow Burst": 22,
        "Spirit Flame": 30,
        "Nightmare Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "CatMage",
      Name: "Katress",
      Type: ["Dark"],
      Moveset: {
        "Ignis Blast": 1,
        "Dark Ball": 7,
        "Flare Arrow": 15,
        "Shadow Burst": 22,
        "Spirit Flame": 30,
        "Nightmare Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "CatVampire",
      Name: "Felbat",
      Type: ["Dark"],
      Moveset: {
        "Poison Blast": 1,
        "Dark Ball": 7,
        "Shadow Burst": 15,
        "Spirit Flame": 22,
        "Nightmare Ball": 30,
        "Ignis Rage": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "ChickenPal",
      Name: "Chikipi",
      Type: ["Neutral"],
      Moveset: {
        "Chicken Rush": 1,
        "Air Cannon": 7,
        "Power Shot": 15,
        Implode: 22,
        "Grass Tornado": 30,
        "Sand Tornado": 40,
        "Flare Storm": 50,
      },
    },
    {
      CodeName: "ColorfulBird",
      Name: "Tocotoco",
      Type: ["Neutral"],
      Moveset: {
        Implode: 1,
        "Air Cannon": 7,
        "Power Shot": 15,
        "Megaton Implode": 22,
        "Sand Tornado": 30,
        "Power Bomb": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "CowPal",
      Name: "Mozzarina",
      Type: ["Neutral"],
      Moveset: {
        "Power Shot": 1,
        "Sand Blast": 7,
        "Air Cannon": 15,
        "Stone Blast": 22,
        "Stone Cannon": 30,
        "Power Bomb": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "CuteButterfly",
      Name: "Cinnamoth",
      Type: ["Grass"],
      Moveset: {
        "Air Cannon": 1,
        "Wind Cutter": 7,
        "Poison Fog": 15,
        "Sand Tornado": 22,
        "Seed Mine": 30,
        "Grass Tornado": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "CuteFox",
      Name: "Vixy",
      Type: ["Neutral"],
      Moveset: {
        "Air Cannon": 1,
        "Sand Blast": 7,
        "Power Shot": 15,
        "Wind Cutter": 22,
        "Seed Machine Gun": 30,
        "Power Bomb": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "CuteMole",
      Name: "Fuddler",
      Type: ["Ground"],
      Moveset: {
        "Sand Blast": 1,
        "Power Shot": 7,
        "Stone Blast": 15,
        "Stone Cannon": 22,
        "Power Bomb": 30,
        "Sand Tornado": 40,
        "Rock Lance": 50,
      },
    },
    {
      CodeName: "DarkCrow",
      Name: "Cawgnito",
      Type: ["Dark"],
      Moveset: {
        "Air Cannon": 1,
        "Dark Ball": 7,
        "Phantom Peck": 15,
        "Shadow Burst": 22,
        "Spirit Flame": 30,
        "Nightmare Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "DarkScorpion",
      Name: "Menasting",
      Type: ["Dark", "Ground"],
      Moveset: {
        "Sand Blast": 1,
        "Poison Blast": 7,
        "Shadow Burst": 15,
        "Stone Cannon": 22,
        "Nightmare Ball": 30,
        "Rock Lance": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "Deer",
      Name: "Eikthyrdeer",
      Type: ["Neutral"],
      Moveset: {
        "Power Shot": 1,
        "Antler Uppercut": 7,
        "Stone Blast": 15,
        "Stone Cannon": 22,
        "Power Bomb": 30,
        "Rock Lance": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "Deer_Ground",
      Name: "Eikthyrdeer Terra",
      Type: ["Ground"],
      Moveset: {
        "Power Shot": 1,
        "Antler Uppercut": 7,
        "Stone Blast": 15,
        "Stone Cannon": 22,
        "Power Bomb": 30,
        "Sand Tornado": 40,
        "Rock Lance": 50,
      },
    },
    {
      CodeName: "DreamDemon",
      Name: "Daedream",
      Type: ["Dark"],
      Moveset: {
        "Dark Ball": 1,
        "Poison Blast": 7,
        "Shadow Burst": 15,
        "Cryst Breath": 22,
        "Spirit Flame": 30,
        "Nightmare Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "DrillGame",
      Name: "Digtoise",
      Type: ["Ground"],
      Moveset: {
        "Aqua Gun": 1,
        "Stone Blast": 7,
        "Shell Spin": 15,
        "Stone Cannon": 22,
        "Sand Tornado": 30,
        "Aqua Burst": 40,
        "Rock Lance": 50,
      },
    },
    {
      CodeName: "Eagle",
      Name: "Galeclaw",
      Type: ["Neutral"],
      Moveset: {
        "Gale Claw": 1,
        "Air Cannon": 7,
        "Sand Blast": 15,
        "Wind Cutter": 22,
        "Sand Tornado": 30,
        "Grass Tornado": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "ElecCat",
      Name: "Sparkit",
      Type: ["Electric"],
      Moveset: {
        "Spark Blast": 1,
        "Sand Blast": 7,
        Shockwave: 15,
        "Electric Ball": 22,
        "Tri-Lightning": 30,
        "Lightning Streak": 40,
        "Lightning Bolt": 50,
      },
    },
    {
      CodeName: "ElecPanda",
      Name: "Grizzbolt",
      Type: ["Electric"],
      Moveset: {
        "Spark Blast": 1,
        Shockwave: 7,
        "Lightning Claw": 15,
        "Lightning Streak": 22,
        "Tri-Lightning": 30,
        "Lightning Strike": 40,
        "Lightning Bolt": 50,
      },
    },
    {
      CodeName: "FairyDragon",
      Name: "Elphidran",
      Type: ["Dragon"],
      Moveset: {
        "Dragon Cannon": 1,
        "Dragon Burst": 7,
        "Flare Arrow": 15,
        "Mystic Whirlwind": 22,
        "Draconic Breath": 30,
        "Pal Blast": 40,
        "Dragon Meteor": 50,
      },
    },
    {
      CodeName: "FairyDragon_Water",
      Name: "Elphidran Aqua",
      Type: ["Dragon", "Water"],
      Moveset: {
        "Aqua Gun": 1,
        "Dragon Cannon": 7,
        "Dragon Burst": 15,
        "Mystic Whirlwind": 22,
        "Acid Rain": 30,
        "Hydro Laser": 40,
        "Dragon Meteor": 50,
      },
    },
    {
      CodeName: "FengyunDeeper",
      Name: "Fenglope",
      Type: ["Neutral"],
      Moveset: {
        "Air Cannon": 1,
        "Aqua Gun": 7,
        "Cloud Tempest": 15,
        "Acid Rain": 22,
        "Aqua Burst": 30,
        "Blizzard Spike": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "FireKirin",
      Name: "Pyrin",
      Type: ["Fire"],
      Moveset: {
        "Sand Blast": 1,
        "Ignis Blast": 7,
        "Spirit Fire": 15,
        "Flare Arrow": 22,
        "Ignis Slam": 30,
        "Ignis Rage": 40,
        "Fire Ball": 50,
      },
    },
    {
      CodeName: "FireKirin_Dark",
      Name: "Pyrin Noct",
      Type: ["Fire", "Dark"],
      Moveset: {
        "Ignis Blast": 1,
        "Shadow Burst": 7,
        "Ignis Breath": 15,
        "Spirit Flame": 22,
        "Dark Charge": 30,
        "Ignis Rage": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "FlameBambi",
      Name: "Rooby",
      Type: ["Fire"],
      Moveset: {
        "Ignis Blast": 1,
        "Power Shot": 7,
        "Spirit Fire": 15,
        "Flare Arrow": 22,
        "Flare Storm": 30,
        "Ignis Rage": 40,
        "Fire Ball": 50,
      },
    },
    {
      CodeName: "FlameBuffalo",
      Name: "Arsox",
      Type: ["Fire"],
      Moveset: {
        "Ignis Blast": 1,
        "Blazing Horn": 7,
        "Spirit Fire": 15,
        "Flare Arrow": 22,
        "Ignis Breath": 30,
        "Ignis Rage": 40,
        "Fire Ball": 50,
      },
    },
    {
      CodeName: "FlowerDinosaur",
      Name: "Dinossom",
      Type: ["Grass", "Dragon"],
      Moveset: {
        "Wind Cutter": 1,
        "Botanical Smash": 7,
        "Dragon Burst": 15,
        "Seed Mine": 22,
        "Draconic Breath": 30,
        "Spine Vine": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "FlowerDinosaur_Electric",
      Name: "Dinossom Lux",
      Type: ["Electric", "Dragon"],
      Moveset: {
        Shockwave: 1,
        "Plasma Tornado": 7,
        "Botanical Smash": 15,
        "Draconic Breath": 22,
        "Tri-Lightning": 30,
        "Lightning Strike": 40,
        "Lightning Bolt": 50,
      },
    },
    {
      CodeName: "FlowerDoll",
      Name: "Petallia",
      Type: ["Grass"],
      Moveset: {
        "Wind Cutter": 1,
        "Aqua Gun": 7,
        "Seed Machine Gun": 15,
        "Bubble Blast": 22,
        "Grass Tornado": 30,
        "Spine Vine": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "FlowerRabbit",
      Name: "Flopie",
      Type: ["Grass"],
      Moveset: {
        "Wind Cutter": 1,
        "Air Cannon": 7,
        "Hydro Jet": 15,
        "Seed Machine Gun": 22,
        "Bubble Blast": 30,
        "Grass Tornado": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "FlyingManta",
      Name: "Celaray",
      Type: ["Water"],
      Moveset: {
        "Hydro Jet": 1,
        "Aqua Gun": 7,
        "Power Shot": 15,
        "Bubble Blast": 22,
        "Seed Machine Gun": 30,
        "Aqua Burst": 40,
        "Hydro Laser": 50,
      },
    },
    {
      CodeName: "FoxMage",
      Name: "Wixen",
      Type: ["Fire"],
      Moveset: {
        "Ignis Blast": 1,
        "Spirit Fire": 7,
        "Flare Arrow": 15,
        "Spirit Flame": 22,
        "Flare Storm": 30,
        "Fire Ball": 40,
        "Dragon Meteor": 50,
      },
    },
    {
      CodeName: "Ganesha",
      Name: "Teafant",
      Type: ["Water"],
      Moveset: {
        "Aqua Gun": 1,
        "Hydro Jet": 7,
        "Sand Blast": 15,
        "Bubble Blast": 22,
        "Acid Rain": 30,
        "Aqua Burst": 40,
        "Hydro Laser": 50,
      },
    },
    {
      CodeName: "Garm",
      Name: "Direhowl",
      Type: ["Neutral"],
      Moveset: {
        "Fierce Fang": 1,
        "Sand Blast": 7,
        "Air Cannon": 15,
        "Power Shot": 22,
        "Ignis Blast": 30,
        "Power Bomb": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "GhostBeast",
      Name: "Maraith",
      Type: ["Dark"],
      Moveset: {
        "Ignis Blast": 1,
        "Dark Ball": 7,
        "Flare Arrow": 15,
        "Shadow Burst": 22,
        "Spirit Flame": 30,
        "Nightmare Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "Gorilla",
      Name: "Gorirat",
      Type: ["Neutral"],
      Moveset: {
        "Sand Blast": 1,
        "Power Shot": 7,
        "Ground Pound": 15,
        "Stone Blast": 22,
        "Seed Machine Gun": 30,
        "Power Bomb": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "GrassMammoth",
      Name: "Mammorest",
      Type: ["Grass"],
      Moveset: {
        "Sand Blast": 1,
        "Seed Machine Gun": 7,
        "Power Bomb": 15,
        "Grass Tornado": 22,
        "Earth Impact": 30,
        "Spine Vine": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "GrassMammoth_Ice",
      Name: "Mammorest Cryst",
      Type: ["Ice"],
      Moveset: {
        "Stone Cannon": 1,
        "Icicle Cutter": 7,
        "Power Bomb": 15,
        Iceberg: 22,
        "Earth Impact": 30,
        "Cryst Breath": 40,
        "Blizzard Spike": 50,
      },
    },
    {
      CodeName: "GrassPanda",
      Name: "Mossanda",
      Type: ["Grass"],
      Moveset: {
        "Power Shot": 1,
        "Seed Machine Gun": 7,
        "Stone Cannon": 15,
        "Crushing Punch": 22,
        "Seed Mine": 30,
        "Spine Vine": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "GrassPanda_Electric",
      Name: "Mossanda Lux",
      Type: ["Electric"],
      Moveset: {
        "Spark Blast": 1,
        Shockwave: 7,
        "Lightning Streak": 15,
        "Blast Punch": 22,
        "Tri-Lightning": 30,
        "Lightning Strike": 40,
        "Lightning Bolt": 50,
      },
    },
    {
      CodeName: "GrassRabbitMan",
      Name: "Verdash",
      Type: ["Grass"],
      Moveset: {
        "Wind Cutter": 1,
        "Stone Cannon": 7,
        "Seed Machine Gun": 15,
        "Stone Blast": 22,
        "Grass Tornado": 30,
        "Spine Vine": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "HadesBird",
      Name: "Helzephyr",
      Type: ["Dark"],
      Moveset: {
        "Spirit Fire": 1,
        "Dark Ball": 7,
        "Shadow Burst": 15,
        "Flare Storm": 22,
        "Spirit Flame": 30,
        "Nightmare Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "HawkBird",
      Name: "Nitewing",
      Type: ["Neutral"],
      Moveset: {
        "Air Cannon": 1,
        "Tornado Attack": 7,
        "Wind Cutter": 15,
        "Power Bomb": 22,
        "Sand Tornado": 30,
        "Grass Tornado": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "Hedgehog",
      Name: "Jolthog",
      Type: ["Electric"],
      Moveset: {
        Shockwave: 1,
        "Power Shot": 7,
        "Electric Ball": 15,
        "Power Bomb": 22,
        "Tri-Lightning": 30,
        "Lightning Streak": 40,
        "Lightning Bolt": 50,
      },
    },
    {
      CodeName: "Hedgehog_Ice",
      Name: "Jolthog Cryst",
      Type: ["Ice"],
      Moveset: {
        "Ice Missile": 1,
        "Power Shot": 7,
        Iceberg: 15,
        "Power Bomb": 22,
        "Icicle Cutter": 30,
        "Cryst Breath": 40,
        "Blizzard Spike": 50,
      },
    },
    {
      CodeName: "HerculesBeetle",
      Name: "Warsect",
      Type: ["Ground", "Grass"],
      Moveset: {
        "Wind Cutter": 1,
        "Seed Machine Gun": 7,
        "Stone Blast": 15,
        "Stone Cannon": 22,
        "Giga Horn": 30,
        "Rock Lance": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "Horus",
      Name: "Faleris",
      Type: ["Fire"],
      Moveset: {
        "Ignis Blast": 1,
        "Flare Arrow": 7,
        "Spirit Fire": 15,
        "Ignis Breath": 22,
        "Phoenix Flare": 30,
        "Ignis Rage": 40,
        "Fire Ball": 50,
      },
    },
    {
      CodeName: "IceDeer",
      Name: "Reindrix",
      Type: ["Ice"],
      Moveset: {
        "Air Cannon": 1,
        "Ice Missile": 7,
        "Icicle Cutter": 15,
        "Freezing Charge": 22,
        Iceberg: 30,
        "Cryst Breath": 40,
        "Blizzard Spike": 50,
      },
    },
    {
      CodeName: "IceFox",
      Name: "Foxcicle",
      Type: ["Ice"],
      Moveset: {
        "Air Cannon": 1,
        "Ice Missile": 7,
        "Icicle Cutter": 15,
        "Spirit Flame": 22,
        Iceberg: 30,
        "Cryst Breath": 40,
        "Blizzard Spike": 50,
      },
    },
    {
      CodeName: "IceHorse",
      Name: "Frostallion",
      Type: ["Ice"],
      Moveset: {
        "Air Cannon": 1,
        "Ice Missile": 7,
        "Icicle Cutter": 15,
        Iceberg: 22,
        "Crystal Wing": 30,
        "Cryst Breath": 40,
        "Blizzard Spike": 50,
      },
    },
    {
      CodeName: "IceHorse_Dark",
      Name: "Frostallion Noct",
      Type: ["Dark"],
      Moveset: {
        "Air Cannon": 1,
        "Dark Ball": 7,
        "Shadow Burst": 15,
        "Spirit Flame": 22,
        "Crystal Wing": 30,
        "Nightmare Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "JetDragon",
      Name: "Jetragon",
      Type: ["Dragon"],
      Moveset: {
        "Spirit Fire": 1,
        "Dragon Burst": 7,
        "Flare Storm": 15,
        "Draconic Breath": 22,
        "Beam Comet": 30,
        "Fire Ball": 40,
        "Dragon Meteor": 50,
      },
    },
    {
      CodeName: "Kelpie",
      Name: "Kelpsea",
      Type: ["Water"],
      Moveset: {
        "Hydro Jet": 1,
        "Dragon Cannon": 7,
        "Aqua Gun": 15,
        "Bubble Blast": 22,
        "Power Bomb": 30,
        "Aqua Burst": 40,
        "Hydro Laser": 50,
      },
    },
    {
      CodeName: "Kelpie_Fire",
      Name: "Kelpsea Ignis",
      Type: ["Fire"],
      Moveset: {
        "Ignis Blast": 1,
        "Dragon Cannon": 7,
        "Spirit Fire": 15,
        "Flare Arrow": 22,
        "Dragon Burst": 30,
        "Ignis Breath": 40,
        "Fire Ball": 50,
      },
    },
    {
      CodeName: "KingAlpaca",
      Name: "Kingpaca",
      Type: ["Neutral"],
      Moveset: {
        "Sand Blast": 1,
        "Power Shot": 7,
        "Power Bomb": 15,
        "Kingly Slam": 22,
        "Tri-Lightning": 30,
        "Rock Lance": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "KingAlpaca_Ice",
      Name: "Ice Kingpaca",
      Type: ["Ice"],
      Moveset: {
        "Ice Missile": 1,
        "Icicle Cutter": 7,
        Iceberg: 15,
        "Kingly Slam": 22,
        "Cryst Breath": 30,
        "Aqua Burst": 40,
        "Blizzard Spike": 50,
      },
    },
    {
      CodeName: "KingBahamut",
      Name: "Blazamut",
      Type: ["Fire"],
      Moveset: {
        "Power Shot": 1,
        "Ignis Blast": 7,
        "Stone Blast": 15,
        "Ignis Breath": 22,
        "Ignis Rage": 30,
        "Fire Ball": 40,
        "Rock Lance": 50,
      },
    },
    {
      CodeName: "Kirin",
      Name: "Univolt",
      Type: ["Electric"],
      Moveset: {
        "Spark Blast": 1,
        Shockwave: 7,
        "Lock-on Laser": 15,
        "Lightning Streak": 22,
        "Tri-Lightning": 30,
        "Lightning Strike": 40,
        "Lightning Bolt": 50,
      },
    },
    {
      CodeName: "Kitsunebi",
      Name: "Foxparks",
      Type: ["Fire"],
      Moveset: {
        "Ignis Blast": 1,
        "Sand Blast": 7,
        "Spirit Fire": 15,
        "Flare Arrow": 22,
        "Ignis Breath": 30,
        "Spirit Flame": 40,
        "Fire Ball": 50,
      },
    },
    {
      CodeName: "LavaGirl",
      Name: "Flambelle",
      Type: ["Fire"],
      Moveset: {
        "Ignis Blast": 1,
        "Spirit Fire": 7,
        "Flare Arrow": 15,
        "Spirit Flame": 22,
        "Flare Storm": 30,
        "Ignis Rage": 40,
        "Fire Ball": 50,
      },
    },
    {
      CodeName: "LazyCatfish",
      Name: "Dumud",
      Type: ["Ground"],
      Moveset: {},
    },
    {
      CodeName: "LazyDragon",
      Name: "Relaxaurus",
      Type: ["Dragon", "Water"],
      Moveset: {
        "Dragon Cannon": 1,
        "Aqua Gun": 7,
        "Dragon Burst": 15,
        "Bubble Blast": 22,
        "Draconic Breath": 30,
        "Aqua Burst": 40,
        "Dragon Meteor": 50,
      },
    },
    {
      CodeName: "LazyDragon_Electric",
      Name: "Relaxaurus Lux",
      Type: ["Dragon", "Electric"],
      Moveset: {
        "Spark Blast": 1,
        "Dragon Cannon": 7,
        Shockwave: 15,
        "Lightning Streak": 22,
        "Draconic Breath": 30,
        "Lightning Strike": 40,
        "Lightning Bolt": 50,
      },
    },
    {
      CodeName: "LilyQueen",
      Name: "Lyleen",
      Type: ["Grass"],
      Moveset: {
        "Wind Cutter": 1,
        "Seed Machine Gun": 7,
        "Seed Mine": 15,
        "Aqua Burst": 22,
        "Grass Tornado": 30,
        "Spine Vine": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "LilyQueen_Dark",
      Name: "Lyleen Noct",
      Type: ["Dark"],
      Moveset: {
        "Dark Ball": 1,
        "Icicle Cutter": 7,
        "Shadow Burst": 15,
        "Cryst Breath": 22,
        "Nightmare Ball": 30,
        "Blizzard Spike": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "LittleBriarRose",
      Name: "Bristla",
      Type: ["Grass"],
      Moveset: {
        "Wind Cutter": 1,
        "Seed Machine Gun": 7,
        "Ice Missile": 15,
        "Grass Tornado": 22,
        Iceberg: 30,
        "Spine Vine": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "LizardMan",
      Name: "Leezpunk",
      Type: ["Dark"],
      Moveset: {
        "Poison Blast": 1,
        "Dark Ball": 7,
        "Shadow Burst": 15,
        "Spirit Flame": 22,
        "Nightmare Ball": 30,
        "Ignis Breath": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "LizardMan_Fire",
      Name: "Leezpunk Ignis",
      Type: ["Fire"],
      Moveset: {
        "Ignis Blast": 1,
        "Poison Blast": 7,
        "Spirit Fire": 15,
        "Ignis Breath": 22,
        "Flare Storm": 30,
        "Ignis Rage": 40,
        "Fire Ball": 50,
      },
    },
    {
      CodeName: "Manticore",
      Name: "Blazehowl",
      Type: ["Fire"],
      Moveset: {
        "Ignis Blast": 1,
        "Power Shot": 7,
        "Flare Arrow": 15,
        "Ignis Breath": 22,
        "Ignis Rage": 30,
        "Fire Ball": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "Manticore_Dark",
      Name: "Blazehowl Noct",
      Type: ["Fire", "Dark"],
      Moveset: {
        "Shadow Burst": 1,
        "Flare Arrow": 7,
        "Ignis Breath": 15,
        "Spirit Flame": 22,
        "Ignis Rage": 30,
        "Fire Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "Monkey",
      Name: "Tanzee",
      Type: ["Grass"],
      Moveset: {
        "Wind Cutter": 1,
        "Sand Blast": 7,
        "Seed Machine Gun": 15,
        "Seed Mine": 22,
        "Stone Cannon": 30,
        "Grass Tornado": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "MopBaby",
      Name: "Swee",
      Type: ["Ice"],
      Moveset: {
        "Air Cannon": 1,
        "Ice Missile": 7,
        "Icicle Cutter": 15,
        "Power Bomb": 22,
        Iceberg: 30,
        "Cryst Breath": 40,
        "Blizzard Spike": 50,
      },
    },
    {
      CodeName: "MopKing",
      Name: "Sweepa",
      Type: ["Ice"],
      Moveset: {
        "Power Shot": 1,
        "Ice Missile": 7,
        "Icicle Cutter": 15,
        Iceberg: 22,
        "Cryst Breath": 30,
        "Pal Blast": 40,
        "Blizzard Spike": 50,
      },
    },
    {
      CodeName: "Mutant",
      Name: "Lunaris",
      Type: ["Neutral"],
      Moveset: {
        "Air Cannon": 1,
        "Power Shot": 7,
        "Icicle Cutter": 15,
        "Plasma Tornado": 22,
        "Power Bomb": 30,
        "Blizzard Spike": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "NaughtyCat",
      Name: "Grintale",
      Type: ["Neutral"],
      Moveset: {
        "Sand Blast": 1,
        "Power Shot": 7,
        "Cat Press": 15,
        "Stone Blast": 22,
        "Stone Cannon": 30,
        "Power Bomb": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "NegativeKoala",
      Name: "Depresso",
      Type: ["Dark"],
      Moveset: {
        "Poison Blast": 1,
        "Sand Blast": 7,
        "Dark Ball": 15,
        "Ice Missile": 22,
        "Shadow Burst": 30,
        "Nightmare Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "NegativeOctopus",
      Name: "Killamari",
      Type: ["Dark"],
      Moveset: {
        "Hydro Jet": 1,
        "Poison Blast": 7,
        "Dark Ball": 15,
        "Shadow Burst": 22,
        "Acid Rain": 30,
        "Nightmare Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "NightFox",
      Name: "Nox",
      Type: ["Dark"],
      Moveset: {
        "Air Cannon": 1,
        "Dark Ball": 7,
        "Shadow Burst": 15,
        "Power Bomb": 22,
        "Spirit Flame": 30,
        "Nightmare Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "Penguin",
      Name: "Pengullet",
      Type: ["Water", "Ice"],
      Moveset: {
        "Ice Missile": 1,
        "Hydro Jet": 7,
        "Aqua Gun": 15,
        "Icicle Cutter": 22,
        Iceberg: 30,
        "Blizzard Spike": 40,
        "Hydro Laser": 50,
      },
    },
    {
      CodeName: "PinkCat",
      Name: "Cattiva",
      Type: ["Neutral"],
      Moveset: {
        "Punch Flurry": 1,
        "Air Cannon": 7,
        "Sand Blast": 15,
        "Power Shot": 22,
        "Wind Cutter": 30,
        "Seed Machine Gun": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "PinkLizard",
      Name: "Lovander",
      Type: ["Neutral"],
      Moveset: {
        "Power Shot": 1,
        "Poison Blast": 7,
        "Shadow Burst": 15,
        "Acid Rain": 22,
        "Power Bomb": 30,
        Implode: 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "PinkRabbit",
      Name: "Ribbuny",
      Type: ["Neutral"],
      Moveset: {
        "Air Cannon": 1,
        "Power Shot": 7,
        "Ice Missile": 15,
        "Blizzard Spike": 22,
        "Power Bomb": 30,
        Iceberg: 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "PlantSlime",
      Name: "Gumoss",
      Type: ["Grass", "Ground"],
      Moveset: {
        "Sand Blast": 1,
        "Wind Cutter": 7,
        "Stone Blast": 15,
        "Seed Machine Gun": 22,
        "Seed Mine": 30,
        "Sand Tornado": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "QueenBee",
      Name: "Elizabee",
      Type: ["Grass"],
      Moveset: {
        "Air Cannon": 1,
        "Wind Cutter": 7,
        "Poison Blast": 15,
        "Spinning Lance": 22,
        "Grass Tornado": 30,
        "Spine Vine": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "RaijinDaughter",
      Name: "Dazzi",
      Type: ["Electric"],
      Moveset: {
        "Air Cannon": 1,
        Shockwave: 7,
        "Acid Rain": 15,
        "Lightning Streak": 22,
        "Tri-Lightning": 30,
        "Lightning Strike": 40,
        "Lightning Bolt": 50,
      },
    },
    {
      CodeName: "RedArmorBird",
      Name: "Ragnahawk",
      Type: ["Fire"],
      Moveset: {
        "Air Cannon": 1,
        "Spirit Fire": 7,
        "Flare Arrow": 15,
        "Sand Tornado": 22,
        "Flare Storm": 30,
        "Ignis Breath": 40,
        "Fire Ball": 50,
      },
    },
    {
      CodeName: "RobinHood",
      Name: "Robinquill",
      Type: ["Grass"],
      Moveset: {
        "Wind Cutter": 1,
        "Power Shot": 7,
        "Focus Shot": 15,
        "Seed Mine": 22,
        "Grass Tornado": 30,
        "Spine Vine": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "RobinHood_Ground",
      Name: "Robinquill Terra",
      Type: ["Grass", "Ground"],
      Moveset: {
        "Sand Blast": 1,
        "Wind Cutter": 7,
        "Focus Shot": 15,
        "Stone Blast": 22,
        "Sand Tornado": 30,
        "Solar Blast": 40,
        "Rock Lance": 50,
      },
    },
    {
      CodeName: "Ronin",
      Name: "Bushi",
      Type: ["Fire"],
      Moveset: {
        "Ignis Blast": 1,
        "Wind Cutter": 7,
        "Icicle Cutter": 15,
        Iaigiri: 22,
        "Ignis Breath": 30,
        "Lightning Strike": 40,
        "Ignis Rage": 50,
      },
    },
    {
      CodeName: "SaintCentaur",
      Name: "Paladius",
      Type: ["Neutral"],
      Moveset: {
        "Power Shot": 1,
        "Ice Missile": 7,
        Iceberg: 15,
        "Power Bomb": 22,
        "Blizzard Spike": 30,
        "Spear Thrust": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "SakuraSaurus",
      Name: "Broncherry",
      Type: ["Grass"],
      Moveset: {
        "Wind Cutter": 1,
        "Sand Blast": 7,
        "Muscle Slam": 15,
        "Seed Mine": 22,
        "Grass Tornado": 30,
        "Spine Vine": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "SakuraSaurus_Water",
      Name: "Broncherry Aqua",
      Type: ["Grass", "Water"],
      Moveset: {
        "Aqua Gun": 1,
        "Bubble Blast": 7,
        "Muscle Slam": 15,
        "Seed Mine": 22,
        "Spine Vine": 30,
        "Aqua Burst": 40,
        "Hydro Laser": 50,
      },
    },
    {
      CodeName: "Serpent",
      Name: "Surfent",
      Type: ["Water"],
      Moveset: {
        "Hydro Jet": 1,
        "Dragon Cannon": 7,
        "Aqua Gun": 15,
        "Bubble Blast": 22,
        "Dragon Burst": 30,
        "Draconic Breath": 40,
        "Hydro Laser": 50,
      },
    },
    {
      CodeName: "Serpent_Ground",
      Name: "Surfent Terra",
      Type: ["Ground"],
      Moveset: {
        "Sand Blast": 1,
        "Dragon Cannon": 7,
        "Stone Blast": 15,
        "Stone Cannon": 22,
        "Sand Tornado": 30,
        "Draconic Breath": 40,
        "Rock Lance": 50,
      },
    },
    {
      CodeName: "SharkKid",
      Name: "Gobfin",
      Type: ["Water"],
      Moveset: {
        "Hydro Jet": 1,
        "Power Shot": 7,
        "Aqua Gun": 15,
        "Bubble Blast": 22,
        "Icicle Cutter": 30,
        "Aqua Burst": 40,
        "Hydro Laser": 50,
      },
    },
    {
      CodeName: "SharkKid_Fire",
      Name: "Gobfin Ignis",
      Type: ["Fire"],
      Moveset: {
        "Ignis Blast": 1,
        "Power Shot": 7,
        "Spirit Fire": 15,
        "Flare Arrow": 22,
        "Lightning Streak": 30,
        "Fire Ball": 40,
        "Ignis Rage": 50,
      },
    },
    {
      CodeName: "Sheepball",
      Name: "Lamball",
      Type: ["Neutral"],
      Moveset: {
        "Roly Poly": 1,
        "Air Cannon": 7,
        "Power Shot": 15,
        Implode: 22,
        "Electric Ball": 30,
        "Power Bomb": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "SkyDragon",
      Name: "Quivern",
      Type: ["Dragon"],
      Moveset: {
        "Dragon Cannon": 1,
        "Spirit Fire": 7,
        "Acid Rain": 15,
        "Draconic Breath": 22,
        "Grass Tornado": 30,
        "Aqua Burst": 40,
        "Dragon Meteor": 50,
      },
    },
    {
      CodeName: "SoldierBee",
      Name: "Beegarde",
      Type: ["Grass"],
      Moveset: {
        "Air Cannon": 1,
        "Wind Cutter": 7,
        "Bee Quiet": 15,
        "Poison Blast": 22,
        "Acid Rain": 30,
        "Grass Tornado": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "Suzaku",
      Name: "Suzaku",
      Type: ["Fire"],
      Moveset: {
        "Air Cannon": 1,
        "Ignis Blast": 7,
        "Spirit Fire": 15,
        "Flare Arrow": 22,
        "Ignis Breath": 30,
        "Flare Storm": 40,
        "Fire Ball": 50,
      },
    },
    {
      CodeName: "Suzaku_Water",
      Name: "Suzaku Aqua",
      Type: ["Water"],
      Moveset: {
        "Hydro Jet": 1,
        "Ice Missile": 7,
        "Aqua Gun": 15,
        "Cryst Breath": 22,
        "Aqua Burst": 30,
        "Blizzard Spike": 40,
        "Hydro Laser": 50,
      },
    },
    {
      CodeName: "SweetsSheep",
      Name: "Woolipop",
      Type: ["Neutral"],
      Moveset: {
        "Air Cannon": 1,
        "Sand Blast": 7,
        "Power Shot": 15,
        "Wind Cutter": 22,
        "Bubble Blast": 30,
        "Power Bomb": 40,
        "Pal Blast": 50,
      },
    },
    {
      CodeName: "ThunderBird",
      Name: "Beakon",
      Type: ["Electric"],
      Moveset: {
        "Air Cannon": 1,
        "Spark Blast": 7,
        Shockwave: 15,
        "Lightning Streak": 22,
        "Tri-Lightning": 30,
        "Sand Tornado": 40,
        "Lightning Bolt": 50,
      },
    },
    {
      CodeName: "ThunderDog",
      Name: "Rayhound",
      Type: ["Electric"],
      Moveset: {
        "Sand Blast": 1,
        Shockwave: 7,
        "Spark Blast": 15,
        "Stone Blast": 22,
        "Electric Ball": 30,
        "Lightning Streak": 40,
        "Lightning Bolt": 50,
      },
    },
    {
      CodeName: "ThunderDragonMan",
      Name: "Orserk",
      Type: ["Dragon", "Electric"],
      Moveset: {
        Kerauno: 1,
        "Lightning Strike": 7,
        "Spark Blast": 15,
        "Draconic Breath": 22,
        "Lightning Streak": 30,
        "Tri-Lightning": 40,
        "Lightning Bolt": 50,
      },
    },
    {
      CodeName: "Umihebi",
      Name: "Jormuntide",
      Type: ["Dragon", "Water"],
      Moveset: {
        "Aqua Gun": 1,
        "Dragon Cannon": 7,
        "Draconic Breath": 15,
        "Aqua Burst": 22,
        "Tri-Lightning": 30,
        "Hydro Laser": 40,
        "Dragon Meteor": 50,
      },
    },
    {
      CodeName: "Umihebi_Fire",
      Name: "Jormuntide Ignis",
      Type: ["Dragon", "Fire"],
      Moveset: {
        "Ignis Blast": 1,
        "Dragon Cannon": 7,
        "Flare Storm": 15,
        "Ignis Breath": 22,
        "Tri-Lightning": 30,
        "Fire Ball": 40,
        "Dragon Meteor": 50,
      },
    },
    {
      CodeName: "VioletFairy",
      Name: "Vaelet",
      Type: ["Grass"],
      Moveset: {
        "Poison Fog": 1,
        "Wind Cutter": 7,
        "Poison Blast": 15,
        "Seed Mine": 22,
        "Grass Tornado": 30,
        "Nightmare Ball": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "VolcanicMonster",
      Name: "Reptyro",
      Type: ["Fire", "Ground"],
      Moveset: {
        "Ignis Blast": 1,
        "Stone Blast": 7,
        "Stone Cannon": 15,
        "Ignis Breath": 22,
        "Volcanic Burst": 30,
        "Ignis Rage": 40,
        "Rock Lance": 50,
      },
    },
    {
      CodeName: "VolcanicMonster_Ice",
      Name: "Ice Reptyro",
      Type: ["Ice", "Ground"],
      Moveset: {
        "Ice Missile": 1,
        "Stone Blast": 7,
        Iceberg: 15,
        "Cryst Breath": 22,
        "Frost Burst": 30,
        "Blizzard Spike": 40,
        "Rock Lance": 50,
      },
    },
    {
      CodeName: "WeaselDragon",
      Name: "Chillet",
      Type: ["Ice", "Dragon"],
      Moveset: {
        "Ice Missile": 1,
        "Dragon Cannon": 7,
        "Dragon Burst": 15,
        "Icicle Cutter": 22,
        "Draconic Breath": 30,
        "Cryst Breath": 40,
        "Dragon Meteor": 50,
      },
    },
    {
      CodeName: "Werewolf",
      Name: "Loupmoon",
      Type: ["Dark"],
      Moveset: {
        "Dark Ball": 1,
        "Jumping Claw": 7,
        "Shadow Burst": 15,
        "Icicle Cutter": 22,
        "Spirit Flame": 30,
        "Nightmare Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "WhiteMoth",
      Name: "Sibelyx",
      Type: ["Ice"],
      Moveset: {
        "Ice Missile": 1,
        "Icicle Cutter": 7,
        Iceberg: 15,
        "Cryst Breath": 22,
        "Spirit Flame": 30,
        "Aqua Burst": 40,
        "Blizzard Spike": 50,
      },
    },
    {
      CodeName: "WhiteTiger",
      Name: "Cryolinx",
      Type: ["Ice"],
      Moveset: {
        "Power Shot": 1,
        "Ice Missile": 7,
        "Stone Cannon": 15,
        "Icicle Cutter": 22,
        Iceberg: 30,
        "Cryst Breath": 40,
        "Blizzard Spike": 50,
      },
    },
    {
      CodeName: "WindChimes",
      Name: "Hangyu",
      Type: ["Ground"],
      Moveset: {},
    },
    {
      CodeName: "WindChimes_Ice",
      Name: "Hangyu Cryst",
      Type: ["Ice"],
      Moveset: {},
    },
    {
      CodeName: "WizardOwl",
      Name: "Hoocrates",
      Type: ["Dark"],
      Moveset: {
        "Air Cannon": 1,
        "Dark Ball": 7,
        "Shadow Burst": 15,
        "Sand Tornado": 22,
        "Spirit Flame": 30,
        "Nightmare Ball": 40,
        "Dark Laser": 50,
      },
    },
    {
      CodeName: "WoolFox",
      Name: "Cremis",
      Type: ["Neutral"],
      Moveset: {
        "Air Cannon": 1,
        "Sand Blast": 7,
        "Spark Blast": 15,
        "Power Shot": 22,
        Shockwave: 30,
        "Power Bomb": 40,
        "Lightning Bolt": 50,
      },
    },
    {
      CodeName: "Yeti",
      Name: "Wumpo",
      Type: ["Ice"],
      Moveset: {
        "Ice Missile": 1,
        "Wind Cutter": 7,
        "Icicle Cutter": 15,
        Iceberg: 22,
        "Cryst Breath": 30,
        "Blizzard Spike": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "Yeti_Grass",
      Name: "Wumpo Botan",
      Type: ["Grass"],
      Moveset: {
        "Wind Cutter": 1,
        "Aqua Gun": 7,
        "Seed Mine": 15,
        "Grass Tornado": 22,
        "Spine Vine": 30,
        "Aqua Burst": 40,
        "Solar Blast": 50,
      },
    },
    {
      CodeName: "GYM_ThunderDragonMan",
      Name: "Axel & Orserk",
      Type: ["Dragon", "Electric"],
      Moveset: {},
      Tower: true,
    },
    {
      CodeName: "GYM_LilyQueen",
      Name: "Lily & Lyleen",
      Type: ["Grass"],
      Moveset: {},
      Tower: true,
    },
    {
      CodeName: "GYM_Horus",
      Name: "Marus & Faleris",
      Type: ["Fire"],
      Moveset: {},
      Tower: true,
    },
    {
      CodeName: "GYM_BlackGriffon",
      Name: "Victor & Shadowbeak",
      Type: ["Dark"],
      Moveset: {},
      Tower: true,
    },
    {
      CodeName: "GYM_ElecPanda",
      Name: "Zoe & Grizzbolt",
      Type: ["Electric"],
      Moveset: {},
      Tower: true,
    },
    {
      CodeName: "Male_DarkTrader01",
      Name: "Black Marketeer",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "FireCult_FlameThrower",
      Name: "Brothers of the Eternal Pyre Martyr",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "Male_Soldier01",
      Name: "Burly Merc",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "Female_Soldier01",
      Name: "Expedition Survivor",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "Believer_CrossBow",
      Name: "Free Pal Alliance Devout",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "Male_Scientist01_LaserRifle",
      Name: "PAL Genetic Research Unit Executioner",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "PalDealer",
      Name: "Pal Merchant",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "Police_Handgun",
      Name: "PIDF Guard",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "Hunter_Bat",
      Name: "Syndicate Thug (Bat)",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "Hunter_FlameThrower",
      Name: "Syndicate Cleaner",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "Hunter_Fat_GatlingGun",
      Name: "Syndicate Crusher",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "Hunter_RocketLauncher",
      Name: "Syndicate Elite",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "Hunter_Grenade",
      Name: "Syndicate Grenadier",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "Hunter_Rifle",
      Name: "Syndicate Gunner",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "Hunter_Shotgun",
      Name: "Syndicate Hunter",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "Hunter_Handgun",
      Name: "Syndicate Thug (Handgun)",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
    {
      CodeName: "SalesPerson",
      Name: "Wandering Merchant",
      Type: ["None"],
      Moveset: {},
      Human: true,
    },
  ],
}
