import type { NextApiRequest, NextApiResponse } from 'next'
import {
  mockData
} from '@dj/queryCartCouponsList'
const API = (req: NextApiRequest, res: NextApiResponse) => {

  const { obj, ...obj_others } = mockData_tmp
  const data = {
    ...obj_others,
    obj: obj.map((t1, idx1) => {
      const { cartCouponInfoList, ...t1_others } = t1
      return {
        ...t1_others,
        cartCouponInfoList: cartCouponInfoList.map((t2, idx2) => {
          if (idx2 == 1) {
            t2.buttonFlag = 2
          }
          return t2
        }),
        // cartCouponInfoList: []
      }
    })
  }

  return new Promise(function (resolve) {
    setTimeout(resolve.bind(null, resolve), 1000)
  })
    .then(() => {
      res.status(200).json(data)
    })
}

export default API

const mockData_tmp = {
  "success": true,
  "resCode": "00100000",
  "traceId": "5e23f80fa3498cfb",
  "obj": [
    {
      "showOrderAmount": 0.00,
      "hgCheckedNumber": 0,
      "cartCouponInfoList": [
        {
          "jumpType": "25",
          "couponName": "第一医药看购物车券展示的",
          "validType": "1",
          "offsetAmount": 3,
          "needPrice": 0,
          "buttonFlag": "1",
          "goodsList": [
            {
              "shoppingCartType": "5",
              "discountRate": 0.00,
              "isNewAdd": "0",
              "type": "25",
              "oldSalePrice": 161.20,
              "freightMoney": 0.00,
              "goodsOriginalNumber": 1,
              "medicareFlag": "0",
              "goodsGiftNumber": 0,
              "price": 0.00,
              "ggName": "50ug*40s",
              "goodsPicUrl": "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1528227518_360x360.jpg",
              "medicineType": "2",
              "goodsName": "石杉碱甲片50ug*40s",
              "ifOnlyPickup": "0",
              "productSid": "2267814",
              "showSalePrice": 161.2,
              "checkedOriginal": false,
              "isPopEffective": "1",
              "processingTime": 0,
              "isFromButtomShop": "0",
              "featureList": [
                {
                  "features": [
                    {
                      "featureName": "我属性1",
                      "propSid": 3009,
                      "propName": "我书属性",
                      "featureId": "3016"
                    },
                    {
                      "featureName": "黑色",
                      "propSid": 3010,
                      "propName": "属性组2",
                      "featureId": "3017"
                    }
                  ],
                  "featureSign": "3284841-3016-3017-6912ed3129c25e0022a90b50",
                  "goodsId": "3284841",
                  "mainGoodsLineBr": "6912ed3129c25e0022a90b50",
                  "num": 1,
                  "updateTime": "2025-11-11 16:00:50 0731",
                  "_id": "6912ed3129c25e0022a90b51",
                  "checkFlag": true
                }
              ],
              "sType": "1",
              "stor": 9962,
              "limitBuySum": -1,
              "kdjShopId": "001100",
              "currPrice": 0.00,
              "if7Refund": "0",
              "medicareCateCode": "HB000000078,S2VH2O0M8PW,H100161",
              "reduceAmout": 0.00,
              "promotionPrice": 161.2,
              "totalPrice": 0.00,
              "goodsId": "3284841",
              "dggUncheckNum": 0,
              "capacity": 0.00,
              "referencePrice": 0.00,
              "featureSign": "3284841-3016-3017-6912ed3129c25e0022a90b50",
              "checkLevel": "1",
              "isMergeTemplete": "0",
              "goodsLineNbr": "6912ed3129c25e0022a90b50",
              "userPrice": 0,
              "handPrice": 0.00,
              "isTakenBySelf": "1",
              "tariff": 0,
              "counpDisCount": 0.00,
              "showGoodsDiscount": 0.00,
              "mpReduceMoney": 0.00,
              "salePrice": 161.20,
              "priceType": "0",
              "virtualSellFlag": "0",
              "hasActivity": "1",
              "updateTime": "2025-11-11 16:00:50 0865",
              "medicareOnlineFlag": "0",
              "isCLFlag": false,
              "depositEndTime": "2099-12-31 23:59:59",
              "promBillNo": 0,
              "goodsPopDiscount2": 0.00,
              "did": "",
              "yunType": "2",
              "basketLimitGoodsNum": -1,
              "groupId": "4018DYSD0",
              "deliveryCharge": 0.00,
              "promotionMark": "0",
              "proSellBit": 4,
              "futuresType": "0",
              "totalCapacity": 0.00,
              "goodsNumber": 1,
              "saleSum": 0,
              "tariffRate": "0",
              "stockStatus": "0",
              "checked": true,
              "depositStartTime": "2021-01-15 18:06:13",
              "sdName": "石杉碱甲片",
              "depositDeductMoney": 0.00,
              "brandName": "方总'",
              "kdjSourceShopId": "001100",
              "kdjmerchantID": "60200011001",
              "personPriceList": [
                {
                  "salePrice": 161.20,
                  "limitBuySum": -1,
                  "priceType": "0",
                  "limitBuyPersonSum": -1
                }
              ],
              "depositMoney": 0.00,
              "weight": 0.001,
              "tax": "0.13",
              "pricechange": false,
              "globalType": "0",
              "isDelevery": "1",
              "barCode": "1999062",
              "goodsType": "30",
              "dggFlag": "1",
              "normalSalePrice": 161.2,
              "djSendType": "3",
              "comSid": "6000",
              "goodsUrl": "https://product.st.bl.com/3284841.html",
              "finalPaymentMoney": 0.00,
              "xgOriginalPrice": 0.00,
              "goodsNumberForLimit": 0,
              "brandSid": "100170",
              "storeIndustrySid": "6020",
              "isWeight": "0",
              "limitBuyPersonSum": -1,
              "addGoodsPrice": 161.2,
              "promotionExpandMoney": 0.00,
              "supplierId": "141759",
              "stanName": "50ug*40s",
              "kdjSourceMerchantId": "60200011001",
              "goodsDiscount": 0.00,
              "freeFreight": false,
              "categoryBackIds": "102689",
              "preBuyFlag": "0",
              "isGift": "0",
              "kdjSourceStoreIndustrySid": "6020",
              "singleDiscountPrice": 0.00,
              "categoryid": "81066",
              "activeCode": "",
              "backChange": 0,
              "ifCanBuy": "1",
              "editable": "1",
              "measureUnit": "盒",
              "comsGoodsCode": "1999062",
              "medicareCountryCode": "HB000000078,S2VH2O0M8PW,H100161",
              "mdmGoodsSid": "60001999062",
              "totalWeight": 0.001,
              "logisticsType": "01"
            },
            {
              "shoppingCartType": "5",
              "discountRate": 0.00,
              "isNewAdd": "0",
              "type": "25",
              "oldSalePrice": 199.00,
              "freightMoney": 0.00,
              "goodsOriginalNumber": 1,
              "medicareFlag": "0",
              "goodsGiftNumber": 0,
              "price": 0.00,
              "goodsPicUrl": "https://Img.st.iblimg.com/fast2homemethod-3/offlinegoods/goods/SP_1979433579_360x360.jpg",
              "medicineType": "2",
              "goodsName": "头孢呋辛酯片0.125g*12s",
              "ifOnlyPickup": "0",
              "productSid": "2267746",
              "showSalePrice": 199,
              "checkedOriginal": false,
              "isPopEffective": "1",
              "processingTime": 0,
              "sType": "1",
              "stor": 966,
              "limitBuySum": -1,
              "kdjShopId": "001100",
              "currPrice": 0.00,
              "if7Refund": "0",
              "medicareCateCode": "6943297600628",
              "reduceAmout": 0.00,
              "promotionPrice": 199,
              "totalPrice": 0.00,
              "goodsId": "3284773",
              "dggUncheckNum": 0,
              "capacity": 0.00,
              "referencePrice": 0.00,
              "checkLevel": "1",
              "isMergeTemplete": "0",
              "goodsLineNbr": "6912ffaa29c25e0022a90be0",
              "userPrice": 0,
              "handPrice": 0.00,
              "isTakenBySelf": "1",
              "tariff": 0,
              "counpDisCount": 0.00,
              "showGoodsDiscount": 0.00,
              "mpReduceMoney": 0.00,
              "salePrice": 199.00,
              "priceType": "0",
              "virtualSellFlag": "0",
              "hasActivity": "1",
              "updateTime": "2025-11-11 17:19:39 0242",
              "medicareOnlineFlag": "1",
              "isCLFlag": false,
              "depositEndTime": "2099-12-31 23:59:59",
              "promBillNo": 0,
              "goodsPopDiscount2": 0.00,
              "did": "",
              "yunType": "2",
              "basketLimitGoodsNum": -1,
              "groupId": "4018DYSD0",
              "deliveryCharge": 0.00,
              "promotionMark": "0",
              "proSellBit": 4,
              "futuresType": "0",
              "totalCapacity": 0.00,
              "goodsNumber": 1,
              "saleSum": 0,
              "tariffRate": "0",
              "stockStatus": "0",
              "checked": true,
              "depositStartTime": "2021-06-07 16:13:14",
              "sdName": "头孢呋辛酯片",
              "depositDeductMoney": 0.00,
              "brandName": "方总'",
              "kdjSourceShopId": "001100",
              "kdjmerchantID": "60200011001",
              "personPriceList": [
                {
                  "salePrice": 199.00,
                  "limitBuySum": -1,
                  "priceType": "0",
                  "limitBuyPersonSum": -1
                }
              ],
              "depositMoney": 0.00,
              "weight": 0.001,
              "tax": "0.13",
              "pricechange": false,
              "globalType": "0",
              "isDelevery": "1",
              "barCode": "6943297600628",
              "goodsType": "30",
              "normalSalePrice": 199,
              "djSendType": "3",
              "comSid": "6000",
              "goodsUrl": "https://product.st.bl.com/3284773.html",
              "finalPaymentMoney": 0.00,
              "xgOriginalPrice": 0.00,
              "goodsNumberForLimit": 0,
              "brandSid": "100170",
              "storeIndustrySid": "6020",
              "isWeight": "0",
              "limitBuyPersonSum": -1,
              "addGoodsPrice": 199.0,
              "promotionExpandMoney": 0.00,
              "supplierId": "-1",
              "stanName": "0.125g*12s",
              "kdjSourceMerchantId": "60200011001",
              "goodsDiscount": 0.00,
              "freeFreight": false,
              "categoryBackIds": "102689",
              "preBuyFlag": "0",
              "isGift": "0",
              "kdjSourceStoreIndustrySid": "6020",
              "singleDiscountPrice": 0.00,
              "categoryid": "81633",
              "activeCode": "",
              "backChange": 0,
              "ifCanBuy": "1",
              "editable": "1",
              "measureUnit": "盒",
              "comsGoodsCode": "1999053",
              "medicareCountryCode": "6943297600628",
              "mdmGoodsSid": "60001999053",
              "totalWeight": 0.001,
              "logisticsType": "01"
            },
            {
              "shoppingCartType": "5",
              "discountRate": 0.00,
              "isNewAdd": "0",
              "type": "25",
              "oldSalePrice": 48.70,
              "freightMoney": 0.00,
              "goodsOriginalNumber": 1,
              "goodsGiftNumber": 0,
              "price": 0.00,
              "ggName": "首X件限购5件",
              "goodsPicUrl": "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1788872213_360x360.jpg",
              "medicineType": "1",
              "goodsName": "紧急发版改名字",
              "ifOnlyPickup": "0",
              "productSid": "2267744",
              "showSalePrice": 48.7,
              "checkedOriginal": false,
              "isPopEffective": "1",
              "processingTime": 0,
              "isFromButtomShop": "0",
              "sType": "1",
              "stor": 11081,
              "limitBuySum": -1,
              "kdjShopId": "001100",
              "currPrice": 0.00,
              "if7Refund": "1",
              "reduceAmout": 0.00,
              "promotionPrice": 48.7,
              "totalPrice": 0.00,
              "goodsId": "3284771",
              "dggUncheckNum": 0,
              "capacity": 0.00,
              "referencePrice": 0.00,
              "checkLevel": "1",
              "isMergeTemplete": "0",
              "goodsLineNbr": "69114f40cf4d610022fe0ed6",
              "userPrice": 0,
              "handPrice": 0.00,
              "isTakenBySelf": "1",
              "tariff": 0,
              "counpDisCount": 0.00,
              "showGoodsDiscount": 0.00,
              "mpReduceMoney": 0.00,
              "salePrice": 48.70,
              "priceType": "0",
              "virtualSellFlag": "0",
              "hasActivity": "1",
              "updateTime": "2025-11-10 10:34:41 0950",
              "medicareOnlineFlag": "1",
              "isCLFlag": false,
              "depositEndTime": "2099-12-31 23:59:59",
              "promBillNo": 0,
              "goodsPopDiscount2": 0.00,
              "did": "",
              "yunType": "2",
              "basketLimitGoodsNum": -1,
              "groupId": "4018DYSD0",
              "deliveryCharge": 0.00,
              "promotionMark": "0",
              "proSellBit": 4,
              "futuresType": "0",
              "totalCapacity": 0.00,
              "goodsNumber": 1,
              "saleSum": 0,
              "tariffRate": "0",
              "stockStatus": "0",
              "checked": true,
              "depositStartTime": "2021-01-15 18:05:45",
              "sdName": "头孢拉定分散片测试211测试测试2333",
              "depositDeductMoney": 0.00,
              "brandName": "到家修改",
              "kdjSourceShopId": "001100",
              "kdjmerchantID": "60200011001",
              "personPriceList": [
                {
                  "salePrice": 48.70,
                  "limitBuySum": -1,
                  "priceType": "0",
                  "limitBuyPersonSum": -1
                }
              ],
              "depositMoney": 0.00,
              "weight": 0.677,
              "tax": "0.06",
              "pricechange": false,
              "globalType": "0",
              "isDelevery": "1",
              "barCode": "6903447301133",
              "goodsType": "1",
              "normalSalePrice": 48.7,
              "djSendType": "3",
              "comSid": "6000",
              "goodsUrl": "https://product.st.bl.com/3284771.html",
              "finalPaymentMoney": 0.00,
              "xgOriginalPrice": 0.00,
              "goodsNumberForLimit": 0,
              "brandSid": "200687",
              "storeIndustrySid": "6020",
              "isWeight": "1",
              "limitBuyPersonSum": -1,
              "onlineStanName": "800",
              "addGoodsPrice": 48.7,
              "promotionExpandMoney": 0.00,
              "supplierId": "-1",
              "stanName": "88ml",
              "kdjSourceMerchantId": "60200011001",
              "goodsDiscount": 0.00,
              "freeFreight": false,
              "categoryBackIds": "102689",
              "preBuyFlag": "0",
              "isGift": "0",
              "kdjSourceStoreIndustrySid": "6020",
              "singleDiscountPrice": 0.00,
              "categoryid": "75781",
              "activeCode": "",
              "backChange": 0,
              "ifCanBuy": "1",
              "editable": "1",
              "measureUnit": "发版发版",
              "comsGoodsCode": "1999005",
              "mdmGoodsSid": "60001999005",
              "totalWeight": 0.677,
              "logisticsType": "01"
            },
            {
              "shoppingCartType": "5",
              "discountRate": 0.00,
              "isNewAdd": "0",
              "type": "25",
              "oldSalePrice": 71.20,
              "freightMoney": 0.00,
              "goodsOriginalNumber": 1,
              "medicareFlag": "0",
              "goodsGiftNumber": 0,
              "price": 0.00,
              "ggName": "改为规格",
              "goodsPicUrl": "https://blqqd-pa-filemanager-sit-pub.st.iblimg.com/daojia_osp_public/offlinegoods/goods/SP_/20250520142130976/60008429084_360x360.jpg",
              "medicineType": "2",
              "goodsName": "氨糖软骨素钙片183.60g(1.02g*180片)",
              "ifOnlyPickup": "0",
              "productSid": "2261378",
              "showSalePrice": 71.2,
              "checkedOriginal": false,
              "isPopEffective": "1",
              "processingTime": 0,
              "isFromButtomShop": "0",
              "featureList": [
                {
                  "features": [
                    {
                      "featureName": "A",
                      "propSid": 5509,
                      "propName": "属性A",
                      "featureId": "6024"
                    }
                  ],
                  "featureSign": "3278408-6024-6912ff9f29c25e0022a90bdd",
                  "goodsId": "3278408",
                  "mainGoodsLineBr": "6912ff9f29c25e0022a90bdd",
                  "num": 1,
                  "updateTime": "2025-11-11 17:19:28 0439",
                  "_id": "6912ff9f29c25e0022a90bde",
                  "checkFlag": true
                }
              ],
              "sType": "1",
              "stor": 3,
              "limitBuySum": -1,
              "kdjShopId": "001100",
              "currPrice": 0.00,
              "if7Refund": "0",
              "medicareCateCode": "6940863609689",
              "reduceAmout": 0.00,
              "promotionPrice": 71.2,
              "totalPrice": 0.00,
              "goodsId": "3278408",
              "dggUncheckNum": 0,
              "capacity": 0.00,
              "referencePrice": 0.00,
              "featureSign": "3278408-6024-6912ff9f29c25e0022a90bdd",
              "checkLevel": "1",
              "isMergeTemplete": "0",
              "goodsLineNbr": "6912ff9f29c25e0022a90bdd",
              "userPrice": 0,
              "handPrice": 0.00,
              "isTakenBySelf": "1",
              "tariff": 0,
              "counpDisCount": 0.00,
              "showGoodsDiscount": 0.00,
              "mpReduceMoney": 0.00,
              "salePrice": 71.20,
              "priceType": "0",
              "virtualSellFlag": "0",
              "hasActivity": "1",
              "updateTime": "2025-11-11 17:19:28 0682",
              "medicareOnlineFlag": "0",
              "isCLFlag": false,
              "depositEndTime": "2099-12-31 23:59:59",
              "promBillNo": 0,
              "goodsPopDiscount2": 0.00,
              "did": "",
              "yunType": "2",
              "basketLimitGoodsNum": -1,
              "groupId": "4018DYSD0",
              "deliveryCharge": 0.00,
              "promotionMark": "0",
              "proSellBit": 4,
              "futuresType": "0",
              "totalCapacity": 0.00,
              "goodsNumber": 1,
              "saleSum": 0,
              "tariffRate": "0",
              "stockStatus": "0",
              "checked": true,
              "depositStartTime": "2021-01-06 14:31:32",
              "sdName": "健力多氨糖软骨素钙片",
              "depositDeductMoney": 0.00,
              "brandName": "国产-健力多",
              "kdjSourceShopId": "001100",
              "kdjmerchantID": "60200011001",
              "personPriceList": [
                {
                  "salePrice": 71.20,
                  "limitBuySum": -1,
                  "priceType": "0",
                  "limitBuyPersonSum": -1
                }
              ],
              "depositMoney": 0.00,
              "weight": 0.200,
              "tax": "0.13",
              "pricechange": false,
              "globalType": "0",
              "isDelevery": "1",
              "barCode": "LH2468095613",
              "goodsType": "1",
              "dggFlag": "1",
              "normalSalePrice": 71.2,
              "djSendType": "3",
              "comSid": "6000",
              "goodsUrl": "https://product.st.bl.com/3278408.html",
              "finalPaymentMoney": 0.00,
              "xgOriginalPrice": 0.00,
              "goodsNumberForLimit": 0,
              "brandSid": "206169",
              "storeIndustrySid": "6020",
              "isWeight": "0",
              "limitBuyPersonSum": -1,
              "addGoodsPrice": 71.2,
              "promotionExpandMoney": 0.00,
              "supplierId": "141323",
              "stanName": "183.60g(1.02g*180片)",
              "kdjSourceMerchantId": "60200011001",
              "goodsDiscount": 0.00,
              "freeFreight": false,
              "categoryBackIds": "103332",
              "preBuyFlag": "0",
              "isGift": "0",
              "kdjSourceStoreIndustrySid": "6020",
              "singleDiscountPrice": 0.00,
              "categoryid": "81792",
              "activeCode": "",
              "backChange": 0,
              "ifCanBuy": "1",
              "editable": "1",
              "measureUnit": "盒",
              "comsGoodsCode": "8429084",
              "medicareCountryCode": "XD10BAY152E002010200805",
              "mdmGoodsSid": "60008429084",
              "totalWeight": 0.200,
              "logisticsType": "01"
            },
            {
              "shoppingCartType": "5",
              "discountRate": 0.00,
              "isNewAdd": "0",
              "type": "25",
              "oldSalePrice": 69.00,
              "freightMoney": 0.00,
              "goodsOriginalNumber": 1,
              "medicareFlag": "1",
              "goodsGiftNumber": 0,
              "price": 0.00,
              "ggName": "碳酸钙",
              "goodsPicUrl": "https://blqqd-pa-filemanager-sit-pub.st.iblimg.com/daojia_osp_public/offlinegoods/goods/SP_/20251031183218348/60001000262_360x360.jpg",
              "medicineType": "2",
              "goodsName": "仅男性纷纷富 碳酸钙片 0.75g*120片纷纷富 碳酸钙片 0.75g*120片纷纷富 碳酸钙片 0.75g*120片纷纷富 碳酸钙片 0.75g*120片纷纷富 碳酸钙片 0.75g*120片",
              "ifOnlyPickup": "0",
              "productSid": "2260243",
              "showSalePrice": 69,
              "checkedOriginal": false,
              "isPopEffective": "1",
              "processingTime": 0,
              "featureList": [
                {
                  "features": [
                    {
                      "featureName": "我是属性1",
                      "propSid": 3006,
                      "propName": "我是属性",
                      "featureId": "3007"
                    }
                  ],
                  "featureSign": "3277293-3007-6912ed3329c25e0022a90b52",
                  "goodsId": "3277293",
                  "mainGoodsLineBr": "6912ed3329c25e0022a90b52",
                  "num": 1,
                  "updateTime": "2025-11-11 16:00:52 0672",
                  "_id": "6912ed3329c25e0022a90b53",
                  "checkFlag": true
                }
              ],
              "sType": "1",
              "stor": 10973,
              "limitBuySum": -1,
              "kdjShopId": "001100",
              "currPrice": 0.00,
              "if7Refund": "0",
              "medicareCateCode": "6921329401047",
              "reduceAmout": 0.00,
              "promotionPrice": 69,
              "totalPrice": 0.00,
              "goodsId": "3277293",
              "dggUncheckNum": 0,
              "capacity": 0.00,
              "referencePrice": 0.00,
              "featureSign": "3277293-3007-6912ed3329c25e0022a90b52",
              "checkLevel": "1",
              "isMergeTemplete": "0",
              "goodsLineNbr": "6912ed3329c25e0022a90b52",
              "userPrice": 0,
              "handPrice": 0.00,
              "isTakenBySelf": "1",
              "tariff": 0,
              "counpDisCount": 0.00,
              "showGoodsDiscount": 0.00,
              "mpReduceMoney": 0.00,
              "salePrice": 69.00,
              "priceType": "0",
              "virtualSellFlag": "0",
              "hasActivity": "1",
              "updateTime": "2025-11-11 16:00:52 0802",
              "medicareOnlineFlag": "1",
              "isCLFlag": false,
              "depositEndTime": "2099-12-31 23:59:59",
              "promBillNo": 0,
              "goodsPopDiscount2": 0.00,
              "did": "",
              "yunType": "2",
              "basketLimitGoodsNum": -1,
              "groupId": "4018DYSD0",
              "deliveryCharge": 0.00,
              "promotionMark": "0",
              "proSellBit": 4,
              "futuresType": "0",
              "totalCapacity": 0.00,
              "goodsNumber": 1,
              "saleSum": 0,
              "tariffRate": "0",
              "stockStatus": "0",
              "checked": true,
              "depositStartTime": "2024-03-04 16:23:41",
              "sdName": "碳酸钙片",
              "depositDeductMoney": 0.00,
              "brandName": "无品牌",
              "kdjSourceShopId": "001100",
              "kdjmerchantID": "60200011001",
              "personPriceList": [
                {
                  "salePrice": 69.00,
                  "limitBuySum": -1,
                  "priceType": "0",
                  "limitBuyPersonSum": -1
                }
              ],
              "depositMoney": 0.00,
              "weight": 0.001,
              "tax": "0.13",
              "pricechange": false,
              "globalType": "0",
              "isDelevery": "1",
              "barCode": "6921329401047",
              "goodsType": "29",
              "dggFlag": "1",
              "normalSalePrice": 69,
              "djSendType": "2",
              "comSid": "6000",
              "goodsUrl": "https://product.st.bl.com/3277293.html",
              "finalPaymentMoney": 0.00,
              "xgOriginalPrice": 0.00,
              "goodsNumberForLimit": 0,
              "brandSid": "116029",
              "storeIndustrySid": "6020",
              "isWeight": "0",
              "limitBuyPersonSum": -1,
              "addGoodsPrice": 69.0,
              "promotionExpandMoney": 0.00,
              "supplierId": "143183",
              "stanName": "0.75g*120片",
              "kdjSourceMerchantId": "60200011001",
              "goodsDiscount": 0.00,
              "freeFreight": false,
              "categoryBackIds": "103914",
              "preBuyFlag": "0",
              "isGift": "0",
              "kdjSourceStoreIndustrySid": "6020",
              "singleDiscountPrice": 0.00,
              "categoryid": "81367",
              "activeCode": "",
              "backChange": 0,
              "ifCanBuy": "1",
              "editable": "1",
              "measureUnit": "盒",
              "comsGoodsCode": "1000262",
              "medicareCountryCode": "XA12AAT012A001010501890",
              "mdmGoodsSid": "60001000262",
              "totalWeight": 0.001,
              "logisticsType": "01"
            },
            {
              "shoppingCartType": "5",
              "discountRate": 0.00,
              "isNewAdd": "0",
              "type": "25",
              "oldSalePrice": 11.20,
              "freightMoney": 0.00,
              "goodsOriginalNumber": 1,
              "medicareFlag": "1",
              "goodsGiftNumber": 0,
              "price": 0.00,
              "goodsPicUrl": "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_2099995052_360x360.jpg",
              "medicineType": "2",
              "goodsName": "医保支付",
              "ifOnlyPickup": "0",
              "productSid": "2260242",
              "showSalePrice": 11.2,
              "checkedOriginal": false,
              "isPopEffective": "1",
              "processingTime": 0,
              "sType": "1",
              "stor": 11066,
              "limitBuySum": -1,
              "kdjShopId": "001100",
              "currPrice": 0.00,
              "if7Refund": "1",
              "medicareCateCode": "6901334300924",
              "reduceAmout": 0.00,
              "promotionPrice": 11.2,
              "totalPrice": 0.00,
              "goodsId": "3277292",
              "dggUncheckNum": 0,
              "capacity": 0.00,
              "referencePrice": 0.00,
              "checkLevel": "1",
              "isMergeTemplete": "0",
              "goodsLineNbr": "6912ffa029c25e0022a90bdf",
              "userPrice": 0,
              "handPrice": 0.00,
              "isTakenBySelf": "1",
              "tariff": 0,
              "counpDisCount": 0.00,
              "showGoodsDiscount": 0.00,
              "mpReduceMoney": 0.00,
              "salePrice": 11.20,
              "priceType": "0",
              "virtualSellFlag": "0",
              "hasActivity": "1",
              "updateTime": "2025-11-11 17:19:29 0987",
              "medicareOnlineFlag": "1",
              "isCLFlag": false,
              "depositEndTime": "2099-12-31 23:59:59",
              "promBillNo": 0,
              "goodsPopDiscount2": 0.00,
              "did": "",
              "yunType": "2",
              "basketLimitGoodsNum": -1,
              "groupId": "4018DYSD0",
              "deliveryCharge": 0.00,
              "promotionMark": "0",
              "proSellBit": 4,
              "futuresType": "0",
              "totalCapacity": 0.00,
              "goodsNumber": 1,
              "saleSum": 0,
              "tariffRate": "0",
              "stockStatus": "0",
              "checked": true,
              "depositStartTime": "2024-03-04 16:23:41",
              "sdName": "喷托维林氯化铵糖浆",
              "depositDeductMoney": 0.00,
              "brandName": "无品牌",
              "kdjSourceShopId": "001100",
              "kdjmerchantID": "60200011001",
              "personPriceList": [
                {
                  "salePrice": 11.20,
                  "limitBuySum": -1,
                  "priceType": "0",
                  "limitBuyPersonSum": -1
                }
              ],
              "depositMoney": 0.00,
              "weight": 0.289,
              "tax": "0",
              "pricechange": false,
              "globalType": "0",
              "isDelevery": "1",
              "barCode": "6901334300924",
              "goodsType": "29",
              "normalSalePrice": 11.2,
              "djSendType": "3",
              "comSid": "6000",
              "goodsUrl": "https://product.st.bl.com/3277292.html",
              "finalPaymentMoney": 0.00,
              "xgOriginalPrice": 0.00,
              "goodsNumberForLimit": 0,
              "brandSid": "116029",
              "storeIndustrySid": "6020",
              "isWeight": "0",
              "limitBuyPersonSum": -1,
              "addGoodsPrice": 11.2,
              "promotionExpandMoney": 0.00,
              "supplierId": "143511",
              "stanName": "回归规格D11",
              "kdjSourceMerchantId": "60200011001",
              "goodsDiscount": 0.00,
              "freeFreight": false,
              "categoryBackIds": "221137",
              "preBuyFlag": "0",
              "isGift": "0",
              "kdjSourceStoreIndustrySid": "6020",
              "singleDiscountPrice": 0.00,
              "categoryid": "75492",
              "activeCode": "",
              "backChange": 0,
              "ifCanBuy": "1",
              "editable": "1",
              "measureUnit": "回归单位C11",
              "comsGoodsCode": "1000230",
              "medicareCountryCode": "XR05XXP036K001010100423",
              "mdmGoodsSid": "60001000230",
              "totalWeight": 0.289,
              "logisticsType": "01"
            }
          ],
          "couponTemplateId": "5783459868",
          "openTimeTo": "2026-04-11 23:59:59",
          "brandVoucher": "0",
          "jumpValue": "http://cloudwebapp.st.bl.com/wxapp?path=platformSubPackage%2Fpages%2FCouponAvailableGoodsList%2FCouponAvailableGoodsList&scene=qhbZnsRvhM2fF*Q2^|^gh_cea3fcf76eef|platformSubPackage/pages/CouponAvailableGoodsList/CouponAvailableGoodsList?couponTemplateId=5783459868^|^blcloudstore://cloudstore/page/CouponAvailableGoodsList?couponTemplateId=5783459868^|^wx5cc935253e8cb92f|platformSubPackage/pages/CouponAvailableGoodsList/CouponAvailableGoodsList?couponTemplateId=5783459868",
          "oriPrice": 560.30,
          "meetAmount": 30,
          "waitDays": "0",
          "showDjEffectTime": "领券当日可使用",
          "buyMember": "0",
          "effectDays": "1",
          "openTimeFrom": "2025-04-11 18:01:51",
          "currPrice": "520.29",
          "isCheckedNum": "6"
        }
      ],
      "deliveryCharge": 0.00,
      "totalGoodsEffectNumber": 0,
      "hgLessPrice": 0,
      "deliveryServiceCharge": 0.00,
      "freightDiscount": 0.00,
      "ticketMoney": 0.00,
      "checked": false,
      "freeFreightAmount": 0,
      "oringinDeliveryCharge": 0.00,
      "promBillNoList": [],
      "freeFreightNeedAmount": 0,
      "baseDeliveryCharge": 0.00,
      "isMatch": false,
      "isDelevery": "0",
      "totalGoodsAmount": 0,
      "popTimes": 0,
      "maxSkus": 0,
      "totalGoodsNumber": 0,
      "promotionConditionAmount": 0.00,
      "hasSelfSupportGoods": true,
      "promotionLimit": 0.00,
      "newOrderPay": 0.00,
      "xyMakeUpCount": 0,
      "xyCount": 0,
      "popTypeMark": 0,
      "xyMakeUpAmount": 0.00,
      "promotionDiscount": 0.00,
      "orderAmount": 0.00,
      "isTakenBySelf": "0",
      "conditionAmount": 0.00,
      "groupDiscountMoney": 0.00,
      "popType": 0,
      "assignFlag": "0",
      "tariffAmount": 0.00,
      "orderPay": 0.00,
      "totalcheckedGoodsAmount": 0,
      "activityMark": "0",
      "showOrderDiscount": 0.00,
      "orderDiscount": 0.00,
      "totalWeight": 0.00,
      "isGroupPop": "0",
      "totalGoodsEffectAmount": 0,
      "totalcheckedGoodsNumber": 0,
      "determineDateTimeId": "",
      "did": "",
      "basketMark": "0"
    }
  ]
}
