const API = (req, res) => {
  const { page } = req.body
  const total_page = Math.max(0, 5 - page)

  // const list = Array.from({ length: 10 }, (t, idx) => ({}))

  const buttonFlagEnum = {
    1: '立即领取',
    2: '已领取',
    3: '已领完',
    4: '达到个人领券上限',
  }
  let receiveFlag = 1
  let buttonFlag = 1
  let data = mockData.obj.list
  // .map((t, idx) => {
  //   if (buttonFlag <= 3) {
  //     buttonFlag += 1
  //     t.receiveFlag = receiveFlag
  //     t.buttonFlag = buttonFlag
  //     t.buttonFlagMsg = buttonFlagEnum[buttonFlag]
  //   } else {
  //     receiveFlag += 1
  //     buttonFlag = 1
  //   }
  //   return t
  // })
  data = Array.from({ length: 4 * 4 }, (t, idx) => {
    const obj = mockData.obj.list[9]
    if (buttonFlag <= 3) {
      buttonFlag += 1
    } else {
      receiveFlag += 1
      buttonFlag = 1
    }
    return {
      ...obj,
      receiveFlag,
      buttonFlag,
      plusFlag: 0,
      buttonFlagMsg: buttonFlagEnum[buttonFlag]
    }
  })
  /** 领取状态:
   *      1:立即领取;
   *      2:再领一张;
   *      3:已领完(本人已领);
   *      4:已领完(本人未领)
   *
   * buttonFlag:
   *      1: 立即领取
   *      2: 已领取
   *      3: 已领完
   *      4: 达到个人领券上限
  */

  return new Promise(function (resolve) {
    setTimeout(resolve.bind(null, resolve), 1000)
  })
    .then(() => {
      res.status(200).json({
        "success": true,
        "resCode": "00100000",
        "obj": {
          "pages": 1,
          "count": 10,
          "start": 1,
          "pageSize": 10000,
          "end": 10000,
          "currentPage": 1,
          "list": data
        }
      })
    })
}

export default API


const mockData = {
  "success": true,
  "resCode": "00100000",
  "obj": {
    "pages": 1,
    "count": 10,
    "start": 1,
    "pageSize": 10000,
    "end": 10000,
    "currentPage": 1,
    "list": [
      {
        "couponCode": null,
        "couponRuleId": null,
        "contentTextPc": null,
        "erCode": null,
        "cloudFlag": "0",
        "signinAcquire": "1",
        "isAcquiredCoupon": "N",
        "userDayCouponCount": "0",
        "merchants": null,
        "waitDays": null,
        "offsetAmount": "5",
        "maxNumPerUserDay": null,
        "produceNum": null,
        "couponListUrl": null,
        "dayCouponCount": "1000",
        "enableTimeFrom": "2021-07-09 00:00:00",
        "buttonFlagMsg": "已领完",
        "contentTextScreen": null,
        "siteStore": null,
        "stores": null,
        "effectDays": null,
        "couponDetailUrl": null,
        "useChannel": "1,2,22",
        "validType": "0",
        "maxNumDay": "1000",
        "enableTimeTo": "2022-07-09 23:59:59",
        "issueNum": "0",
        "showOrder": "1",
        "acquireType": "3",
        "maxNum": null,
        "birthdayFlag": null,
        "couponPicUrl": null,
        "openTimeFrom": "2021-07-09 00:00:00",
        "couponTypeId": "20",
        "pointsValue": "0",
        "notSentCouponCount": null,
        "contentTextApp": null,
        "jumpValue": null,
        "jumpType": "13",
        "couponChannelType": null,
        "couponName": "快到家PLUS专享5折券",
        "couponType": "折扣券",
        "openTimeTo": "2022-07-09 23:59:59",
        "maxNumPerUser": null,
        "couponDesc": "快到家PLUS专享5折券快到家PLUS专享5折券快到家PLUS专享5折券",
        "canAcquireCoupon": "N",
        "couponTemplateId": "295568941",
        "suitShopCount": null,
        "couponShortDesc": "快到家PLUS专享5折券",
        "acquireFlag": "1",
        "userCouponCount": "0",
        "mpShopName": null,
        "couponScope": "0",
        "nextGenerateTime": null,
        "currentGenerateTime": "",
        "buttonFlag": "3",
        "receiveFlag": "4",
        "alreadyPercentNum": "100",
        "noticeDesc1": null,
        "noticeDesc2": null,
        "conditionAmount": null,
        "conditionFlag": null,
        "plusFlag": "1",
        "plusWeightFlag": "0"
      },
      {
        "couponCode": null,
        "couponRuleId": null,
        "contentTextPc": null,
        "erCode": null,
        "cloudFlag": "0",
        "signinAcquire": "1",
        "isAcquiredCoupon": "N",
        "userDayCouponCount": "0",
        "merchants": null,
        "waitDays": null,
        "offsetAmount": "5",
        "maxNumPerUserDay": null,
        "produceNum": null,
        "couponListUrl": null,
        "dayCouponCount": "0",
        "enableTimeFrom": "2021-07-09 00:00:00",
        "buttonFlagMsg": "立即领取",
        "contentTextScreen": null,
        "siteStore": null,
        "stores": null,
        "effectDays": null,
        "couponDetailUrl": null,
        "useChannel": "1,2,22",
        "validType": "0",
        "maxNumDay": "59",
        "enableTimeTo": "2022-07-09 23:59:59",
        "issueNum": "0",
        "showOrder": "1",
        "acquireType": "3",
        "maxNum": null,
        "birthdayFlag": null,
        "couponPicUrl": null,
        "openTimeFrom": "2021-07-09 00:00:00",
        "couponTypeId": "20",
        "pointsValue": "0",
        "notSentCouponCount": null,
        "contentTextApp": null,
        "jumpValue": null,
        "jumpType": "13",
        "couponChannelType": null,
        "couponName": "快到家PLUS折扣券5折",
        "couponType": "折扣券",
        "openTimeTo": "2022-07-09 23:59:59",
        "maxNumPerUser": null,
        "couponDesc": "快到家PLUS折扣券快到家PLUS折扣券",
        "canAcquireCoupon": "Y",
        "couponTemplateId": "291116950",
        "suitShopCount": null,
        "couponShortDesc": "快到家PLUS折扣券",
        "acquireFlag": "0",
        "userCouponCount": "0",
        "mpShopName": null,
        "couponScope": "0",
        "nextGenerateTime": null,
        "currentGenerateTime": "",
        "buttonFlag": "1",
        "receiveFlag": "1",
        "alreadyPercentNum": "0",
        "noticeDesc1": null,
        "noticeDesc2": null,
        "conditionAmount": null,
        "conditionFlag": null,
        "plusFlag": "1",
        "plusWeightFlag": "0"
      },
      {
        "couponCode": null,
        "couponRuleId": null,
        "contentTextPc": null,
        "erCode": null,
        "cloudFlag": "0",
        "signinAcquire": "1",
        "isAcquiredCoupon": "N",
        "userDayCouponCount": "0",
        "merchants": null,
        "waitDays": "5",
        "offsetAmount": "6",
        "maxNumPerUserDay": null,
        "produceNum": null,
        "couponListUrl": null,
        "dayCouponCount": "1000",
        "enableTimeFrom": null,
        "buttonFlagMsg": "已领完",
        "contentTextScreen": null,
        "siteStore": null,
        "stores": null,
        "effectDays": "1",
        "couponDetailUrl": null,
        "useChannel": "1,2,22",
        "validType": "1",
        "maxNumDay": "1000",
        "enableTimeTo": null,
        "issueNum": "0",
        "showOrder": "1",
        "acquireType": "3",
        "maxNum": null,
        "birthdayFlag": null,
        "couponPicUrl": null,
        "openTimeFrom": "2020-07-01 00:00:00",
        "couponTypeId": "11",
        "pointsValue": "0",
        "notSentCouponCount": null,
        "contentTextApp": null,
        "jumpValue": null,
        "jumpType": "2",
        "couponChannelType": null,
        "couponName": "无固定期限-到家PLUS6元抵用券",
        "couponType": "抵用券",
        "openTimeTo": "2022-07-01 23:59:59",
        "maxNumPerUser": null,
        "couponDesc": "无固定期限-到家PLUS6元抵用券无固定期限-到家PLUS6元抵用券",
        "canAcquireCoupon": "N",
        "couponTemplateId": "290841284",
        "suitShopCount": null,
        "couponShortDesc": "无固定期限-到家PLUS6元抵用券",
        "acquireFlag": "1",
        "userCouponCount": "0",
        "mpShopName": null,
        "couponScope": "0",
        "nextGenerateTime": null,
        "currentGenerateTime": "",
        "buttonFlag": "3",
        "receiveFlag": "4",
        "alreadyPercentNum": "100",
        "noticeDesc1": null,
        "noticeDesc2": null,
        "conditionAmount": null,
        "conditionFlag": null,
        "plusFlag": "0",
        "plusWeightFlag": "0"
      },
      {
        "couponCode": null,
        "couponRuleId": null,
        "contentTextPc": null,
        "erCode": null,
        "cloudFlag": "0",
        "signinAcquire": "1",
        "isAcquiredCoupon": "Y",
        "userDayCouponCount": "0",
        "merchants": null,
        "waitDays": null,
        "offsetAmount": "6",
        "maxNumPerUserDay": null,
        "produceNum": null,
        "couponListUrl": null,
        "dayCouponCount": "1",
        "enableTimeFrom": "2020-07-01 00:00:00",
        "buttonFlagMsg": "已领取",
        "contentTextScreen": null,
        "siteStore": null,
        "stores": null,
        "effectDays": null,
        "couponDetailUrl": null,
        "useChannel": "1,2,22",
        "validType": "0",
        "maxNumDay": "47",
        "enableTimeTo": "2022-07-01 23:59:59",
        "issueNum": "0",
        "showOrder": "1",
        "acquireType": "3",
        "maxNum": null,
        "birthdayFlag": null,
        "couponPicUrl": null,
        "openTimeFrom": "2020-07-01 00:00:00",
        "couponTypeId": "11",
        "pointsValue": "0",
        "notSentCouponCount": null,
        "contentTextApp": null,
        "jumpValue": null,
        "jumpType": "2",
        "couponChannelType": null,
        "couponName": "【复制290763506】已领完-到家PLUS6元抵用券",
        "couponType": "抵用券",
        "openTimeTo": "2022-07-01 23:59:59",
        "maxNumPerUser": null,
        "couponDesc": "已领完-到家PLUS6元抵用券已领完-到家PLUS6元抵用券",
        "canAcquireCoupon": "N",
        "couponTemplateId": "290784152",
        "suitShopCount": null,
        "couponShortDesc": "已领完-到家PLUS6元抵用券",
        "acquireFlag": "2",
        "userCouponCount": "0",
        "mpShopName": null,
        "couponScope": "0",
        "nextGenerateTime": null,
        "currentGenerateTime": "",
        "buttonFlag": "2",
        "receiveFlag": "3",
        "alreadyPercentNum": "2",
        "noticeDesc1": null,
        "noticeDesc2": null,
        "conditionAmount": null,
        "conditionFlag": null,
        "plusFlag": "0",
        "plusWeightFlag": "0"
      },
      {
        "couponCode": null,
        "couponRuleId": null,
        "contentTextPc": null,
        "erCode": null,
        "cloudFlag": "0",
        "signinAcquire": "1",
        "isAcquiredCoupon": "N",
        "userDayCouponCount": "0",
        "merchants": null,
        "waitDays": null,
        "offsetAmount": "6",
        "maxNumPerUserDay": null,
        "produceNum": null,
        "couponListUrl": null,
        "dayCouponCount": "1",
        "enableTimeFrom": "2021-07-01 00:00:00",
        "buttonFlagMsg": "已领完",
        "contentTextScreen": null,
        "siteStore": null,
        "stores": null,
        "effectDays": null,
        "couponDetailUrl": null,
        "useChannel": "1,22",
        "validType": "0",
        "maxNumDay": "1",
        "enableTimeTo": "2022-07-01 23:59:59",
        "issueNum": "0",
        "showOrder": "1",
        "acquireType": "3",
        "maxNum": null,
        "birthdayFlag": null,
        "couponPicUrl": null,
        "openTimeFrom": "2021-07-01 00:00:00",
        "couponTypeId": "11",
        "pointsValue": "0",
        "notSentCouponCount": null,
        "contentTextApp": null,
        "jumpValue": null,
        "jumpType": "2",
        "couponChannelType": null,
        "couponName": "已领完-到家PLUS6元抵用券",
        "couponType": "抵用券",
        "openTimeTo": "2022-07-01 23:59:59",
        "maxNumPerUser": null,
        "couponDesc": "已领完-到家PLUS6元抵用券已领完-到家PLUS6元抵用券",
        "canAcquireCoupon": "N",
        "couponTemplateId": "290763506",
        "suitShopCount": null,
        "couponShortDesc": "已领完-到家PLUS6元抵用券",
        "acquireFlag": "1",
        "userCouponCount": "0",
        "mpShopName": null,
        "couponScope": "0",
        "nextGenerateTime": null,
        "currentGenerateTime": "",
        "buttonFlag": "3",
        "receiveFlag": "4",
        "alreadyPercentNum": "100",
        "noticeDesc1": null,
        "noticeDesc2": null,
        "conditionAmount": null,
        "conditionFlag": null,
        "plusFlag": "0",
        "plusWeightFlag": "0"
      },
      {
        "couponCode": null,
        "couponRuleId": null,
        "contentTextPc": null,
        "erCode": null,
        "cloudFlag": "0",
        "signinAcquire": "1",
        "isAcquiredCoupon": "N",
        "userDayCouponCount": "0",
        "merchants": null,
        "waitDays": null,
        "offsetAmount": "5",
        "maxNumPerUserDay": null,
        "produceNum": null,
        "couponListUrl": null,
        "dayCouponCount": "1000",
        "enableTimeFrom": "2021-07-01 00:00:00",
        "buttonFlagMsg": "已领完",
        "contentTextScreen": null,
        "siteStore": null,
        "stores": null,
        "effectDays": null,
        "couponDetailUrl": null,
        "useChannel": "1,2,22",
        "validType": "0",
        "maxNumDay": "1000",
        "enableTimeTo": "2022-07-01 23:59:59",
        "issueNum": "0",
        "showOrder": "1",
        "acquireType": "3",
        "maxNum": null,
        "birthdayFlag": null,
        "couponPicUrl": null,
        "openTimeFrom": "2021-07-01 00:00:00",
        "couponTypeId": "20",
        "pointsValue": "0",
        "notSentCouponCount": null,
        "contentTextApp": null,
        "jumpValue": null,
        "jumpType": "13",
        "couponChannelType": null,
        "couponName": "到家满10元5折券",
        "couponType": "折扣券",
        "openTimeTo": "2022-07-01 23:59:59",
        "maxNumPerUser": null,
        "couponDesc": "到家满10元5折券到家满10元5折券到家满10元5折券",
        "canAcquireCoupon": "N",
        "couponTemplateId": "290719068",
        "suitShopCount": null,
        "couponShortDesc": "到家满10元5折券",
        "acquireFlag": "1",
        "userCouponCount": "0",
        "mpShopName": null,
        "couponScope": "0",
        "nextGenerateTime": null,
        "currentGenerateTime": "",
        "buttonFlag": "3",
        "receiveFlag": "4",
        "alreadyPercentNum": "100",
        "noticeDesc1": null,
        "noticeDesc2": null,
        "conditionAmount": null,
        "conditionFlag": null,
        "plusFlag": "0",
        "plusWeightFlag": "0"
      },
      {
        "couponCode": null,
        "couponRuleId": null,
        "contentTextPc": null,
        "erCode": null,
        "cloudFlag": "0",
        "signinAcquire": "1",
        "isAcquiredCoupon": "N",
        "userDayCouponCount": "0",
        "merchants": null,
        "waitDays": null,
        "offsetAmount": "6",
        "maxNumPerUserDay": null,
        "produceNum": null,
        "couponListUrl": null,
        "dayCouponCount": "0",
        "enableTimeFrom": "2021-07-01 00:00:00",
        "buttonFlagMsg": "立即领取",
        "contentTextScreen": null,
        "siteStore": null,
        "stores": null,
        "effectDays": null,
        "couponDetailUrl": null,
        "useChannel": "1,2,22",
        "validType": "0",
        "maxNumDay": "93",
        "enableTimeTo": "2022-07-01 23:59:59",
        "issueNum": "0",
        "showOrder": "1",
        "acquireType": "3",
        "maxNum": null,
        "birthdayFlag": null,
        "couponPicUrl": null,
        "openTimeFrom": "2021-07-01 00:00:00",
        "couponTypeId": "11",
        "pointsValue": "0",
        "notSentCouponCount": null,
        "contentTextApp": null,
        "jumpValue": null,
        "jumpType": "2",
        "couponChannelType": null,
        "couponName": "到家PLUS6元抵用券",
        "couponType": "抵用券",
        "openTimeTo": "2022-07-01 23:59:59",
        "maxNumPerUser": null,
        "couponDesc": "到家PLUS6元抵用券到家PLUS6元抵用券到家PLUS6元抵用券",
        "canAcquireCoupon": "Y",
        "couponTemplateId": "290693890",
        "suitShopCount": null,
        "couponShortDesc": "到家PLUS6元抵用券",
        "acquireFlag": "0",
        "userCouponCount": "0",
        "mpShopName": null,
        "couponScope": "0",
        "nextGenerateTime": null,
        "currentGenerateTime": "2021-11-05 09:00:00",
        "buttonFlag": "1",
        "receiveFlag": "1",
        "alreadyPercentNum": "0",
        "noticeDesc1": null,
        "noticeDesc2": null,
        "conditionAmount": null,
        "conditionFlag": null,
        "plusFlag": "1",
        "plusWeightFlag": "0"
      },
      {
        "couponCode": null,
        "couponRuleId": null,
        "contentTextPc": null,
        "erCode": null,
        "cloudFlag": "0",
        "signinAcquire": "1",
        "isAcquiredCoupon": "Y",
        "userDayCouponCount": "0",
        "merchants": null,
        "waitDays": null,
        "offsetAmount": "20",
        "maxNumPerUserDay": null,
        "produceNum": null,
        "couponListUrl": null,
        "dayCouponCount": "1000",
        "enableTimeFrom": "2021-04-28 00:00:00",
        "buttonFlagMsg": "已领完",
        "contentTextScreen": null,
        "siteStore": null,
        "stores": null,
        "effectDays": null,
        "couponDetailUrl": null,
        "useChannel": "1",
        "validType": "0",
        "maxNumDay": "1000",
        "enableTimeTo": "2022-04-28 23:59:59",
        "issueNum": "0",
        "showOrder": "1",
        "acquireType": "3",
        "maxNum": null,
        "birthdayFlag": null,
        "couponPicUrl": null,
        "openTimeFrom": "2021-04-28 00:00:00",
        "couponTypeId": "11",
        "pointsValue": "0",
        "notSentCouponCount": null,
        "contentTextApp": null,
        "jumpValue": null,
        "jumpType": "2",
        "couponChannelType": null,
        "couponName": "满58减20抵用券",
        "couponType": "抵用券",
        "openTimeTo": "2022-04-28 23:59:59",
        "maxNumPerUser": null,
        "couponDesc": "满58减20抵用券满58减20抵用券满58减20抵用券",
        "canAcquireCoupon": "N",
        "couponTemplateId": "286479657",
        "suitShopCount": null,
        "couponShortDesc": "满58减20抵用券",
        "acquireFlag": "1",
        "userCouponCount": "0",
        "mpShopName": null,
        "couponScope": "0",
        "nextGenerateTime": null,
        "currentGenerateTime": "",
        "buttonFlag": "3",
        "receiveFlag": "3",
        "alreadyPercentNum": "100",
        "noticeDesc1": null,
        "noticeDesc2": null,
        "conditionAmount": null,
        "conditionFlag": null,
        "plusFlag": "0",
        "plusWeightFlag": "0"
      },
      {
        "couponCode": null,
        "couponRuleId": null,
        "contentTextPc": null,
        "erCode": null,
        "cloudFlag": "0",
        "signinAcquire": "1",
        "isAcquiredCoupon": "N",
        "userDayCouponCount": "0",
        "merchants": null,
        "waitDays": null,
        "offsetAmount": "4",
        "maxNumPerUserDay": null,
        "produceNum": null,
        "couponListUrl": null,
        "dayCouponCount": "0",
        "enableTimeFrom": "2021-04-07 20:54:30",
        "buttonFlagMsg": "立即领取",
        "contentTextScreen": null,
        "siteStore": null,
        "stores": null,
        "effectDays": null,
        "couponDetailUrl": null,
        "useChannel": "1,2,3",
        "validType": "0",
        "maxNumDay": "40",
        "enableTimeTo": "2022-04-15 23:59:59",
        "issueNum": "0",
        "showOrder": "1",
        "acquireType": "3",
        "maxNum": null,
        "birthdayFlag": null,
        "couponPicUrl": null,
        "openTimeFrom": "2021-04-07 00:00:00",
        "couponTypeId": "17",
        "pointsValue": "0",
        "notSentCouponCount": null,
        "contentTextApp": null,
        "jumpValue": null,
        "jumpType": "13",
        "couponChannelType": null,
        "couponName": "到家plus普通运费券lihangy",
        "couponType": "运费券",
        "openTimeTo": "2022-04-15 23:59:59",
        "maxNumPerUser": null,
        "couponDesc": "到家plus普通运费券lihangy",
        "canAcquireCoupon": "Y",
        "couponTemplateId": "284486664",
        "suitShopCount": null,
        "couponShortDesc": "到家plus普通运费券lihangy",
        "acquireFlag": "0",
        "userCouponCount": "0",
        "mpShopName": null,
        "couponScope": "1",
        "nextGenerateTime": null,
        "currentGenerateTime": "",
        "buttonFlag": "1",
        "receiveFlag": "1",
        "alreadyPercentNum": "0",
        "noticeDesc1": null,
        "noticeDesc2": null,
        "conditionAmount": null,
        "conditionFlag": null,
        "plusFlag": "1",
        "plusWeightFlag": "0"
      },
      {
        "couponCode": null,
        "couponRuleId": null,
        "contentTextPc": null,
        "erCode": null,
        "cloudFlag": "0",
        "signinAcquire": "1",
        "isAcquiredCoupon": "N",
        "userDayCouponCount": "0",
        "merchants": null,
        "waitDays": null,
        "offsetAmount": "10",
        "maxNumPerUserDay": null,
        "produceNum": null,
        "couponListUrl": null,
        "dayCouponCount": "0",
        "enableTimeFrom": "2021-04-06 20:54:30",
        "buttonFlagMsg": "立即领取",
        "contentTextScreen": null,
        "siteStore": null,
        "stores": null,
        "effectDays": null,
        "couponDetailUrl": null,
        "useChannel": "1,2,3",
        "validType": "0",
        "maxNumDay": "40",
        "enableTimeTo": "2022-04-15 23:59:59",
        "issueNum": "0",
        "showOrder": "1",
        "acquireType": "3",
        "maxNum": null,
        "birthdayFlag": null,
        "couponPicUrl": null,
        "openTimeFrom": "2021-04-06 00:00:00",
        "couponTypeId": "17",
        "pointsValue": "0",
        "notSentCouponCount": null,
        "contentTextApp": null,
        "jumpValue": null,
        "jumpType": "13",
        "couponChannelType": null,
        "couponName": "到家plus普通运费券406",
        "couponType": "运费券",
        "openTimeTo": "2022-04-15 23:59:59",
        "maxNumPerUser": null,
        "couponDesc": "plus普通运费券",
        "canAcquireCoupon": "Y",
        "couponTemplateId": "284424939",
        "suitShopCount": null,
        "couponShortDesc": "plus普通运费券",
        "acquireFlag": "0",
        "userCouponCount": "0",
        "mpShopName": null,
        "couponScope": "1",
        "nextGenerateTime": null,
        "currentGenerateTime": "",
        "buttonFlag": "1",
        "receiveFlag": "1",
        "alreadyPercentNum": "0",
        "noticeDesc1": null,
        "noticeDesc2": null,
        "conditionAmount": null,
        "conditionFlag": null,
        "plusFlag": "1",
        "plusWeightFlag": "0"
      }
    ]
  }
}
