export default (req, res) => {
  const { page } = req.body
  const total_page = Math.max(0, 5 - page)

  // const list = Array.from({ length: 10 }, (t, idx) => ({}))
  const list = []

  const data = {
    ...mockData2,
  }

  setTimeout(() => {
    res.status(200).json({
      success: true,
      resCode: '00100000',
      timestamp: 1630897693687,
      obj: data,
    })
  }, 1000)
}

const mockData = {
  onOff: 'Y',
  templet: {
    temType: 1,
    mBy: '米萍',
    channel: 'APP',
    tabBar: {
      tabBarInfoList: [],
      backColor: '#FFFAF0',
      templetSid: 3770,
      cartNumColor: '#FF0000',
      bkPic: null,
      barType: 1,
      bkPicWidth: 750,
      bkPicHeight: 98,
      sid: 13984,
    },
    cTime: '2021-08-27 18:21:23',
    version: 1630573303000,
    sid: 3770,
    moduleList: [
      {
        pic1ButName: null,
        ssButName: null,
        mwButId: 56874,
        distance: null,
        smButId: 56869,
        syButId: 56871,
        pic1ResourceId: null,
        pic2ButName: null,
        searchResId: '2021082505',
        sid: 3829,
        styleType: 4,
        pic2ResourceId: null,
        bgType: 1,
        pic1: null,
        syButName: null,
        smButName: null,
        inStore: 1,
        pic2: null,
        zzButId: 56875,
        searchModeType: 1,
        pic1ButId: 56872,
        hyButName: null,
        bgWidth: 750,
        mdButId: 56867,
        moduleType: 'Head',
        pic1JumpType: null,
        entButton: '1,2',
        bgImg:
          'https://Img.st.iblimg.com/fast2home-2/images/kdj/index/2018/10/1010037442.jpg',
        pic1ModeType: 1,
        qdButName: null,
        entButtonList: [1, 2],
        hyButId: 56866,
        pic2ModeType: 1,
        backColor: '#FF774F',
        pic2ButId: 56873,
        qdButId: 56868,
        mdButName: null,
        zzButName: null,
        mwButName: null,
        pic2JumpType: null,
        ssButId: 56870,
        bgHeight: 350,
      },
      {
        styleType: 3,
        fcDef: '#221D1D',
        moduleType: 'Tab',
        fcActive: '#EA1616',
        showType: 1,
        busiType: 1,
        position: 1,
        tabItemList: [
          {
            resourceId: null,
            tabName: '联华到家',
            storeGoodsType: 1,
            butId: 56876,
            tabType: 1,
            addInfo: null,
            pic: null,
            labelTxt: null,
            showLabel: 0,
            sid: 3155,
            tabSid: 3137,
            modeType: 1,
            moduleList: [
              {
                picWidth: 750,
                styleType: 1,
                modeType: 1,
                resourceId: '2020102301',
                picHeight: 400,
                moduleType: 'VipProduct',
                buttonInfo: '58132&_&,58133&_&',
                buttonList: [
                  {
                    name: null,
                    id: 58132,
                  },
                  {
                    name: null,
                    id: 58133,
                  },
                ],
                resourceIdSec: null,
                sid: 12961,
              },
              {
                picWidth: 750,
                styleType: 1,
                isLogin: 1,
                modeType: 1,
                resourceId: '2020102302',
                picHeight: 240,
                moduleType: 'VipCoupon',
                buttonInfo: '55245&_&',
                buttonList: null,
                sid: 13111,
              },
              {
                picWidth: 750,
                bgWidth: null,
                resourceId: '20210207',
                picHeight: 350,
                moduleType: 'Slide',
                butId: 56879,
                showBg: 0,
                showRadius: 8,
                showAddr: 1,
                sid: 13735,
                bgPic: null,
                styleType: 1,
                modeType: 1,
                bgColor: null,
                butName: null,
                bgHeight: null,
              },
              {
                styleType: 1,
                modeType: 1,
                resourceId: '201808201637',
                moduleType: 'Notify',
                butId: 56880,
                showType: 1,
                pic: 'https://Img.st.iblimg.com/fast2home-2/images/kdj/index/2018/10/1640740375.png',
                butName: null,
                sid: 12896,
              },
              {
                styleType: 1,
                modeType: 1,
                resourceId: '2020010701',
                moduleType: 'Timer',
                butId: 56881,
                butName: null,
                sid: 12753,
              },
              {
                modeType: 1,
                resourceId: '2020010701',
                moduleType: 'Product',
                butId: 56882,
                showType: 4,
                productNum: 10,
                butName: null,
                sid: 15944,
              },
              {
                picWidth: 750,
                resourceId: '2021082506',
                picHeight: 350,
                moduleType: 'Picture',
                but1Id: 56883,
                but3Id: 56885,
                but2Id: 56884,
                but1Name: null,
                but5Id: 56887,
                sid: 16124,
                but3Name: null,
                but4Id: 56886,
                but5Name: null,
                but6Id: 56888,
                modeType: 1,
                showType: 5,
                but6Name: null,
                but4Name: null,
                but2Name: null,
              },
              {
                picWidth: 750,
                resourceId: '2020010703',
                picHeight: 350,
                moduleType: 'Picture',
                but1Id: 56889,
                but3Id: 56891,
                but2Id: 56890,
                but1Name: null,
                but5Id: 56893,
                sid: 16125,
                but3Name: null,
                but4Id: 56892,
                but5Name: null,
                but6Id: 56894,
                modeType: 1,
                showType: 1,
                but6Name: null,
                but4Name: null,
                but2Name: null,
              },
              {
                modeType: 1,
                resourceId: '2020010703',
                moduleType: 'Product',
                butId: 56895,
                showType: 5,
                productNum: 1,
                butName: null,
                sid: 15945,
              },
              {
                styleType: 1,
                modeType: 1,
                moduleType: 'WaterFall',
                sid: 360,
                wfList: [
                  {
                    picWidth: 343,
                    wfSid: 360,
                    resIdPic: '2021081802',
                    picHeight: 500,
                    scopeMax: 1,
                    butId: 58134,
                    contType: 2,
                    scopeMin: 1,
                    itemInd: 0,
                    sid: 872,
                    firstGoodsNum: null,
                    goodsTotal: 50,
                    showPic: 1,
                    resIdGoods: '2021081801',
                    butName: null,
                  },
                  {
                    picWidth: 343,
                    wfSid: 360,
                    resIdPic: '2021081802',
                    picHeight: 500,
                    scopeMax: 20,
                    butId: 58135,
                    contType: 1,
                    scopeMin: 1,
                    itemInd: 1,
                    sid: 873,
                    firstGoodsNum: null,
                    goodsTotal: 200,
                    showPic: 1,
                    resIdGoods: '2021081803',
                    butName: null,
                  },
                ],
              },
            ],
            picUn: null,
            tabInd: 0,
            butName: null,
          },
          {
            resourceId: null,
            tabName: 'B2C',
            storeGoodsType: 1,
            butId: 56898,
            tabType: 2,
            addInfo: null,
            pic: null,
            labelTxt: null,
            showLabel: 0,
            sid: 3156,
            tabSid: 3137,
            modeType: 1,
            moduleList: [],
            picUn: null,
            tabInd: 1,
            butName: null,
          },
        ],
        labelColor: '#000000',
        sid: 3137,
      },
    ],
    name: 'APP--联华到家武宁-新首页',
    cBy: '米萍',
    mTime: '2021-09-02 17:01:43',
    isDel: null,
    config: {
      cpPicType: 1,
      cpTitResId: null,
      prmButName: null,
      myCpButId: 56863,
      bkTopPic: null,
      prmResId: null,
      ctCpPicWidth: null,
      sid: 3209,
      cpButId: 56862,
      myCpPicType: 1,
      showPrm: 0,
      ctCpPicType: 1,
      prmPicHeight: 120,
      ctCpButName: null,
      adButId: null,
      getMoreCoupon: 0,
      adButName: null,
      ctCpButId: 56864,
      showCpPop: 1,
      c_popPriority: 'type:1,priority:1_type:2,priority:2',
      myCpPicWidth: null,
      adResId: null,
      popPriority: [
        {
          type: 1,
          priority: 1,
        },
        {
          type: 2,
          priority: 2,
        },
      ],
      showYyzz: 1,
      showAdPop: 0,
      prmButId: 56865,
      ctCpPic: null,
      backColor: '#F7F7F7',
      myCpPic: null,
      cpTitModeType: 1,
      templetSid: 3770,
      ctCpPicHeight: null,
      myCpPicHeight: null,
      adModeType: 1,
      cpPic: null,
      prmPicWidth: 120,
      cpButName: null,
      myCpButName: null,
    },
    tempType: 1,
    status: 1,
  },
}

const mockData2 = {
  onOff: 'Y',
  templet: {
    temType: 1,
    mBy: '王欣然',
    channel: 'APP',
    tabBar: {
      tabBarInfoList: [],
      backColor: ' #FFFFFF',
      templetSid: 3627,
      cartNumColor: '#F63333',
      barType: 1,
      sid: 14144,
    },
    cTime: '2021-09-03 10:57:43',
    version: 1630637877000,
    sid: 3627,
    moduleList: [
      {
        pic1ButName: '会员码',
        ssButName: '三组APP_搜索框',
        mwButId: 285218,
        distance: '500',
        smButId: 285213,
        syButId: 285215,
        pic2ButName: '扫码购',
        sid: 4110,
        styleType: 3,
        pic1: 'http://Img.iblimg.com/resh5-1/h5resource/kdj/app/hym.png',
        smButName: '三组APP_扫码购',
        inStore: 0,
        pic2: 'http://Img.iblimg.com/resh5-1/h5resource/kdj/app/smg.png',
        zzButId: 285219,
        pic1ButId: 285216,
        hyButName: '三组APP_会员码',
        mdButId: 285211,
        moduleType: 'Head',
        pic1JumpType: 3,
        entButton: '1,2',
        pic1ModeType: 1,
        entButtonList: [1, 2],
        hyButId: 285210,
        pic2ModeType: 1,
        backColor: '#FFFFFF',
        pic2ButId: 285217,
        qdButId: 285212,
        pic2JumpType: 4,
        ssButId: 285214,
      },
      {
        styleType: 2,
        moduleType: 'Tab',
        showType: 1,
        position: 1,
        tabItemList: [
          {
            tabName: '即时达',
            butId: 285220,
            tabType: 1,
            labelTxt: '最快半小时达',
            showLabel: 1,
            sid: 3699,
            tabSid: 3151,
            modeType: 1,
            moduleList: [
              {
                picWidth: 750,
                styleType: 1,
                modeType: 1,
                resourceId: '2020112501',
                picHeight: 400,
                moduleType: 'VipProduct',
                buttonInfo: '285465&_&标超APP_新人价',
                buttonList: [{ name: '标超APP_新人价', id: 285465 }],
                sid: 12323,
              },
              {
                picWidth: 750,
                styleType: 1,
                isLogin: 1,
                modeType: 1,
                resourceId: '2020112502',
                picHeight: 240,
                moduleType: 'VipCoupon',
                buttonInfo: '209895&_&三组APP_新人券',
                sid: 11269,
              },
              {
                picWidth: 750,
                resourceId: '6601',
                picHeight: 300,
                moduleType: 'Slide',
                butId: 285222,
                showBg: 0,
                showAddr: 0,
                sid: 16429,
                styleType: 1,
                modeType: 1,
                butName: '标超APP_轮播',
              },
              {
                picWidth: 750,
                resourceId: '6671',
                picHeight: 170,
                moduleType: 'Picture',
                but1Id: 285223,
                but3Id: 285225,
                but2Id: 285224,
                but1Name: '标超APP_海景1',
                but5Id: 285227,
                sid: 47255,
                but4Id: 285226,
                but6Id: 285228,
                modeType: 1,
                showType: 1,
              },
              {
                styleType: 1,
                modeType: 1,
                resourceId: '6542',
                moduleType: 'Notify',
                butId: 285229,
                showType: 2,
                pic: 'https://Img.iblimg.com/fast2home-2/images/kdj/index/2019/12/1643675870.png',
                butName: '标超APP_通知栏',
                sid: 13847,
              },
              {
                moduleType: 'Category',
                showText: 1,
                but1Id: 285231,
                buttonList: [
                  { id: 285230 },
                  { id: 285231 },
                  { id: 285232 },
                  { id: 285233 },
                  { id: 285234 },
                  { id: 285235 },
                  { id: 285236 },
                  { id: 285237 },
                  { id: 285238 },
                  { id: 285239 },
                ],
                but3Id: 285233,
                but2Id: 285232,
                but5Id: 285235,
                sid: 13818,
                but4Id: 285234,
                styleType: 3,
                modeType: 1,
                categoryInfoList: [
                  {
                    jumpType: 1,
                    butPriorEnd: 5,
                    butStart: 1,
                    butEnd: 1,
                    categoryId: 13818,
                    sid: 20664,
                    butPriorStart: 5,
                  },
                  {
                    jumpType: 1,
                    butPriorEnd: 3,
                    butStart: 2,
                    butEnd: 2,
                    categoryId: 13818,
                    sid: 20685,
                    butPriorStart: 3,
                  },
                  {
                    jumpType: 1,
                    butPriorEnd: 8,
                    butStart: 3,
                    butEnd: 5,
                    categoryId: 13818,
                    sid: 20686,
                    butPriorStart: 6,
                  },
                ],
                buttonInfo:
                  '285230&_&,285231&_&,285232&_&,285233&_&,285234&_&,285235&_&,285236&_&,285237&_&,285238&_&,285239&_&',
              },
              {
                moduleType: 'Category',
                showText: 1,
                sid: 13819,
                styleType: 1,
                modeType: 1,
                categoryInfoList: [
                  {
                    jumpType: 1,
                    butPriorEnd: 10,
                    butStart: 1,
                    butEnd: 1,
                    categoryId: 13819,
                    sid: 20687,
                    butPriorStart: 10,
                  },
                  {
                    jumpType: 1,
                    butPriorEnd: 13,
                    butStart: 2,
                    butEnd: 2,
                    categoryId: 13819,
                    sid: 20688,
                    butPriorStart: 13,
                  },
                  {
                    jumpType: 1,
                    butPriorEnd: 17,
                    butStart: 3,
                    butEnd: 5,
                    categoryId: 13819,
                    sid: 20689,
                    butPriorStart: 15,
                  },
                ],
              },
              {
                picWidth: 750,
                resourceId: '6614',
                picHeight: 170,
                moduleType: 'Picture',
                but1Id: 285240,
                but3Id: 285242,
                but2Id: 285241,
                but1Name: '标超APP_海景2',
                but5Id: 285244,
                sid: 47256,
                but4Id: 285243,
                but6Id: 285245,
                modeType: 1,
                showType: 1,
              },
              {
                picWidth: 375,
                resourceId: '20210501',
                picHeight: 135,
                moduleType: 'Picture',
                but1Id: 285246,
                but3Id: 285248,
                but2Id: 285247,
                but1Name: '标超APP_海景下两框1',
                but5Id: 285250,
                sid: 47257,
                but4Id: 285249,
                but6Id: 285251,
                modeType: 1,
                showType: 2,
                but2Name: '标超APP_海景下两框1',
              },
              {
                picWidth: 750,
                resourceId: '2022',
                picHeight: 110,
                moduleType: 'Picture',
                but1Id: 285252,
                but3Id: 285254,
                but2Id: 285253,
                but1Name: '标超APP_热销爆款',
                but5Id: 285256,
                sid: 47258,
                but4Id: 285255,
                but6Id: 285257,
                modeType: 1,
                showType: 1,
              },
              {
                modeType: 1,
                resourceId: '2022',
                moduleType: 'Product',
                butId: 285258,
                showType: 4,
                productNum: 30,
                butName: '标超APP_热销爆款',
                sid: 34705,
              },
              {
                styleType: 1,
                modeType: 1,
                resourceId: '6619',
                moduleType: 'Timer',
                butId: 285259,
                butName: '标超APP_限时抢',
                sid: 13185,
              },
              {
                modeType: 1,
                resourceId: '6619',
                moduleType: 'Product',
                butId: 285260,
                showType: 4,
                productNum: 30,
                butName: '标超APP_限时抢',
                sid: 34706,
              },
              {
                picWidth: 376,
                resourceId: '6624',
                picHeight: 280,
                moduleType: 'Picture',
                but1Id: 285261,
                but3Id: 285263,
                but2Id: 285262,
                but1Name: '标超APP_四框左上',
                but5Id: 285265,
                sid: 47259,
                but3Name: '标超APP_四框左下',
                but4Id: 285264,
                but6Id: 285266,
                modeType: 1,
                showType: 5,
                but4Name: '标超APP_四框右下',
                but2Name: '标超APP_四框右上',
              },
              {
                picWidth: 750,
                resourceId: '6682',
                picHeight: 220,
                moduleType: 'Picture',
                but1Id: 285267,
                but3Id: 285269,
                but2Id: 285268,
                but1Name: '标超APP_四框下方',
                but5Id: 285271,
                sid: 47260,
                but4Id: 285270,
                but6Id: 285272,
                modeType: 1,
                showType: 1,
              },
              {
                picWidth: 750,
                resourceId: '20021301',
                picHeight: 110,
                moduleType: 'Picture',
                but1Id: 285273,
                but3Id: 285275,
                but2Id: 285274,
                but1Name: '标超APP_品牌条',
                but5Id: 285277,
                sid: 47261,
                but4Id: 285276,
                but6Id: 285278,
                modeType: 1,
                showType: 1,
              },
              {
                picWidth: 250,
                resourceId: '20021302',
                picHeight: 220,
                moduleType: 'Picture',
                but1Id: 285279,
                but3Id: 285281,
                but2Id: 285280,
                but1Name: '标超APP_三框左',
                but5Id: 285283,
                sid: 47262,
                but3Name: '标超APP_三框右',
                but4Id: 285282,
                but6Id: 285284,
                modeType: 1,
                showType: 3,
                but2Name: '标超APP_三框中',
              },
              {
                picWidth: 750,
                resourceId: '6621',
                picHeight: 110,
                moduleType: 'Picture',
                but1Id: 285285,
                but3Id: 285287,
                but2Id: 285286,
                but1Name: '标超APP_超值价',
                but5Id: 285289,
                sid: 47263,
                but4Id: 285288,
                but6Id: 285290,
                modeType: 1,
                showType: 1,
              },
              {
                modeType: 1,
                resourceId: '6621',
                moduleType: 'Product',
                butId: 285291,
                showType: 4,
                productNum: 50,
                butName: '标超APP_超值价',
                sid: 34707,
              },
              {
                picWidth: 750,
                resourceId: '6678',
                picHeight: 110,
                moduleType: 'Picture',
                but1Id: 285292,
                but3Id: 285294,
                but2Id: 285293,
                but1Name: '标超APP_当季优选',
                but5Id: 285296,
                sid: 47264,
                but4Id: 285295,
                but6Id: 285297,
                modeType: 1,
                showType: 1,
              },
              {
                modeType: 1,
                resourceId: '6678',
                moduleType: 'Product',
                butId: 285298,
                showType: 4,
                productNum: 30,
                butName: '标超APP_当季优选',
                sid: 34708,
              },
              {
                picWidth: 750,
                resourceId: '6669',
                picHeight: 220,
                moduleType: 'Slide',
                butId: 285299,
                showBg: 0,
                showAddr: 0,
                sid: 16430,
                styleType: 1,
                modeType: 1,
                butName: '标超APP_中部轮播',
              },
              {
                picWidth: 750,
                resourceId: '6628',
                picHeight: 220,
                moduleType: 'Picture',
                but1Id: 285300,
                but3Id: 285302,
                but2Id: 285301,
                but1Name: '标超APP_楼层一标题',
                but5Id: 285304,
                sid: 47265,
                but4Id: 285303,
                but6Id: 285305,
                modeType: 1,
                showType: 1,
              },
              {
                modeType: 1,
                resourceId: '6628',
                moduleType: 'Product',
                butId: 285306,
                showType: 5,
                productNum: 30,
                butName: '标超APP_楼层一商品',
                sid: 34709,
              },
              {
                picWidth: 750,
                resourceId: '6631',
                picHeight: 220,
                moduleType: 'Picture',
                but1Id: 285307,
                but3Id: 285309,
                but2Id: 285308,
                but1Name: '标超APP_楼层二标题',
                but5Id: 285311,
                sid: 47266,
                but4Id: 285310,
                but6Id: 285312,
                modeType: 1,
                showType: 1,
              },
              {
                modeType: 1,
                resourceId: '6631',
                moduleType: 'Product',
                butId: 285313,
                showType: 5,
                productNum: 30,
                butName: '标超APP_楼层二商品',
                sid: 34710,
              },
              {
                picWidth: 750,
                resourceId: '6635',
                picHeight: 220,
                moduleType: 'Picture',
                but1Id: 285314,
                but3Id: 285316,
                but2Id: 285315,
                but1Name: '标超APP_楼层三标题',
                but5Id: 285318,
                sid: 47267,
                but4Id: 285317,
                but6Id: 285319,
                modeType: 1,
                showType: 1,
              },
              {
                modeType: 1,
                resourceId: '6635',
                moduleType: 'Product',
                butId: 285320,
                showType: 5,
                productNum: 30,
                butName: '标超APP_楼层三商品',
                sid: 34711,
              },
              {
                picWidth: 750,
                resourceId: '6638',
                picHeight: 220,
                moduleType: 'Picture',
                but1Id: 285321,
                but3Id: 285323,
                but2Id: 285322,
                but1Name: '标超APP_楼层四标题',
                but5Id: 285325,
                sid: 47268,
                but4Id: 285324,
                but6Id: 285326,
                modeType: 1,
                showType: 1,
              },
              {
                modeType: 1,
                resourceId: '6638',
                moduleType: 'Product',
                butId: 285327,
                showType: 5,
                productNum: 30,
                butName: '标超APP_楼层四商品',
                sid: 34712,
              },
              {
                picWidth: 750,
                resourceId: '6641',
                picHeight: 220,
                moduleType: 'Picture',
                but1Id: 285328,
                but3Id: 285330,
                but2Id: 285329,
                but1Name: '标超APP_楼层五标题',
                but5Id: 285332,
                sid: 47269,
                but4Id: 285331,
                but6Id: 285333,
                modeType: 1,
                showType: 1,
              },
              {
                modeType: 1,
                resourceId: '6641',
                moduleType: 'Product',
                butId: 285334,
                showType: 5,
                productNum: 30,
                butName: '标超APP_楼层五标题',
                sid: 34713,
              },
              {
                picWidth: 750,
                resourceId: '6644',
                picHeight: 220,
                moduleType: 'Picture',
                but1Id: 285335,
                but3Id: 285337,
                but2Id: 285336,
                but1Name: '标超APP_楼层六标题',
                but5Id: 285339,
                sid: 47270,
                but4Id: 285338,
                but6Id: 285340,
                modeType: 1,
                showType: 1,
              },
              {
                modeType: 1,
                resourceId: '6644',
                moduleType: 'Product',
                butId: 285341,
                showType: 5,
                productNum: 30,
                butName: '标超APP_楼层六商品',
                sid: 34714,
              },
              {
                picWidth: 750,
                resourceId: '6647',
                picHeight: 220,
                moduleType: 'Picture',
                but1Id: 285342,
                but3Id: 285344,
                but2Id: 285343,
                but1Name: '标超APP_楼层七标题',
                but5Id: 285346,
                sid: 47271,
                but4Id: 285345,
                but6Id: 285347,
                modeType: 1,
                showType: 1,
              },
              {
                modeType: 1,
                resourceId: '6647',
                moduleType: 'Product',
                butId: 285348,
                showType: 5,
                productNum: 30,
                butName: '标超APP_楼层七商品',
                sid: 34715,
              },
              {
                picWidth: 750,
                resourceId: '6650',
                picHeight: 220,
                moduleType: 'Picture',
                but1Id: 285349,
                but3Id: 285351,
                but2Id: 285350,
                but1Name: '标超APP_楼层八标题',
                but5Id: 285353,
                sid: 47272,
                but4Id: 285352,
                but6Id: 285354,
                modeType: 1,
                showType: 1,
              },
              {
                modeType: 1,
                resourceId: '6650',
                moduleType: 'Product',
                butId: 285355,
                showType: 5,
                productNum: 30,
                butName: '标超APP_楼层八商品',
                sid: 34716,
              },
              {
                picWidth: 750,
                resourceId: '6660',
                picHeight: 110,
                moduleType: 'Picture',
                but1Id: 285356,
                but3Id: 285358,
                but2Id: 285357,
                but1Name: '标超APP_猜你喜欢标题',
                but5Id: 285360,
                sid: 47273,
                but4Id: 285359,
                but6Id: 285361,
                modeType: 1,
                showType: 1,
              },
              {
                modeType: 1,
                resourceId: '6660',
                moduleType: 'Product',
                butId: 285362,
                showType: 3,
                productNum: 30,
                butName: '标超APP_猜你喜欢商品',
                sid: 34717,
              },
            ],
            tabInd: 0,
            butName: '标超APP_即时达',
          },
          {
            tabName: '超市精选',
            butId: 285363,
            tabType: 2,
            labelTxt: '满199减100起',
            showLabel: 1,
            sid: 3700,
            tabSid: 3151,
            modeType: 1,
            moduleList: [
              {
                picWidth: 750,
                resourceId: '8560',
                picHeight: 300,
                moduleType: 'Slide',
                butId: 285364,
                showBg: 0,
                showAddr: 0,
                sid: 16431,
                styleType: 1,
                modeType: 2,
              },
              {
                picWidth: 750,
                resourceId: '8503',
                picHeight: 60,
                moduleType: 'Picture',
                but1Id: 285365,
                but3Id: 285367,
                but2Id: 285366,
                but5Id: 285369,
                sid: 47274,
                but4Id: 285368,
                but6Id: 285370,
                modeType: 2,
                showType: 1,
              },
              {
                picWidth: 750,
                resourceId: '8502',
                picHeight: 60,
                moduleType: 'Picture',
                but1Id: 285371,
                but3Id: 285373,
                but2Id: 285372,
                but5Id: 285375,
                sid: 47275,
                but4Id: 285374,
                but6Id: 285376,
                modeType: 2,
                showType: 1,
              },
              {
                picWidth: 750,
                resourceId: '8562',
                picHeight: 230,
                moduleType: 'Picture',
                but1Id: 285377,
                but3Id: 285379,
                but2Id: 285378,
                but5Id: 285381,
                sid: 47276,
                but4Id: 285380,
                but6Id: 285382,
                modeType: 2,
                showType: 1,
              },
              {
                modeType: 2,
                resourceId: '8504',
                moduleType: 'Product',
                butId: 285383,
                showType: 4,
                productNum: 8,
                sid: 34718,
              },
              {
                picWidth: 750,
                resourceId: '8526',
                picHeight: 180,
                moduleType: 'Picture',
                but1Id: 285384,
                but3Id: 285386,
                but2Id: 285385,
                but5Id: 285388,
                sid: 47277,
                but4Id: 285387,
                but6Id: 285389,
                modeType: 2,
                showType: 1,
              },
              {
                picWidth: 375,
                resourceId: '8563',
                picHeight: 295,
                moduleType: 'Picture',
                but1Id: 285390,
                but3Id: 285392,
                but2Id: 285391,
                but5Id: 285394,
                sid: 47278,
                but4Id: 285393,
                but6Id: 285395,
                modeType: 2,
                showType: 2,
              },
              {
                picWidth: 375,
                resourceId: '8527',
                picHeight: 245,
                moduleType: 'Picture',
                but1Id: 285396,
                but3Id: 285398,
                but2Id: 285397,
                but5Id: 285400,
                sid: 47279,
                but4Id: 285399,
                but6Id: 285401,
                modeType: 2,
                showType: 5,
              },
              {
                picWidth: 375,
                resourceId: '8550',
                picHeight: 295,
                moduleType: 'Picture',
                but1Id: 285402,
                but3Id: 285404,
                but2Id: 285403,
                but5Id: 285406,
                sid: 47280,
                but4Id: 285405,
                but6Id: 285407,
                modeType: 2,
                showType: 2,
              },
              {
                picWidth: 250,
                resourceId: '8532',
                picHeight: 220,
                moduleType: 'Picture',
                but1Id: 285408,
                but3Id: 285410,
                but2Id: 285409,
                but5Id: 285412,
                sid: 47281,
                but4Id: 285411,
                but6Id: 285413,
                modeType: 2,
                showType: 3,
              },
              {
                picWidth: 750,
                resourceId: '8511',
                picHeight: 75,
                moduleType: 'Picture',
                but1Id: 285414,
                but3Id: 285416,
                but2Id: 285415,
                but5Id: 285418,
                sid: 47282,
                but4Id: 285417,
                but6Id: 285419,
                modeType: 2,
                showType: 1,
              },
              {
                picWidth: 750,
                resourceId: '8500',
                picHeight: 360,
                moduleType: 'Slide',
                butId: 285420,
                showBg: 0,
                showAddr: 0,
                sid: 16432,
                styleType: 1,
                modeType: 2,
              },
              {
                picWidth: 750,
                resourceId: '8514',
                picHeight: 75,
                moduleType: 'Picture',
                but1Id: 285421,
                but3Id: 285423,
                but2Id: 285422,
                but5Id: 285425,
                sid: 47283,
                but4Id: 285424,
                but6Id: 285426,
                modeType: 2,
                showType: 1,
              },
              {
                modeType: 2,
                resourceId: '8515',
                moduleType: 'Product',
                butId: 285427,
                showType: 3,
                productNum: 6,
                sid: 34719,
              },
              {
                picWidth: 750,
                resourceId: '8516',
                picHeight: 75,
                moduleType: 'Picture',
                but1Id: 285428,
                but3Id: 285430,
                but2Id: 285429,
                but5Id: 285432,
                sid: 47284,
                but4Id: 285431,
                but6Id: 285433,
                modeType: 2,
                showType: 1,
              },
              {
                modeType: 2,
                resourceId: '8517',
                moduleType: 'Product',
                butId: 285434,
                showType: 3,
                productNum: 9,
                sid: 34720,
              },
              {
                picWidth: 750,
                resourceId: '8518',
                picHeight: 360,
                moduleType: 'Slide',
                butId: 285435,
                showBg: 0,
                showAddr: 0,
                sid: 16433,
                styleType: 1,
                modeType: 2,
              },
              {
                picWidth: 750,
                resourceId: '8520',
                picHeight: 75,
                moduleType: 'Picture',
                but1Id: 285436,
                but3Id: 285438,
                but2Id: 285437,
                but5Id: 285440,
                sid: 47285,
                but4Id: 285439,
                but6Id: 285441,
                modeType: 2,
                showType: 1,
              },
              {
                modeType: 2,
                resourceId: '8521',
                moduleType: 'Product',
                butId: 285442,
                showType: 3,
                productNum: 6,
                sid: 34721,
              },
              {
                picWidth: 750,
                resourceId: '8522',
                picHeight: 75,
                moduleType: 'Picture',
                but1Id: 285443,
                but3Id: 285445,
                but2Id: 285444,
                but5Id: 285447,
                sid: 47286,
                but4Id: 285446,
                but6Id: 285448,
                modeType: 2,
                showType: 1,
              },
              {
                modeType: 2,
                resourceId: '8523',
                moduleType: 'Product',
                butId: 285449,
                showType: 3,
                productNum: 9,
                sid: 34722,
              },
              {
                picWidth: 750,
                resourceId: '8524',
                picHeight: 360,
                moduleType: 'Slide',
                butId: 285450,
                showBg: 0,
                showAddr: 0,
                sid: 16434,
                styleType: 1,
                modeType: 2,
              },
              {
                picWidth: 750,
                resourceId: '8528',
                picHeight: 75,
                moduleType: 'Picture',
                but1Id: 285451,
                but3Id: 285453,
                but2Id: 285452,
                but5Id: 285455,
                sid: 47287,
                but4Id: 285454,
                but6Id: 285456,
                modeType: 2,
                showType: 1,
              },
              {
                modeType: 2,
                resourceId: '8529',
                moduleType: 'Product',
                butId: 285457,
                showType: 3,
                productNum: 6,
                sid: 34723,
              },
              {
                picWidth: 750,
                resourceId: '8530',
                picHeight: 75,
                moduleType: 'Picture',
                but1Id: 285458,
                but3Id: 285460,
                but2Id: 285459,
                but5Id: 285462,
                sid: 47288,
                but4Id: 285461,
                but6Id: 285463,
                modeType: 2,
                showType: 1,
              },
              {
                modeType: 2,
                resourceId: '8531',
                moduleType: 'Product',
                butId: 285464,
                showType: 3,
                productNum: 9,
                sid: 34724,
              },
            ],
            tabInd: 1,
          },
        ],
        labelColor: '#000000',
        sid: 3151,
      },
    ],
    name: '标超-APP-0903new',
    cBy: '王欣然',
    mTime: '2021-09-03 10:57:57',
    config: {
      cpPicType: 1,
      myCpButId: 285208,
      sid: 3174,
      cpButId: 285207,
      myCpPicType: 1,
      ctCpPicType: 1,
      ctCpButName: '标超APP_领券中心',
      getMoreCoupon: 1,
      ctCpButId: 285209,
      showCpPop: 1,
      c_popPriority: 'type:1,priority:1_type:2,priority:2',
      popPriority: [
        { type: 1, priority: 1 },
        { type: 2, priority: 2 },
      ],
      showYyzz: 1,
      showAdPop: 0,
      backColor: '#F1F1F1',
      cpTitModeType: 1,
      templetSid: 3627,
      adModeType: 1,
      cpButName: '标超APP_优惠券弹框',
      myCpButName: '标超APP_我的券',
    },
    tempType: 1,
    status: 1,
  },
}
