import {
    mockData_test_dj
} from "../../../../../../mockData/dj/cateSkuDetails";

const API = (req, res) => {
    const { page } = req.body
    const total_page = Math.max(0, 5 - page)

    // const list = Array.from({ length: 10 }, (t, idx) => ({}))
    const list = []

    // const data = mockData
    // const goodsList = data.goodsList;
    // goodsList[0].tdType = "2";
    // goodsList[0].tdLable = "24h发货";

    // goodsList.forEach((t, idx) => t.categoryId = idList[idx])
    let obj = JSON.parse(JSON.stringify(mockData_test_dj))
    obj.obj.goodsList = obj.obj.goodsList.map((item, idx1) => {
        if (11 === idx1) {
            item.popinfosList = [
                ...item.popinfosList,
                ...item.popinfosList,
            ].map((item2, idx2) => {
                    // item2.sLabel = `${idx2}${item2.sLabel}${item2.sLabel}`
                    item2.sLabel = `到家全场`
                    return item2
                })
        } else {
            // item.popinfosList = []
        }
        return item
    })
    return new Promise(function (resolve) {
        setTimeout(resolve.bind(null, resolve), 1000)
    }).then(() => {
        res.status(200).json(obj)
    })
}
export default API

const mockData = {
    goodsList: [
        {
            id: "001100_60200011001@@1@@3284778",
            basePrice: "67.70",
            categoryId: "14924",
            comSid: "6000",
            goodsId: "3284778",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_207078108_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999172",
            salePrice: "57.70",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "1001",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: "1",
            productName: "恩替卡韦分散片0.5mg*7s",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "定位门店新人价",
                            id: "3525",
                        },
                    ],
                    activityType: "1",
                    activityTag: "定位门店新人",
                    memo: "定位门店新人",
                    labelDesc: "定位门店新人",
                    goodsDetSid: "3284778",
                    popDes: "买立减",
                    ruleid: "50505",
                    ruletype: "12",
                    ruleName: "专享",
                    activityId: "0",
                    shopid: "001100",
                    discountAmount: "57.7",
                    memberLimit: "10",
                    orderLimit: "1",
                    sLabel: "定位门店新人",
                    mLabel: "定位门店新人价",
                    lLabel: "53545",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14924: 1000,
                14928: 7127,
            },
        },
        {
            id: "001100_60200011001@@1@@3285363",
            basePrice: "77.70",
            categoryId: "14928",
            comSid: "6000",
            goodsId: "3285363",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_329118886_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "2999252",
            salePrice: "69.93",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "1002",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "香砂六君丸 200s",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "每第1件9.0折",
                            id: "7921",
                        },
                        {
                            desc: "每第2件8.0折",
                            id: "7922",
                        },
                        {
                            desc: "每第3件5.0折",
                            id: "7923",
                        },
                    ],
                    activityType: "1",
                    memo: "勿动-一件9折二件8折三件5折",
                    labelDesc: "勿动-一件9折二",
                    goodsDetSid: "3285363",
                    popDes: "折扣",
                    ruleid: "48584",
                    ruletype: "2",
                    ruleName: "折扣",
                    activityDesc: "勿动-一件9折二件8折三件5折_154746543",
                    activityId: "50035",
                    shopid: "001100",
                    buyMember: "0",
                    sLabel: "勿动-一件9折二",
                    mLabel: "勿动-一件9折二件8折三件5折",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14926: 1000,
                14112: 1000,
                14928: 1,
                14113: 2319,
            },
        },
        {
            id: "001100_60200011001@@1@@3284840",
            basePrice: "28.70",
            categoryId: "14924",
            comSid: "6000",
            goodsId: "3284840",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1970580453_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999017",
            salePrice: "30.33",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "1001",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: "1",
            productName: "盐酸乙哌立松片50mg*20s（薄膜衣）()",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "药到家新人价",
                            id: "3601",
                        },
                    ],
                    activityType: "1",
                    activityTag: "新人活动标签",
                    memo: "新人活动标签",
                    labelDesc: "新人活动标签",
                    goodsDetSid: "3284840",
                    popDes: "买立减",
                    ruleid: "50682",
                    ruletype: "12",
                    ruleName: "专享",
                    activityId: "0",
                    shopid: "001100",
                    discountAmount: "30.33",
                    memberLimit: "10",
                    orderLimit: "1",
                    sLabel: "新人活动标签",
                    mLabel: "新人价标签说明",
                    lLabel: "365346346",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14924: 1000,
                14928: 1943,
            },
        },
        {
            id: "001100_60200011001@@1@@3284842",
            basePrice: "18.70",
            categoryId: "14924",
            comSid: "6000",
            goodsId: "3284842",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_836629306_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999121",
            salePrice: "18.70",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "甲磺酸倍他司汀片6mg*30s",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14924: 1000,
                14928: 4314,
            },
        },
        {
            id: "001100_60200011001@@1@@3284581",
            basePrice: "88.33",
            categoryId: "14924",
            comSid: "6000",
            goodsId: "3284581",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1425248628_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "6999002",
            salePrice: "22.22",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "诺斯清 生理性海水鼻腔护理喷雾器 50ml(儿童)",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "每满58减5",
                            id: "11038",
                        },
                    ],
                    activityType: "1",
                    memo: "满减验证定位托底",
                    labelDesc: "满减验证定位托",
                    goodsDetSid: "3284581",
                    popDes: "满58减5",
                    ruleid: "48602",
                    discountType: "1",
                    conditionType: "1",
                    ruletype: "1",
                    ruleName: "满减",
                    activityDesc: "青浦满减10减1",
                    activityId: "48630",
                    shopid: "001100",
                    sLabel: "满减验证定位托",
                    mLabel: "满减验证定位托底",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14924: 1000,
                14903: 1000,
                14928: 1889,
                14110: 8822,
                14108: 4772,
            },
        },
        {
            id: "001100_60200011001@@1@@3284795",
            basePrice: "17.70",
            categoryId: "14928",
            comSid: "6000",
            goodsId: "3284795",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1283930173_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999036",
            salePrice: "15.93",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "1002",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "小麦纤维素颗粒测试113.5g*10s",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "每第1件9.0折",
                            id: "7921",
                        },
                        {
                            desc: "每第2件8.0折",
                            id: "7922",
                        },
                        {
                            desc: "每第3件5.0折",
                            id: "7923",
                        },
                    ],
                    activityType: "1",
                    memo: "勿动-一件9折二件8折三件5折",
                    labelDesc: "勿动-一件9折二",
                    goodsDetSid: "3284795",
                    popDes: "折扣",
                    ruleid: "48584",
                    ruletype: "2",
                    ruleName: "折扣",
                    activityDesc: "勿动-一件9折二件8折三件5折_154746543",
                    activityId: "50035",
                    shopid: "001100",
                    buyMember: "0",
                    sLabel: "勿动-一件9折二",
                    mLabel: "勿动-一件9折二件8折三件5折",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14927: 1000,
                14928: 1,
                14891: 1000,
            },
        },
        {
            id: "001100_60200011001@@1@@3357094",
            basePrice: "36.00",
            categoryId: "14110",
            comSid: "6000",
            goodsId: "3357094",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_499924188_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "2560001522",
            salePrice: "36.00",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "消毒酒精500ml",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14110: 4695,
            },
        },
        {
            id: "001456_60100014561@@1@@3285035",
            basePrice: "37.70",
            categoryId: "14110",
            comSid: "6000",
            goodsId: "3285035",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1680399849_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999210",
            salePrice: "37.70",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "复方多粘菌素B软膏 10g",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "2",
            tdLable: "24H内发货",
            pageCat: {
                14110: 1310,
            },
        },
        {
            id: "001456_60100014561@@1@@3285049",
            basePrice: "27.70",
            categoryId: "14924",
            comSid: "6000",
            goodsId: "3285049",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1715868217_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999286",
            salePrice: "27.70",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "盐酸左氧氟沙星眼用凝胶 5g:0.015g",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "药到家未登录不展示",
                            id: "3541",
                        },
                    ],
                    activityType: "1",
                    activityTag: "600019",
                    memo: "600019",
                    labelDesc: "600019",
                    goodsDetSid: "3285049",
                    popDes: "买立减",
                    ruleid: "50553",
                    ruletype: "12",
                    ruleName: "专享",
                    activityId: "0",
                    shopid: "001456",
                    memberLimit: "1",
                    orderLimit: "1",
                    sLabel: "600019",
                    mLabel: "60001999286",
                    lLabel: "60001999286",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "2",
            tdLable: "24H内发货",
            pageCat: {
                14924: 1,
                14893: 1000,
                14112: 1000,
                14896: 1000,
                14113: 3601,
            },
        },
        {
            id: "001100_60200011001@@1@@3286624",
            basePrice: "78.00",
            categoryId: "14924",
            comSid: "6000",
            goodsId: "3286624",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1266342987_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1003165",
            salePrice: "68.00",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "1001",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: "1",
            productName: "拜新同 硝苯地平控释片30mg*7片",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "药到家新人价",
                            id: "3602",
                        },
                    ],
                    activityType: "1",
                    activityTag: "新人活动标签",
                    memo: "新人活动标签",
                    labelDesc: "新人活动标签",
                    goodsDetSid: "3286624",
                    popDes: "买立减",
                    ruleid: "50682",
                    ruletype: "12",
                    ruleName: "专享",
                    activityId: "0",
                    shopid: "001100",
                    discountAmount: "68.0",
                    memberLimit: "10",
                    orderLimit: "1",
                    sLabel: "新人活动标签",
                    mLabel: "新人价标签说明",
                    lLabel: "365346346",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14924: 1000,
                14928: 6403,
                14110: 8102,
                14897: 1000,
                14108: 2941,
            },
        },
        {
            id: "001456_60100014561@@1@@3277293",
            basePrice: "165.60",
            categoryId: "14110",
            comSid: "6000",
            goodsId: "3277293",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1272016818_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1000262",
            salePrice: "165.60",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "纷纷富 碳酸钙片 0.75g*120片",
            pointTitle: null,
            saleStockSum: 7,
            marketOn: "1",
            type: null,
            brandCnName: "远大",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "1元1件",
                            id: "3864",
                        },
                    ],
                    activityType: "1",
                    memo: "一件任选5折",
                    labelDesc: "一件任选5折",
                    goodsDetSid: "3277293",
                    popDes: "1元1件",
                    ruleid: "50741",
                    ruletype: "7",
                    ruleName: "N元任选",
                    activityDesc: "一件任选5折",
                    activityId: "50742",
                    shopid: "001456",
                    sLabel: "一件任选5折",
                    mLabel: "一件任选5折",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "2",
            tdLable: "24H内发货",
            pageCat: {
                14110: 3515,
                14113: 5061,
                14108: 9766,
            },
        },
        {
            id: "001100_60200011001@@1@@3285079",
            basePrice: "77.70",
            categoryId: "14924",
            comSid: "6000",
            goodsId: "3285079",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1114902528_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "2999057",
            salePrice: "67.70",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "1001",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: "1",
            productName: "湿毒清胶囊",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "到家",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "药到家满立减",
                            id: "3531",
                        },
                    ],
                    activityType: "1",
                    activityTag: "药到家满立减",
                    memo: "药到家满立减",
                    labelDesc: "药到家满立减",
                    goodsDetSid: "3285079",
                    popDes: "买立减",
                    ruleid: "50527",
                    ruletype: "12",
                    ruleName: "专享",
                    activityId: "0",
                    shopid: "001100",
                    discountAmount: "67.7",
                    memberLimit: "1",
                    orderLimit: "1",
                    sLabel: "药到家满立减",
                    mLabel: "药到家满立减",
                    lLabel: "药到家满立减",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14926: 1000,
                14924: 2,
                14112: 1000,
                14928: 2,
                14110: 9819,
                14113: 3225,
            },
        },
        {
            id: "001456_60100014561@@1@@3285071",
            basePrice: "50000.00",
            categoryId: "14896",
            comSid: "6000",
            goodsId: "3285071",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_2090448465_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "2999017",
            salePrice: "40000000.00",
            plusPrice: "50000000.00",
            discountPrice: null,
            endTime: null,
            priceType: "1002",
            limitBuyPersonSum: null,
            personLimit: "10",
            saleStockStatus: "1",
            limitPopSum: null,
            productName:
                "全天麻胶囊全天麻胶囊全天麻胶囊全天麻胶囊全天麻胶囊全天麻胶囊全天麻胶囊全天麻胶囊",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "太平",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "每第1件8.0折",
                            id: "8481",
                        },
                    ],
                    activityType: "1",
                    memo: "药到家折扣",
                    labelDesc: "药到家折扣",
                    goodsDetSid: "3285071",
                    popDes: "折扣",
                    ruleid: "50695",
                    ruletype: "2",
                    ruleName: "PLUS折扣",
                    activityDesc: "60002999017",
                    activityId: "50696",
                    shopid: "001456",
                    buyMember: "1",
                    sLabel: "药到家折扣",
                    mLabel: "药到家折扣",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "2",
            tdLable: "24H内发货",
            pageCat: {
                14273: 1000,
                14111: 1000,
                14112: 1000,
                14896: 1000,
                14894: 5,
                14113: 1,
                14109: 5791,
            },
        },
        {
            id: "001100_60200011001@@1@@3285359",
            basePrice: "57.70",
            categoryId: "14928",
            comSid: "6000",
            goodsId: "3285359",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_753207381_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "2999231",
            salePrice: "57.70",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "驴胶补血颗粒 20g*20袋",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: null,
            popinfosList: [],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14926: 1000,
                14112: 1000,
                14928: 1,
                14113: 9191,
            },
        },
        {
            id: "001100_60200011001@@1@@3286625",
            basePrice: "199.00",
            categoryId: "14110",
            comSid: "6000",
            goodsId: "3286625",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1294116011_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "2000277",
            salePrice: "189.00",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "1001",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: "1",
            productName: "板蓝根颗粒10g*20袋",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "定位门店新人价",
                            id: "3526",
                        },
                    ],
                    activityType: "1",
                    activityTag: "定位门店新人",
                    memo: "定位门店新人",
                    labelDesc: "定位门店新人",
                    goodsDetSid: "3286625",
                    popDes: "买立减",
                    ruleid: "50505",
                    ruletype: "12",
                    ruleName: "专享",
                    activityId: "0",
                    shopid: "001100",
                    discountAmount: "189.0",
                    memberLimit: "10",
                    orderLimit: "1",
                    sLabel: "定位门店新人",
                    mLabel: "定位门店新人价",
                    lLabel: "53545",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14924: 1000,
                14903: 1000,
                14928: 6553,
                14110: 5228,
                14113: 3067,
                14108: 6559,
            },
        },
        {
            id: "001100_60200011001@@1@@3285362",
            basePrice: "77.70",
            categoryId: "14928",
            comSid: "6000",
            goodsId: "3285362",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_2047887520_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "2999240",
            salePrice: "77.70",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "清热暗疮丸 72s",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14926: 1000,
                14112: 1000,
                14928: 1,
                14113: 7445,
            },
        },
        {
            id: "001100_60200011001@@1@@3285364",
            basePrice: "77.70",
            categoryId: "14928",
            comSid: "6000",
            goodsId: "3285364",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_655673532_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "2999273",
            salePrice: "77.70",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "当归苦参丸 6g*6瓶",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14926: 1000,
                14112: 1000,
                14928: 1,
                14113: 3855,
            },
        },
        {
            id: "001100_60200011001@@1@@3284767",
            basePrice: "32.00",
            categoryId: "14110",
            comSid: "6000",
            goodsId: "3284767",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_379350671_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999304",
            salePrice: "5.55",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "多糖铁复合物胶囊0.15g*10s",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "到家",
            popinfosList: [],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14928: 6322,
                14110: 2531,
                14109: 9546,
            },
        },
        {
            id: "001100_60200011001@@1@@3284836",
            basePrice: "199.00",
            categoryId: "14924",
            comSid: "6000",
            goodsId: "3284836",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1568911135_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999229",
            salePrice: "179.00",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "1001",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: "1",
            productName: "布洛芬混悬液100ml",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "定位门店新人价",
                            id: "3527",
                        },
                    ],
                    activityType: "1",
                    activityTag: "定位门店新人",
                    memo: "定位门店新人",
                    labelDesc: "定位门店新人",
                    goodsDetSid: "3284836",
                    popDes: "买立减",
                    ruleid: "50505",
                    ruletype: "12",
                    ruleName: "专享",
                    activityId: "0",
                    shopid: "001100",
                    discountAmount: "179.0",
                    memberLimit: "1",
                    orderLimit: "1",
                    sLabel: "定位门店新人",
                    mLabel: "定位门店新人价",
                    lLabel: "53545",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14924: 1000,
                14928: 7272,
            },
        },
        {
            id: "001100_60200011001@@1@@3284841",
            basePrice: "11.00",
            categoryId: "14924",
            comSid: "6000",
            goodsId: "3284841",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1528227518_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999062",
            salePrice: "9.90",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "1002",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "石杉碱甲片50ug*40s",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "每第1件9.0折",
                            id: "7921",
                        },
                        {
                            desc: "每第2件8.0折",
                            id: "7922",
                        },
                        {
                            desc: "每第3件5.0折",
                            id: "7923",
                        },
                    ],
                    activityType: "1",
                    memo: "勿动-一件9折二件8折三件5折",
                    labelDesc: "勿动-一件9折二",
                    goodsDetSid: "3284841",
                    popDes: "折扣",
                    ruleid: "48584",
                    ruletype: "2",
                    ruleName: "折扣",
                    activityDesc: "勿动-一件9折二件8折三件5折_154746543",
                    activityId: "50035",
                    shopid: "001100",
                    buyMember: "0",
                    sLabel: "勿动-一件9折二",
                    mLabel: "勿动-一件9折二件8折三件5折",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14924: 1000,
                14928: 8754,
            },
        },
        {
            id: "001456_60100014561@@1@@3285434",
            basePrice: "33.33",
            categoryId: "14110",
            comSid: "6000",
            goodsId: "3285434",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_495539419_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999218",
            salePrice: "33.33",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "盐酸伐昔洛韦片0.15g*6s",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "2",
            tdLable: "24H内发货",
            pageCat: {
                14110: 3269,
            },
        },
        {
            id: "001456_60100014561@@1@@3285049",
            basePrice: "27.70",
            categoryId: "14896",
            comSid: "6000",
            goodsId: "3285049",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1715868217_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999286",
            salePrice: "27.70",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "盐酸左氧氟沙星眼用凝胶 5g:0.015g",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "药到家未登录不展示",
                            id: "3541",
                        },
                    ],
                    activityType: "1",
                    activityTag: "600019",
                    memo: "600019",
                    labelDesc: "600019",
                    goodsDetSid: "3285049",
                    popDes: "买立减",
                    ruleid: "50553",
                    ruletype: "12",
                    ruleName: "专享",
                    activityId: "0",
                    shopid: "001456",
                    memberLimit: "1",
                    orderLimit: "1",
                    sLabel: "600019",
                    mLabel: "60001999286",
                    lLabel: "60001999286",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "2",
            tdLable: "24H内发货",
            pageCat: {
                14924: 1,
                14893: 1000,
                14112: 1000,
                14896: 1000,
                14113: 3601,
            },
        },
        {
            id: "001456_60100014561@@1@@3285050",
            basePrice: "50000000000.00",
            categoryId: "14896",
            comSid: "6000",
            goodsId: "3285050",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_354870795_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999289",
            salePrice: "45000000000.00",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "1002",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "异维A酸红霉素凝胶 10g",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "每满10减1",
                            id: "10977",
                        },
                    ],
                    activityType: "1",
                    memo: "到家仅托底门店满减",
                    labelDesc: "托底门店满减",
                    goodsDetSid: "3285050",
                    popDes: "满10减1",
                    ruleid: "48494",
                    discountType: "1",
                    conditionType: "1",
                    ruletype: "1",
                    ruleName: "满减",
                    activityDesc: "药到家满减仅托底门店",
                    activityId: "48495",
                    shopid: "001456",
                    sLabel: "托底门店满减",
                    mLabel: "到家仅托底门店满减",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "2",
            tdLable: "24H内发货",
            pageCat: {
                14111: 1000,
                14893: 1000,
                14112: 1000,
                14896: 1000,
                14113: 4,
            },
        },
        {
            id: "001456_60100014561@@1@@3285356",
            basePrice: "17.70",
            categoryId: "14896",
            comSid: "6000",
            goodsId: "3285356",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1826831605_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "2999213",
            salePrice: "17.70",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "香砂养胃丸 200s",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "2",
            tdLable: "24H内发货",
            pageCat: {
                14110: 9936,
                14896: 1000,
                14113: 8090,
            },
        },
        {
            id: "001456_60100014561@@1@@3285034",
            basePrice: "27.70",
            categoryId: "14110",
            comSid: "6000",
            goodsId: "3285034",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1314968373_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999204",
            salePrice: "27.70",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "阿达帕林凝胶 15g:15mg",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "2",
            tdLable: "24H内发货",
            pageCat: {
                14110: 2926,
            },
        },
        {
            id: "001100_60200011001@@1@@3284845",
            basePrice: "48.70",
            categoryId: "14924",
            comSid: "6000",
            goodsId: "3284845",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1504735928_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999295",
            salePrice: "48.70",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "盐酸普拉克索片0.25mg*30s",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14924: 1000,
                14928: 8898,
            },
        },
        {
            id: "001100_60200011001@@1@@3286625",
            basePrice: "199.00",
            categoryId: "14924",
            comSid: "6000",
            goodsId: "3286625",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_1294116011_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "2000277",
            salePrice: "189.00",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "1001",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: "1",
            productName: "板蓝根颗粒10g*20袋",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "定位门店新人价",
                            id: "3526",
                        },
                    ],
                    activityType: "1",
                    activityTag: "定位门店新人",
                    memo: "定位门店新人",
                    labelDesc: "定位门店新人",
                    goodsDetSid: "3286625",
                    popDes: "买立减",
                    ruleid: "50505",
                    ruletype: "12",
                    ruleName: "专享",
                    activityId: "0",
                    shopid: "001100",
                    discountAmount: "189.0",
                    memberLimit: "10",
                    orderLimit: "1",
                    sLabel: "定位门店新人",
                    mLabel: "定位门店新人价",
                    lLabel: "53545",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14924: 1000,
                14903: 1000,
                14928: 6553,
                14110: 5228,
                14113: 3067,
                14108: 6559,
            },
        },
        {
            id: "001100_60200011001@@1@@3284789",
            basePrice: "47.70",
            categoryId: "14110",
            comSid: "6000",
            goodsId: "3284789",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_2024010194_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999305",
            salePrice: "46.70",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "1001",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: "1",
            productName: "大蒜素软胶囊 0.4g*20s",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "药到家新人价活动",
                            id: "3623",
                        },
                    ],
                    activityType: "1",
                    activityTag: "新人活动标签",
                    memo: "新人活动标签",
                    labelDesc: "新人活动标签",
                    goodsDetSid: "3284789",
                    popDes: "买立减",
                    ruleid: "50781",
                    ruletype: "12",
                    ruleName: "专享",
                    activityId: "0",
                    shopid: "001100",
                    discountAmount: "46.7",
                    memberLimit: "10",
                    orderLimit: "1",
                    sLabel: "新人活动标签",
                    mLabel: "新人价标签说明",
                    lLabel: "43534545",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14110: 1242,
                14109: 7836,
            },
        },
        {
            id: "001100_60200011001@@1@@3285060",
            basePrice: "97.70",
            categoryId: "14110",
            comSid: "6000",
            goodsId: "3285060",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_979639421_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999333",
            salePrice: "87.93",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "1002",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "他克莫司软膏 10g:0.03%",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "每第1件9.0折",
                            id: "7921",
                        },
                        {
                            desc: "每第2件8.0折",
                            id: "7922",
                        },
                        {
                            desc: "每第3件5.0折",
                            id: "7923",
                        },
                    ],
                    activityType: "1",
                    memo: "勿动-一件9折二件8折三件5折",
                    labelDesc: "勿动-一件9折二",
                    goodsDetSid: "3285060",
                    popDes: "折扣",
                    ruleid: "48584",
                    ruletype: "2",
                    ruleName: "折扣",
                    activityDesc: "勿动-一件9折二件8折三件5折_154746543",
                    activityId: "50035",
                    shopid: "001100",
                    buyMember: "0",
                    sLabel: "勿动-一件9折二",
                    mLabel: "勿动-一件9折二件8折三件5折",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14925: 4,
                14111: 1000,
                14112: 1000,
                14928: 2,
                14110: 1455,
                14113: 5651,
            },
        },
        {
            id: "001456_60100014561@@1@@3284777",
            basePrice: "35.00",
            categoryId: "14110",
            comSid: "6000",
            goodsId: "3284777",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_10497050_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999123",
            salePrice: "35.00",
            plusPrice: null,
            discountPrice: null,
            endTime: null,
            priceType: "0",
            limitBuyPersonSum: null,
            personLimit: null,
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "加巴喷丁胶囊0.1g*50s",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "2",
            tdLable: "24H内发货",
            pageCat: {
                14110: 7334,
            },
        },
        {
            id: "001100_60200011001@@1@@3285054",
            basePrice: "97.70",
            categoryId: "14928",
            comSid: "6000",
            goodsId: "3285054",
            goodsImage:
                "https://Img.st.iblimg.com/fast2homemethod-2/offlinegoods/goods/SP_856978571_200x200.jpg",
            goodsType: null,
            inStock: null,
            comGoodCode: "1999298",
            salePrice: "77.44",
            plusPrice: "88.00",
            discountPrice: null,
            endTime: null,
            priceType: "1002",
            limitBuyPersonSum: null,
            personLimit: "1",
            saleStockStatus: "1",
            limitPopSum: null,
            productName: "更昔洛韦眼用凝胶 5g:7.5mg",
            pointTitle: null,
            saleStockSum: 11,
            marketOn: "1",
            type: null,
            brandCnName: "无品牌",
            popinfosList: [
                {
                    rules: [
                        {
                            desc: "每第1件8.80折",
                            id: "8521",
                        },
                    ],
                    activityType: "1",
                    memo: "指定商品8.8折",
                    labelDesc: "指定商品8.8折",
                    goodsDetSid: "3285054",
                    popDes: "折扣",
                    ruleid: "50745",
                    ruletype: "2",
                    ruleName: "PLUS折扣",
                    activityDesc: "一件任选5折_143747911",
                    activityId: "50746",
                    shopid: "001100",
                    buyMember: "1",
                    sLabel: "指定商品8.8折",
                    mLabel: "指定商品8.8折",
                },
            ],
            previewList: [],
            xgList: [],
            from: null,
            tdType: "0",
            tdLable: null,
            pageCat: {
                14925: 3,
                14111: 1000,
                14112: 1000,
                14928: 2,
                14113: 1719,
            },
        },
    ],
}
